workspace "Channel 4 Core" "Enterprise Systems - Generated from LeanIX" {

    !identifiers hierarchical

    model {
    
        archetypes {
            application = container
        }
        
        /* ============================================================
           ORGANISATIONS / TEAMS (from LeanIX UserGroups)
           ============================================================ */
        
        cse = person "Client Sales & Engagement" ""
        part = person "Partnerships" ""
        so = person "Sales Operations" "Sales Operations handle the content supply chain for commercial content and plan placements withi..."
        agen = person "Agency" ""
        bt = person "Broadcast Technology" ""
        av = person "AV" ""
        at = person "Ad Tech" ""
        camp = person "Campaign" ""
        traf = person "Traffic" ""
        trad = person "Trading" ""
        paas = person "Presentation and Access Services" ""
        cf = person "Content Finance" ""
        comm = person "Communications" ""
        aiX = person "Audience Integration" ""
        clac = person "Corporate Legal and Compliance" "Sub-team of Commercial Affairs that handle legal and compliance for all our content. Assigning ce..."
        cd = person "Content Delivery" ""
        4stu = person "4Studio" ""
        prod = person "Product" ""
        pp = person "Partner Platform" "User group to describe partner platforms such as DUK, Youview or Sky"
        pi = person "Programme Information" "Programme Information provide distinctive, top quality, informative copy with the relevant tone o..."
        co = person "Commissioning Office" ""
        prodX = person "Producer" ""
        ca = person "Commercial Affairs" "The commercial affairs teams handle entitlements and agreements, including rights) with out conte..."
        cspX = person "Content Strategy & Planning" "The Content Strategy team plans exhibition windows for our content on linear and non-linear using..."
        yad = person "Youth and Digital" ""
        cm = person "Content Management" "Technical and business team that handle content media supply chain."
        ccf = person "Finance" ""
        sci = person "Strategy & Consumer Insight" ""
        mark = person "Marketing" ""
        inno = person "Innovation" ""
        daf = person "Daytime and Features" ""
        dram = person "Drama" ""
        fact = person "Factual" ""
        fe = person "Factual Entertainment" ""
        ncas = person "News, Current Affairs & Sport" ""
        f4 = person "Film 4" ""
        ba = person "Business Affairs" ""
        come = person "Comedy" ""
        coX = person "Commissioning Operations" ""
        ente = person "Entertainment" ""
        dd = person "Duty Desk" "Team that handles live content operations for our linear channels."
        peop = person "People" ""
        mve = person "MVE" ""
        4cre = person "4Creative" "Creative Team that creates new content for Channel 4."
        commX = person "Commercial" ""
        pf = person "Production Finance" ""
        paa = person "Programmatic and Audience" ""
        ds = person "Data Science" ""
        ar = person "Audience Research" ""
        tech = person "Technology" ""
        digi = person "Digital" ""
        dm = person "Digital Marketing" ""
        insi = person "Insights" ""
        c4 = person "Channel 4" ""
        ccfrss = person "Shared Services" "Team responsible for any financial transactional incoming and outgoing payment processing. Typica..."
        cpX = person "Consumer Product" ""
        dmp = person "Digital Marketing (Product)" ""
        cc = person "Content & Commissioning" ""
        corp = person "Corporate" ""
        er = person "Employee Relations" ""
        ct = person "Corporate Technology" ""
        lad = person "Learning and Development" ""
        proc = person "Procurement" ""
        clg = person "Corporate Legal & Governance" ""
        view = person "Viewer" ""
        a4e = person "All 4 Editorial" ""
        gs = person "Growth (Subscriptions)" ""
        fm = person "Facilities Management" ""

        /* ============================================================
           COMMERCIAL PLATFORM
           ============================================================ */
        
        cp = softwareSystem "Commercial Platform" "Platform from LeanIX" {
            
            ap = container "Agency Portal" "Empowering advertising agencies with their Channel4 campaign data." "paas"
            cari = container "Caria" "The platform on which UK & Irish airtime is traded, and upon which copy rotation instructions are..." "saas"
            cc = container "Copy Central" "Service that provides information about copy restrictions and/or certifications. Also known as Cl..." ""
            fsh = container "Freewheel Streaming Hub" "Freewheel Streaming Hub (aka MRM) is a software application that enables publishers and broadcast..." "saas"
            inno = container "Innovid" "Innovid is the only independent omni-channel advertising and analytics platform built for televis..." "saas"
            moat = container "Moat" "Moat enables measuring consumer attention across channels, devices, and platforms" "saas"
            sc = container "Sales CRM" "" ""
            stel = container "Stellar" "Channel4's Sales Order Processing System" "onPremise"
        }

        /* ============================================================
           CONTENT MANAGEMENT PLATFORM
           ============================================================ */
        
        bms = softwareSystem "Content Management Platform" "The applications and components that support the media management and linear scheduling for our l..." {
            
            asp = container "Access Service Provider" "" ""
            acf = container "Acquired Cash Forecast" "For the management of cashflow for acquired content, this is all captured on a spreadsheet called..." "desktopOrLaptop"
            bynd = container "Bynder" "Bynder is an AI-powered, SaaS DAM solution that allows brands to easily create, find and use thei..." "saas"
            c7t = container "C4 7A Titles" "Home grown system to schedule long form content on YouTube with workflow for Rights and Compliance." "saas"
            cmt = container "CMT" "Hosted by I2, CMT is a web-based tool with secure log-in credentials . The tool allows Long Term ..." "saas"
            dasdpwpswra = container "DTT Audio & Signing Date prompts with peak stats (with RB amendments)" "Business Objects report Displays the total volume of transmitted content during a time period, an..." ""
            et = container "Everyone TV" "Everyone TV is the new name for Digital UK. [JV with UK PSB's] NOTE: This is NOT an Application E..." ""
            grac = container "Gracenote" "Gracenote is the world’s leading entertainment data and technology company. We power the top musi..." "saas"
            mod = container "MediaGenix On Demand" "BeBanjo Movida VOD Management system (Comprising of systems which schedule and manage transcode a..." "saas"
            olss = container "OFCOM Licensing Services-Online Services-MIDCOM" "This is the OFCOM platform used by our Access Services team to upload of our reporting to OFCOM." ""
            osp = container "OnLine Service Provider" "Provides capabilities for ingest, transformation, transcoding, encryption and delivery of VOD; li..." "saas"
            ol = container "Order list" "Setting a budget and its' allocations genres & channels. Existing commitments also captured. Targ..." ""
            pira = container "Pirate" "Pirate is a collection of applications used by various departments. Commercial affairs (business ..." ""
            p4ws = container "4Producers (Web Site)" "eCommissioning system. Allows C4 to engage with Production companies for Production companies to ..." "saas"
            pass = container "Advance Scheduling System" "The Advanced Scheduling System (A55) provides a view of a schedule for a specific channel and dat..." "desktopOrLaptop"
            pbm = container "Brand Management" "An application where can create or update Pirate Brands. This enables the business to group toget..." "desktopOrLaptop"
            pc = container "Companies" "This application allows users to create companies like production companies, studios etc" "desktopOrLaptop"
            pcgs = container "Content Generation System" "Generates the required detailed metadata required for each target platform and sends the appropri..." "desktopOrLaptop"
            pcps = container "Content Planning System" "VOD Scheduling" "desktopOrLaptop"
            pdaprs = container "Director and Producer Reporting System" "DPRS Transmission/Sales Report This report works in various stages: 1. A list of all contract num..." "desktopOrLaptop"
            pfas = container "Film Advanced Scheduling" "Manages the film scheduling scenarios based on deals purchased" "desktopOrLaptop"
            pge = container "General Enquiry" "Contains query functionality and several reports that can be run based on a broad range of topics..." "desktopOrLaptop"
            pip = container "Interface Payments" "Maintenance tables for 1. Nominal accounts – specifying what codes are valid 2. Specifying which ..." "desktopOrLaptop"
            pitts = container "Interface To Transmission Systems" "ITS prepares final schedules for Playout systems. It uses Programme schedules generated from PPS ..." "onPremise"
            pmam = container "Management Account Maintenance" "Maintenance of reference data related to Management Accounts (Programme Finance)  Not used much,..." "desktopOrLaptop"
            pmm = container "Media Management" "Video browse can also be launched from this application" "desktopOrLaptop"
            pofg = container "OFCOM File Generator" "Review one or more channels for their compliance with statutory commercial minutage regulations. ..." "desktopOrLaptop"
            ppps = container "Presentation Planning System" "Manages the detailed channel schedules with all the relevant transmission content required for br..." "desktopOrLaptop"
            ppps-p = container "Presentation Planning System - PPS.NET" "This is the .NET version of PPS NOTE: We need to create all VOD processes and link one to this ap..." "desktopOrLaptop"
            ppp = container "Producers Portal" "An app which allows C4 to engage with Production companies for Production companies to fill in th..." "onPremise"
            ppc = container "Programme Certification" "Programme Certification gives the users of the system the ability look at the assets when they ar..." "desktopOrLaptop"
            prta2 = container "Real Time As-Run 2" "Provides real-time playout updates to Pirate systems." "onPremise"
            pswo = container "Stock Write Off" "Channel 4 commission or purchase programmes (stock) to be consumed by the schedule using annual t..." "desktopOrLaptop"
            psfv = container "Subtitle File Viewer" "Provides a view over the content of subtitles and the ability to quickly search for bad-language ..." "hybrid"
            ptis = container "Transcode Initiation Service" "TIS2 is the back-end engine of the VoD system, running background jobs ranging from asset synchro..." "onPremise"
            pvb = container "Video Browse" "Video Browse is a client-side.NET application that is part of the Pirate domain. It provides user..." "onPremise"
            pve = container "Viewer Enquiry" "Viewing the logged calls made by viewers regarding transmitted programmes. EXE name: VE" "desktopOrLaptop"
            pvmsv = container "VOD Management System (VMS)" "" "desktopOrLaptop"
            pvma = container "VoD Material Allocation" "VoD Material Allocation is small module inside Media Management. This module used by Programme Ma..." "desktopOrLaptop"
            pvt = container "VOD Tracker" "Support tool for monitoring VOD systems and workflows" "desktopOrLaptop"
            pt = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" ""
            pcX = container "Promo Create" "Hosted by I2, CMT is a web-based tool with secure log-in credentials . The tool allows Long Term ..." "saas"
            scf = container "Sky Curated Feeds" "Web application designed to create ordered curated lists for presentation on Sky UVP/VRP platforms" ""
            soun = container "Soundmouse" "Representation of Soundmouse as company. Covers all SaaS products offered by Soundmouse: Soundmou..." "saas"
            spape = container "Soundmouse Pre-TX and Post-TX Exporter" "Creates both Pre-TX and Post-TX export files to Soundmouse for music reporting and production rep..." ""
            spri = container "Sprinklr" "Sprinklr is a social media management platform that enables enterprise brands to connect with cus..." "saas"
            ssfatwswra = container "Subtitling Sep FLS and Teletext with Subtotals (with Ray Amendments)" "Business Objects Report 'Subtitling Sep FLS and Teletext with Subtotals (with Ray Amendments)' - ..." ""
            tb = container "The Bible" "The bible is a host of information related to the programme idea, such as the programme descripti..." "onPremise"
            typ = container "Three Year Plan" "" ""
        }

        /* ============================================================
           CONTENT SOURCING PLATFORM
           ============================================================ */
        
        csp = softwareSystem "Content Sourcing Platform" "Platform from LeanIX" {
            
            crmc = container "Customer Relationship Manager  (Content)" "A system used by the commissioning dept to track and manage programme ideas from pitch to greenlight" "paas"
            dist = container "Distributor" "Supplier of acquired content e.g. a US Studio" ""
            pasc = container "Acquisition Stock Control" "A Read-only/Live reporting tool, allowing users to track stock usage (available, scheduled, used)..." "desktopOrLaptop"
            pcf = container "Cashflow Forecasting" "Forecasting tool for managing cash, when are production companies actually going to be paid compa..." "desktopOrLaptop"
            pcc = container "Commissioning Cycle" "Manages the agreements of commissioned content." "desktopOrLaptop"
            pp = container "Programmes" "" "desktopOrLaptop"
            ppX = container "Purchases" "" "desktopOrLaptop"
            pc = container "Production Company" "Supplier of commissioned content e.g. All 3 Media NOTE: NOT an application" ""
        }

        /* ============================================================
           DATA AND ANALYTICS PLATFORM
           ============================================================ */
        
        dap = softwareSystem "Data and Analytics Platform" "An extensive Massive Parallel Processing (MPP) platform designed for analytics tasks, which inclu..." {
            
            as = container "Audience Segmentation" "Enables publishers and broadcasters to grow and retain audiences and increase monetisation for a ..." "saas"
            barb = container "BARB" "Founded by the major organisations in the UK television and advertising industry, BARB is respons..." "onPremise"
            bor = container "Business Objects Reporting" "This application represents all Business Object reports generated by BI team and are read by busi..." "hybrid"
            cedw = container "Enterprise Data Warehouse" "Data Warehouse application used as a host of analytics data in a star schema or a columnar databa..." "hybrid"
            c4 = container "Core 4" "https://www.core4.channel4.com/hub Core4 is Channel 4's quantitative insight community, made up o..." ""
            dcri = container "Data Clean Room (InfoSum)" "A data platform with a vision to connect the world’s data without ever sharing it – by developing..." "saas"
            dcrs = container "Data Clean Room (Snowflake)" "A data platform with a vision to connect the world’s data without ever sharing it – by developing..." "saas"
            df = container "Data Fabric" "Data Fabric is an innovative approach designed to simplify and streamline data management across ..." "saas"
            tabl = container "Tableau" "Tableau is a data visualization tool used in the Business Intelligence Industry. It helps in simp..." "saas"
            wa = container "Web Analytics" "Web Analytics software used by M&VE for All 4 & Online Services Adobe Analytics is the solution f..." "saas"
        }

        /* ============================================================
           FINANCE SYSTEMS PLATFORM
           ============================================================ */
        
        fsp = softwareSystem "Finance Systems Platform" "Platform from LeanIX" {
            
            atax = container "Alphatax" "Corporation tax compliance software, providing complete control over the preparation and manageme..." ""
            bbp = container "Barclays Banking Portal" "Barclays Online platform used to transact FX deals. File Gateway is a host to host connectivity p..." ""
            bdn = container "Barclays.Net" "Barclays service used to download statements." ""
            bsw = container "Basware" "Enterprise software for financial processes, purchase to pay and financial management. Manage Inv..." "saas"
            cmx = container "Cachematrix" "SaaS solution for cash management" ""
            ebs = container "E-Business Suite" "Channel4 Oracle E-business Suite application used in Finance department for Accounts, Cash and As..." "onPremise"
            faf = container "Finance Approval Form" "" ""
            msc = container "Mastercard" "" ""
            odf = container "Oracle eBS Excel data files" "These are a collection of manually generated .xslx files out of Oracle e-Business that contain va..." ""
            pjc = container "Project Codes" "App used to generate project codes which are used in Oracle and across Channel 4." ""
            sov = container "Sovos" "Sovos helps in digital transformation of tax, with complete, connected offerings for tax determin..." "saas"
            sbi = container "SplashBI" "SplashBI is an all-in-one framework for visualising, reporting and analysing data." "saas"
            tgn = container "Tungsten Network" "Tungsten provide a multiple distribution channel service to a single stream invoice feed." ""
            wda = container "Workday Adaptive" "Workday Adaptive is Channel 4 Finance's Planning and Consolidation tool" "saas"
        }

        /* ============================================================
           LINEAR PLAYOUT PLATFORM
           ============================================================ */
        
        lpp = softwareSystem "Linear Playout Platform" "Platform from LeanIX" {
            
            ac = container "Amagi Cloudport" "<https://www.amagi.com/products/cloudport-cloud-playout>\ \ Amagi CLOUDPORT supports media ingest..." "saas"
            lsp = container "Linear Service Provider" "" "saas"
            ppps = container "Presentation Planning System" "Manages the detailed channel schedules with all the relevant transmission content required for br..." "desktopOrLaptop"
            pt = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" ""
            sp = container "Stargate Portal" "" "saas"
        }

        /* ============================================================
           MARKETING PLATFORM
           ============================================================ */
        
        mp = softwareSystem "Marketing Platform" "Platform from LeanIX" {
            
            braz = container "Braze" "Braze is a mobile marketing automation platform that provides a CRM and multichannel messaging su..." "saas"
            mpar = container "mParticle" "mParticle is a Customer Data Platform. It collects customer data once through secure APIs and SDK..." "saas"
            po = container "Promo Optimizer" "User-friendly TV promo scheduling tool. Leveraging advanced optimization and sequencing algorithm..." ""
        }

        /* ============================================================
           MEDIA MANAGEMENT PLATFORM
           ============================================================ */
        
        mmp = softwareSystem "Media Management Platform" "Platform from LeanIX" {
            
            awar = container "Awards" "Awards is a repository of all awards won by Channel 4 or where Channel 4 has been nominated. Plat..." "saas"
            msp = container "Media Service Provider" "Service provider for Digital Asset Management System" "saas"
            pmm = container "Media Management" "Video browse can also be launched from this application" "desktopOrLaptop"
            pvb = container "Video Browse" "Video Browse is a client-side.NET application that is part of the Pirate domain. It provides user..." "onPremise"
            pt = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" ""
            ppsp = container "Post Production Service Provider" "Post production service is pre-integrated to MSP and has suites available in HFR. This work can b..." ""
            rta = container "Ready to Air" "Deliver pre-transmission & pre-release video to journalists securely and reliably, wherever they ..." ""
            uv = container "Underground Vault" "Team that handles live content operations for our linear channels.Controlled and secure location ..." ""
        }

        /* ============================================================
           PEOPLE SYSTEMS PLATFORM
           ============================================================ */
        
        psp = softwareSystem "People Systems Platform" "Platform from LeanIX" {
            
            4peo = container "4People" "4People is a cloud HR and people system that empowers mid-size organisations to effectively respo..." "saas"
            acti = container "ActivPay" "Actvipay is Channel 4's 3rd party payroll provider." "saas"
            ac = container "Alert Cascade" "Crisis event mass communication tool" "desktopOrLaptop"
            bp = container "Benefits Portal" "" "saas"
            er = container "Executive Reporting" "Bespoke set of reports created in Power BI and served for the purpose of business reporting for t..." "paas"
            fes = container "Freelancer Engagement System" "HR system to request freelancers and bring them onboard. Freelancers submit timesheets via FES. O..." "onPremise"
            ll = container "LinkedIn Learning" "LinkedIn Learning offers video courses taught by industry experts in software, creative, and busi..." "saas"
            popp = container "Poppulo" "Internal communications Internal Communication, newsletter system. Used by internal comms. Integr..." "saas"
            tlh = container "The Learning Hive" "Cornerstone is a cloud-based learning and talent management solutions platform." "saas"
        }

        /* ============================================================
           RIGHTS MANAGEMENT PLATFORM
           ============================================================ */
        
        rmp = softwareSystem "Rights Management Platform" "Platform from LeanIX" {
            
            prms = container "Rights Management System" "" "desktopOrLaptop"
            pt = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" ""
            rc = container "Repeats Clearances" "This excel spreadsheet is our record of all programmes repeated on C4 with details of any rights/..." ""
            soun = container "Soundmouse" "Representation of Soundmouse as company. Covers all SaaS products offered by Soundmouse: Soundmou..." "saas"
        }

        /* ============================================================
           ROYALTIES AND SALES PLATFORM
           ============================================================ */
        
        rsp = softwareSystem "Royalties and Sales Platform" "Platform from LeanIX" {
            
            come = container "COMET" "Channel 4 International and National Rights Licencing Software used by Channel 4 to manage Films ..." "desktopOrLaptop"
            eps = container "Exclusivity Payment Schedules" "Contains payment details due to the artist for an exclusivity deal" ""
            neo = container "Neo" "NEO is a Soundmouse application that 4Studio and Rights Team users use. NEO does a shazam of soci..." ""
            pap = container "Artist Payments" "Application for reporting artist royalties" "desktopOrLaptop"
            pris = container "Royalties Income system" "Manages the Statements and chasing of Statements to ensure Royalties owed to Channel 4 are tracke..." "desktopOrLaptop"
            prrs = container "Royalties Reporting System" "RRS Overview Description: The Royalty Reporting System (RRS) is an application used for the conso..." "onPremise"
            pt = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" ""
            rc = container "Repeats Clearances" "This excel spreadsheet is our record of all programmes repeated on C4 with details of any rights/..." ""
            sd = container "Sargent Disc" "Sargent-Disc is the U.K.’s foremost entertainment-technology provider, building cloud-based workf..." ""
            soun = container "Soundmouse" "Representation of Soundmouse as company. Covers all SaaS products offered by Soundmouse: Soundmou..." "saas"
            ted = container "Ted" "Ted is a (tactical) web application that is used by 4Studio to capture key information concerning..." "iaas"
            ussw = container "UK Secondary Sales Wishlist" "" ""
            vr = container "VOD Revenue" "" ""
            vwgmp = container "VOD Writers Guild & Musician Payments" "" ""
            wga = container "Writers Guild Advances" "" ""
        }

        /* ============================================================
           SCHEDULING PLATFORM
           ============================================================ */
        
        sp = softwareSystem "Scheduling Platform" "The Scheduling Platform is a core functional domain that orchestrates the creation and management..." {
            
            mod = container "MediaGenix On Demand" "BeBanjo Movida VOD Management system (Comprising of systems which schedule and manage transcode a..." "saas"
            pass = container "Advance Scheduling System" "The Advanced Scheduling System (A55) provides a view of a schedule for a specific channel and dat..." "desktopOrLaptop"
            pepl = container "Electronic Press Listing" "Sends Electronic Programme Guide to other platforms Carries Rights information such as restart" "desktopOrLaptop"
            pitts = container "Interface To Transmission Systems" "ITS prepares final schedules for Playout systems. It uses Programme schedules generated from PPS ..." "onPremise"
            ppps = container "Presentation Planning System" "Manages the detailed channel schedules with all the relevant transmission content required for br..." "desktopOrLaptop"
            ppps-p = container "Presentation Planning System - PPS.NET" "This is the .NET version of PPS NOTE: We need to create all VOD processes and link one to this ap..." "desktopOrLaptop"
        }

        /* ============================================================
           SMALL BUSINESS SERVICES
           ============================================================ */
        
        sbs = softwareSystem "Small Business Services" "A set of small applications delivering discreet business processes usually hosted on SQL on prem ..." {
            
            anda = container "ANDA" "ANDA is a document archive repository. Where physical documents need to be archived (signed contr..." "onPremise"
            comp = container "Competitions" "It is used by Legal & Compliance to select winners and runner ups for Channel 4 competitions. The..." "onPremise"
            cms = container "Contract Management System" "Contract Management System, used as a repository for contracts Owned by Procurement storing the m..." "onPremise"
            dsd = container "Diversity Suppliers DB" "This is a database of supplier information used by the Creative Diversity team based in Glasgow," "onPremise"
            fa = container "FOIA Application" "Application built on SQL Server for storing Freedom of Information Act requests" ""
            mc = container "Music Clearance" "It is used by colleagues in CACL - Commercial Affairs every time Channel 4 license a music track ..." "hybrid"
            pps = container "Post Production Schedule" "This application is used by 4Creative to plan the development of on-air promotional material and ..." ""
            pr = container "Producer Reporting" "It is used by Finance to format the producer reporting statements. The application takes all the ..." ""
            sac = container "Stills and Clips" "" ""
            time = container "Timesheets" "" "onPremise"
        }

        /* ============================================================
           VIDEO STREAMING PLATFORM
           ============================================================ */
        
        vsp = softwareSystem "Video Streaming Platform" "Includes all items that provide the value chain" {
            
            c4sl = container "Channel 4 Streaming (Legacy)" "Video on Demand platform across many devices including https://channel4.com" "iaas"
            cdna = container "Content Distribution Network (Accenture)" "Logical representation of the CDN's used by Channel 4 Streaming, controlled and maintained by Acc..." ""
            free = container "Freely" "" ""
            mpar = container "mParticle" "mParticle is a Customer Data Platform. It collects customer data once through secure APIs and SDK..." "saas"
            ova = container "Online Video Analytics" "Real-Time Streaming Video Intelligence" "saas"
            pipe = container "PIPE" "The CMS that drivers Channel 4 Streaming UX in the apps" "iaas"
            sm = container "Subscription Management" "The application that manages our subscription products such as offers and deals." "saas"
            sl = container "Sumo Logic" "Sumo Logic is a cloud-based log management and analytics service that leverages machine-generated..." "saas"
            tr = container "Tag Recommender" "A Data Science led application to aid the Channel 4 Streaming editors with tagging for Brands" "iaas"
            thin = container "ThinkAnalytics" "World leaders in AI personalized content discovery, hyper-targeted advertising and customer insight." "saas"
            yosp = container "YoSpace" "Dynamic Ad Insertion (replacement of linear ads) on live streams to our owned and operated stream..." "saas"
        }

        /* ============================================================
           WORKSPACE SYSTEMS PLATFORM
           ============================================================ */
        
        wsp = softwareSystem "Workspace Systems Platform" "Platform from LeanIX" {
            
            ac = container "Alert Cascade" "Crisis event mass communication tool" "desktopOrLaptop"
            ce = container "Concept Evolution" "FM Job sheets for building maintenance used by Facilities & Workspace" "onPremise"
            egen = container "Egencia" "Egencia is a SaaS platform developed by Amex GBT that offers corporate travel management solution..." "saas"
            tb = container "Taxi Booking" "This application describes are taxi booking capability at Channel 4." "saas"
            tb-n = container "Taxi Booking - non-London" "This application is used for London based Taxi bookings to and from Horseferry Road" "saas"
        }
        
        /* ============================================================
           PERSON -> APPLICATION RELATIONSHIPS
           ============================================================ */
        
        cseToAp = cse -> cp.ap "Uses"
        partToAp = part -> cp.ap "Uses"
        soToAp = so -> cp.ap "Uses"
        agenToAp = agen -> cp.ap "Uses"
        btToCari = bt -> cp.cari "Uses"
        agenToCari = agen -> cp.cari "Uses"
        soToCc = so -> cp.cc "Uses"
        soToFsh = so -> cp.fsh "Uses"
        soToInno = so -> cp.inno "Uses"
        avToSc = av -> cp.sc "AV = Audio Visual"
        soToSc = so -> cp.sc "Uses"
        atToSc = at -> cp.sc "Uses"
        cseToStel = cse -> cp.stel "Uses"
        partToStel = part -> cp.stel "Uses"
        soToStel = so -> cp.stel "Uses"
        campToStel = camp -> cp.stel "Uses"
        trafToStel = traf -> cp.stel "Uses"
        tradToStel = trad -> cp.stel "Uses"
        paasToAsp = paas -> bms.asp "Uses"
        cfToAcf = cf -> bms.acf "Uses"
        commToBynd = comm -> bms.bynd "Uses"
        aiXToBynd = aiX -> bms.bynd "Uses"
        partToC7t = part -> bms.c7t "Uses"
        clacToC7t = clac -> bms.c7t "Uses"
        cdToC7t = cd -> bms.c7t "Uses"
        4stuToC7t = 4stu -> bms.c7t "Uses"
        prodToC7t = prod -> bms.c7t "Uses"
        paasToDasdpwpswra = paas -> bms.dasdpwpswra "Uses"
        ppToEt = pp -> bms.et "Uses"
        ppToGrac = pp -> bms.grac "Uses"
        piToMod = pi -> bms.mod "Uses"
        paasToOlss = paas -> bms.olss "Uses"
        piToOsp = pi -> bms.osp "Uses"
        btToOsp = bt -> bms.osp "Uses"
        cfToOl = cf -> bms.ol "Uses"
        coToP4ws = co -> bms.p4ws "Uses"
        prodXToP4ws = prodX -> bms.p4ws "Uses"
        soToPass = so -> bms.pass "Uses"
        tradToPass = trad -> bms.pass "Uses"
        caToPass = ca -> bms.pass "Uses"
        cspXToPass = cspX -> bms.pass "Uses"
        yadToPass = yad -> bms.pass "Uses"
        cmToPass = cm -> bms.pass "Uses"
        ccfToPass = ccf -> bms.pass "Uses"
        sciToPass = sci -> bms.pass "Uses"
        markToPass = mark -> bms.pass "Uses"
        prodToPass = prod -> bms.pass "Uses"
        caToPbm = ca -> bms.pbm "Uses"
        ccfToPbm = ccf -> bms.pbm "Uses"
        cfToPbm = cf -> bms.pbm "Uses"
        innoToPc = inno -> bms.pc "Uses"
        caToPc = ca -> bms.pc "Uses"
        cspXToPc = cspX -> bms.pc "Uses"
        dafToPc = daf -> bms.pc "Uses"
        dramToPc = dram -> bms.pc "Uses"
        factToPc = fact -> bms.pc "Uses"
        feToPc = fe -> bms.pc "Uses"
        ncasToPc = ncas -> bms.pc "Uses"
        yadToPc = yad -> bms.pc "Uses"
        cmToPc = cm -> bms.pc "Uses"
        ccfToPc = ccf -> bms.pc "Uses"
        cfToPc = cf -> bms.pc "Uses"
        sciToPc = sci -> bms.pc "Uses"
        f4ToPc = f4 -> bms.pc "Uses"
        4stuToPc = 4stu -> bms.pc "Uses"
        markToPc = mark -> bms.pc "Uses"
        prodToPc = prod -> bms.pc "Uses"
        innoToPcgs = inno -> bms.pcgs "Uses"
        soToPcgs = so -> bms.pcgs "Uses"
        caToPcgs = ca -> bms.pcgs "Uses"
        dramToPcgs = dram -> bms.pcgs "Uses"
        ncasToPcgs = ncas -> bms.pcgs "Uses"
        cmToPcgs = cm -> bms.pcgs "Uses"
        piToPcgs = pi -> bms.pcgs "Uses"
        sciToPcgs = sci -> bms.pcgs "Uses"
        4stuToPcgs = 4stu -> bms.pcgs "Uses"
        commToPcgs = comm -> bms.pcgs "Uses"
        markToPcgs = mark -> bms.pcgs "Uses"
        prodToPcgs = prod -> bms.pcgs "Uses"
        innoToPcps = inno -> bms.pcps "Uses"
        soToPcps = so -> bms.pcps "Uses"
        caToPcps = ca -> bms.pcps "Uses"
        cspXToPcps = cspX -> bms.pcps "Uses"
        dramToPcps = dram -> bms.pcps "Uses"
        cmToPcps = cm -> bms.pcps "Uses"
        piToPcps = pi -> bms.pcps "Uses"
        prodToPcps = prod -> bms.pcps "Uses"
        baToPdaprs = ba -> bms.pdaprs "Uses"
        soToPfas = so -> bms.pfas "Uses"
        caToPfas = ca -> bms.pfas "Uses"
        cspXToPfas = cspX -> bms.pfas "Uses"
        ccfToPfas = ccf -> bms.pfas "Uses"
        sciToPfas = sci -> bms.pfas "Uses"
        innoToPge = inno -> bms.pge "Uses"
        soToPge = so -> bms.pge "Uses"
        tradToPge = trad -> bms.pge "Uses"
        caToPge = ca -> bms.pge "Uses"
        comeToPge = come -> bms.pge "Uses"
        coToPge = co -> bms.pge "Uses"
        coXToPge = coX -> bms.pge "Uses"
        cspXToPge = cspX -> bms.pge "Uses"
        dafToPge = daf -> bms.pge "Uses"
        dramToPge = dram -> bms.pge "Uses"
        enteToPge = ente -> bms.pge "Uses"
        factToPge = fact -> bms.pge "Uses"
        feToPge = fe -> bms.pge "Uses"
        ncasToPge = ncas -> bms.pge "Uses"
        yadToPge = yad -> bms.pge "Uses"
        cmToPge = cm -> bms.pge "Uses"
        cdToPge = cd -> bms.pge "Uses"
        ddToPge = dd -> bms.pge "Uses"
        paasToPge = paas -> bms.pge "Uses"
        piToPge = pi -> bms.pge "Not all information is available and needs to be obtained from other sources. Clunky"
        ccfToPge = ccf -> bms.pge "Uses"
        peopToPge = peop -> bms.pge "Uses"
        sciToPge = sci -> bms.pge "Uses"
        f4ToPge = f4 -> bms.pge "Uses"
        mveToPge = mve -> bms.pge "Uses"
        4creToPge = 4cre -> bms.pge "Uses"
        4stuToPge = 4stu -> bms.pge "Uses"
        commToPge = comm -> bms.pge "Uses"
        markToPge = mark -> bms.pge "Uses"
        prodToPge = prod -> bms.pge "Uses"
        yadToPip = yad -> bms.pip "Uses"
        cmToPip = cm -> bms.pip "Uses"
        ccfToPip = ccf -> bms.pip "Uses"
        cfToPip = cf -> bms.pip "Uses"
        markToPip = mark -> bms.pip "Uses"
        prodToPip = prod -> bms.pip "Uses"
        piToPitts = pi -> bms.pitts "Uses"
        soToPmam = so -> bms.pmam "Uses"
        cmToPmam = cm -> bms.pmam "Uses"
        ccfToPmam = ccf -> bms.pmam "Uses"
        cfToPmam = cf -> bms.pmam "Uses"
        soToPmm = so -> bms.pmm "Uses"
        caToPmm = ca -> bms.pmm "Uses"
        cspXToPmm = cspX -> bms.pmm "Uses"
        factToPmm = fact -> bms.pmm "Uses"
        ncasToPmm = ncas -> bms.pmm "Uses"
        yadToPmm = yad -> bms.pmm "Uses"
        cmToPmm = cm -> bms.pmm "Uses"
        cdToPmm = cd -> bms.pmm "Uses"
        4creToPmm = 4cre -> bms.pmm "Uses"
        markToPmm = mark -> bms.pmm "Uses"
        soToPofg = so -> bms.pofg "Uses"
        cmToPofg = cm -> bms.pofg "Uses"
        ccfToPofg = ccf -> bms.pofg "Uses"
        cfToPofg = cf -> bms.pofg "Uses"
        soToPpps = so -> bms.ppps "Uses"
        caToPpps = ca -> bms.ppps "Uses"
        cspXToPpps = cspX -> bms.ppps "Uses"
        feToPpps = fe -> bms.ppps "Uses"
        cmToPpps = cm -> bms.ppps "Uses"
        paasToPpps = paas -> bms.ppps "Uses"
        sciToPpps = sci -> bms.ppps "Uses"
        4creToPpps = 4cre -> bms.ppps "Uses"
        4stuToPpps = 4stu -> bms.ppps "Uses"
        markToPpps = mark -> bms.ppps "Uses"
        prodToPpps = prod -> bms.ppps "Uses"
        innoToPpps-p = inno -> bms.ppps-p "Uses"
        soToPpps-p = so -> bms.ppps-p "Uses"
        caToPpps-p = ca -> bms.ppps-p "Uses"
        cspXToPpps-p = cspX -> bms.ppps-p "Uses"
        factToPpps-p = fact -> bms.ppps-p "Uses"
        feToPpps-p = fe -> bms.ppps-p "Uses"
        cmToPpps-p = cm -> bms.ppps-p "Uses"
        ccfToPpps-p = ccf -> bms.ppps-p "Uses"
        4creToPpps-p = 4cre -> bms.ppps-p "Uses"
        markToPpps-p = mark -> bms.ppps-p "Uses"
        caToPpp = ca -> bms.ppp "Uses"
        comeToPpp = come -> bms.ppp "Uses"
        cspXToPpp = cspX -> bms.ppp "Uses"
        dafToPpp = daf -> bms.ppp "Uses"
        dramToPpp = dram -> bms.ppp "Uses"
        enteToPpp = ente -> bms.ppp "Uses"
        factToPpp = fact -> bms.ppp "Uses"
        feToPpp = fe -> bms.ppp "Uses"
        ncasToPpp = ncas -> bms.ppp "Uses"
        yadToPpp = yad -> bms.ppp "Uses"
        cmToPpp = cm -> bms.ppp "Uses"
        ccfToPpp = ccf -> bms.ppp "Uses"
        sciToPpp = sci -> bms.ppp "Uses"
        f4ToPpp = f4 -> bms.ppp "Uses"
        4creToPpp = 4cre -> bms.ppp "Uses"
        markToPpp = mark -> bms.ppp "Uses"
        prodXToPpp = prodX -> bms.ppp "Uses"
        soToPpc = so -> bms.ppc "Uses"
        caToPpc = ca -> bms.ppc "Uses"
        clacToPpc = clac -> bms.ppc "Uses"
        cspXToPpc = cspX -> bms.ppc "Uses"
        dafToPpc = daf -> bms.ppc "Uses"
        dramToPpc = dram -> bms.ppc "Uses"
        factToPpc = fact -> bms.ppc "Uses"
        feToPpc = fe -> bms.ppc "Uses"
        ncasToPpc = ncas -> bms.ppc "Uses"
        yadToPpc = yad -> bms.ppc "Uses"
        cmToPpc = cm -> bms.ppc "Uses"
        sciToPpc = sci -> bms.ppc "Uses"
        4creToPpc = 4cre -> bms.ppc "Uses"
        markToPpc = mark -> bms.ppc "Uses"
        piToPrta2 = pi -> bms.prta2 "Uses"
        ccfToPswo = ccf -> bms.pswo "Uses"
        cfToPswo = cf -> bms.pswo "Uses"
        cmToPsfv = cm -> bms.psfv "Uses"
        piToPsfv = pi -> bms.psfv "Uses"
        4stuToPsfv = 4stu -> bms.psfv "Uses"
        piToPtis = pi -> bms.ptis "Uses"
        commXToPvb = commX -> bms.pvb "Uses"
        clacToPvb = clac -> bms.pvb "Uses"
        cmToPvb = cm -> bms.pvb "Uses"
        ddToPvb = dd -> bms.pvb "Uses"
        piToPvb = pi -> bms.pvb "Uses"
        innoToPve = inno -> bms.pve "Uses"
        soToPve = so -> bms.pve "Uses"
        caToPve = ca -> bms.pve "Uses"
        cspXToPve = cspX -> bms.pve "Uses"
        feToPve = fe -> bms.pve "Uses"
        cmToPve = cm -> bms.pve "Uses"
        piToPve = pi -> bms.pve "Uses"
        sciToPve = sci -> bms.pve "Uses"
        markToPve = mark -> bms.pve "Uses"
        prodToPve = prod -> bms.pve "Uses"
        innoToPvmsv = inno -> bms.pvmsv "Uses"
        caToPvmsv = ca -> bms.pvmsv "Uses"
        cspXToPvmsv = cspX -> bms.pvmsv "Uses"
        cmToPvmsv = cm -> bms.pvmsv "Uses"
        piToPvma = pi -> bms.pvma "Uses"
        cfToSoun = cf -> bms.soun "Uses"
        paasToSsfatwswra = paas -> bms.ssfatwswra "Uses"
        piToTb = pi -> bms.tb "Uses"
        prodXToDist = prodX -> csp.dist "Uses"
        caToPasc = ca -> csp.pasc "Uses"
        pfToPasc = pf -> csp.pasc "Uses"
        cspXToPasc = cspX -> csp.pasc "Uses"
        ccfToPasc = ccf -> csp.pasc "Uses"
        soToPcf = so -> csp.pcf "Uses"
        caToPcf = ca -> csp.pcf "Uses"
        yadToPcf = yad -> csp.pcf "Uses"
        cmToPcf = cm -> csp.pcf "Uses"
        ccfToPcf = ccf -> csp.pcf "Uses"
        cfToPcf = cf -> csp.pcf "Uses"
        innoToPcc = inno -> csp.pcc "Uses"
        soToPcc = so -> csp.pcc "Uses"
        caToPcc = ca -> csp.pcc "Uses"
        comeToPcc = come -> csp.pcc "Uses"
        coToPcc = co -> csp.pcc "Uses"
        cspXToPcc = cspX -> csp.pcc "Uses"
        dafToPcc = daf -> csp.pcc "Uses"
        dramToPcc = dram -> csp.pcc "Uses"
        enteToPcc = ente -> csp.pcc "Uses"
        factToPcc = fact -> csp.pcc "Uses"
        feToPcc = fe -> csp.pcc "Uses"
        ncasToPcc = ncas -> csp.pcc "Uses"
        yadToPcc = yad -> csp.pcc "Uses"
        cmToPcc = cm -> csp.pcc "Uses"
        ccfToPcc = ccf -> csp.pcc "Uses"
        sciToPcc = sci -> csp.pcc "Uses"
        f4ToPcc = f4 -> csp.pcc "Uses"
        4creToPcc = 4cre -> csp.pcc "Uses"
        markToPcc = mark -> csp.pcc "Uses"
        prodXToPcc = prodX -> csp.pcc "Uses"
        innoToPp = inno -> csp.pp "Uses"
        soToPp = so -> csp.pp "Uses"
        caToPp = ca -> csp.pp "Uses"
        cspXToPp = cspX -> csp.pp "Uses"
        dafToPp = daf -> csp.pp "Uses"
        dramToPp = dram -> csp.pp "Uses"
        factToPp = fact -> csp.pp "Uses"
        feToPp = fe -> csp.pp "Uses"
        ncasToPp = ncas -> csp.pp "Uses"
        yadToPp = yad -> csp.pp "Uses"
        cmToPp = cm -> csp.pp "Uses"
        piToPp = pi -> csp.pp "Uses"
        ccfToPp = ccf -> csp.pp "Uses"
        f4ToPp = f4 -> csp.pp "Uses"
        commToPp = comm -> csp.pp "Uses"
        caToPpX = ca -> csp.ppX "Uses"
        cspXToPpX = cspX -> csp.ppX "Uses"
        dafToPpX = daf -> csp.ppX "Uses"
        piToPpX = pi -> csp.ppX "Uses"
        ccfToPpX = ccf -> csp.ppX "Uses"
        paaToAs = paa -> dap.as "Uses"
        soToBarb = so -> dap.barb "Uses"
        dsToBarb = ds -> dap.barb "Uses"
        cseToBor = cse -> dap.bor "Uses"
        partToBor = part -> dap.bor "Uses"
        soToBor = so -> dap.bor "Uses"
        tradToBor = trad -> dap.bor "Uses"
        arToCedw = ar -> dap.cedw "Uses"
        dsToCedw = ds -> dap.cedw "Uses"
        techToCedw = tech -> dap.cedw "Uses"
        arToC4 = ar -> dap.c4 "Uses"
        soToDcri = so -> dap.dcri "Uses"
        digiToDcrs = digi -> dap.dcrs "Uses"
        aiXToDcrs = aiX -> dap.dcrs "C4 Audience Team and Marketing team use the Data Clean Room solution for creating overlapping aud..."
        dmToDcrs = dm -> dap.dcrs "Uses"
        soToDf = so -> dap.df "Uses"
        atToDf = at -> dap.df "Uses"
        insiToTabl = insi -> dap.tabl "Uses"
        insiToWa = insi -> dap.wa "Uses"
        ccfToAtax = ccf -> fsp.atax "Uses"
        ccfToBbp = ccf -> fsp.bbp "Uses"
        c4ToBsw = c4 -> fsp.bsw "Raise and approve POs"
        ccfToBsw = ccf -> fsp.bsw "Uses"
        ccfrssToBsw = ccfrss -> fsp.bsw "Uses"
        ccfToEbs = ccf -> fsp.ebs "Uses"
        ccfrssToEbs = ccfrss -> fsp.ebs "Uses"
        c4ToFaf = c4 -> fsp.faf "Uses"
        ccfToMsc = ccf -> fsp.msc "Uses"
        ccfToSov = ccf -> fsp.sov "Uses"
        ccfToSbi = ccf -> fsp.sbi "Uses"
        ccfrssToSbi = ccfrss -> fsp.sbi "Uses"
        ccfrssToTgn = ccfrss -> fsp.tgn "Uses"
        ccfToWda = ccf -> fsp.wda "Uses"
        ddToLsp = dd -> lpp.lsp "Uses"
        piToLsp = pi -> lpp.lsp "Uses"
        btToLsp = bt -> lpp.lsp "Uses"
        btToSp = bt -> lpp.sp "Uses"
        dmToBraz = dm -> mp.braz "Uses"
        cpXToMpar = cpX -> mp.mpar "Uses"
        dmpToMpar = dmp -> mp.mpar "Uses"
        cspXToAwar = cspX -> mmp.awar "Uses"
        trafToMsp = traf -> mmp.msp "Uses"
        ccToMsp = cc -> mmp.msp "Uses"
        cmToMsp = cm -> mmp.msp "Uses"
        paasToMsp = paas -> mmp.msp "Uses"
        btToMsp = bt -> mmp.msp "Uses"
        4creToMsp = 4cre -> mmp.msp "Uses"
        prodXToMsp = prodX -> mmp.msp "Uses"
        clacToPpsp = clac -> mmp.ppsp "Uses"
        btToPpsp = bt -> mmp.ppsp "Uses"
        4creToPpsp = 4cre -> mmp.ppsp "Uses"
        c4To4peo = c4 -> psp.4peo "Uses"
        peopTo4peo = peop -> psp.4peo "Uses"
        c4ToActi = c4 -> psp.acti "Uses"
        peopToActi = peop -> psp.acti "Uses"
        corpToAc = corp -> psp.ac "Uses"
        c4ToBp = c4 -> psp.bp "Uses"
        erToBp = er -> psp.bp "Uses"
        ctToEr = ct -> psp.er "Uses"
        c4ToFes = c4 -> psp.fes "Uses"
        peopToFes = peop -> psp.fes "Uses"
        c4ToLl = c4 -> psp.ll "Uses"
        ladToLl = lad -> psp.ll "Uses"
        peopToPopp = peop -> psp.popp "Uses"
        c4ToTlh = c4 -> psp.tlh "Uses"
        soToPrms = so -> rmp.prms "Uses"
        caToPrms = ca -> rmp.prms "Uses"
        cspXToPrms = cspX -> rmp.prms "Uses"
        dramToPrms = dram -> rmp.prms "Uses"
        cmToPrms = cm -> rmp.prms "Uses"
        piToPrms = pi -> rmp.prms "Uses"
        ccfToPrms = ccf -> rmp.prms "Uses"
        4stuToPrms = 4stu -> rmp.prms "Uses"
        markToPrms = mark -> rmp.prms "Uses"
        caToRc = ca -> rmp.rc "Uses"
        partToCome = part -> rsp.come "Uses"
        caToCome = ca -> rsp.come "Uses"
        piToCome = pi -> rsp.come "Uses"
        ccfrssToCome = ccfrss -> rsp.come "Uses"
        caToEps = ca -> rsp.eps "Uses"
        caToNeo = ca -> rsp.neo "Uses"
        soToPap = so -> rsp.pap "Uses"
        caToPap = ca -> rsp.pap "Uses"
        ccfToPap = ccf -> rsp.pap "Uses"
        sciToPap = sci -> rsp.pap "Uses"
        caToPris = ca -> rsp.pris "Uses"
        piToPris = pi -> rsp.pris "Uses"
        ccfToPris = ccf -> rsp.pris "Uses"
        4stuToPris = 4stu -> rsp.pris "Uses"
        caToPrrs = ca -> rsp.prrs "Uses"
        ccfToPrrs = ccf -> rsp.prrs "Uses"
        caToSd = ca -> rsp.sd "Uses"
        4stuToTed = 4stu -> rsp.ted "Uses"
        cspXToPepl = cspX -> sp.pepl "Uses"
        yadToPepl = yad -> sp.pepl "Uses"
        cmToPepl = cm -> sp.pepl "Uses"
        piToPepl = pi -> sp.pepl "Uses"
        commToPepl = comm -> sp.pepl "Uses"
        clacToAnda = clac -> sbs.anda "Uses"
        piToAnda = pi -> sbs.anda "Clunky and difficult to use."
        procToCms = proc -> sbs.cms "Uses"
        clgToFa = clg -> sbs.fa "Uses"
        techToTime = tech -> sbs.time "Uses"
        viewToC4sl = view -> vsp.c4sl "Uses"
        a4eToPipe = a4e -> vsp.pipe "Uses"
        gsToSm = gs -> vsp.sm "Uses"
        techToSl = tech -> vsp.sl "Uses"
        piToTr = pi -> vsp.tr "Uses"
        cpXToThin = cpX -> vsp.thin "Uses"
        fmToCe = fm -> wsp.ce "Uses"
        c4ToEgen = c4 -> wsp.egen "Uses"
        ccfToEgen = ccf -> wsp.egen "Uses"

        /* ============================================================
           APPLICATION -> APPLICATION RELATIONSHIPS (from LeanIX Interfaces)
           ============================================================ */
        
        4ta = psp.4peo -> psp.acti "4People to ActivePay" "Mule" "Integration"
        4tac = psp.4peo -> wsp.ac "4People to Alert cascade" "Mule" "Integration"
        4tb = psp.4peo -> wsp.ac "4People to Benefits" "Mule" "Integration"
        4tce = psp.4peo -> wsp.ce "4People to Concept Evolution" "Mule" "Integration"
        4tcms = psp.4peo -> sbs.cms "4People to Contract Management System(CMS)" "Mule" "Integration"
        4tc = psp.4peo -> psp.tlh "4People to Cornerstone" "Mule" "Integration"
        4te = psp.4peo -> wsp.egen "4People to Egencia" "Mule" "Integration"
        4toe = psp.4peo -> fsp.ebs "4People to Oracle EBS" "Mule" "Integration"
        4tp = psp.4peo -> fsp.wda "4People to Planning" "Alternative" "Integration"
        4tpX = psp.4peo -> psp.popp "4People to Poppulo" "Mule" "Integration"
        atsfasdf = sp.pass -> cp.stel "A55 to Stellar for Advanced Schedule data flow" "SFTP" "Integration"
        aptf = psp.acti -> fsp.wda "Active Pay to Financial Planning" "Mule" "Integration"
        atoe = psp.acti -> fsp.ebs "ActivPay to Oracle EBS" "Mule" "Integration"
        asstc = vsp.yosp -> vsp.c4sl "Ad Serving System to C4S" "Alternative" "Integration"
        aate = dap.wa -> dap.cedw "Adobe Analytics to EDW" "Alternative" "Integration"
        apffpfb = cp.ap -> bms.pbm "Agency Portal fetch from Pirate for Brand" "Mule" "Integration"
        apffsfp = cp.ap -> cp.stel "Agency Portal fetch from Stellar for Programme" "Mule" "Integration"
        apfsfpyot = cp.ap -> cp.stel "Agency Portal from Stellar for Pick Your Own transmission" "Mule" "Integration"
        ai = csp.pcc -> rsp.prrs "Agreement Information" "Alternative" "Integration"
        ap = rsp.sd -> rsp.pap "Artist payments" "Automate" "Integration"
        adaa = bms.asp -> mmp.msp "ASP Delivery Acknowledgment API" "Alternative" "Integration"
        alsstl = lpp.lsp -> bms.asp "ASP live subtitle streams to LSP" "Alternative" "Integration"
        allsfl = bms.asp -> lpp.lsp "ASP low latency stream from LSP" "Alternative" "Integration"
        apja = bms.asp -> mmp.msp "ASP Production Job API" "Alternative" "Integration"
        apjsa = mmp.msp -> bms.asp "ASP Production Job Status API" "Alternative" "Integration"
        asfp = bms.asp -> bms.pira "ASP Schedule from Pirate" "Alternative" "Integration"
        assmfd = bms.asp -> mmp.msp "ASP Signer Source Media File Delivery" "Alternative" "Integration"
        avcmfd = bms.asp -> mmp.msp "ASP Viewing Copy Media File Delivery" "Alternative" "Integration"
        asaltf = cp.fsh -> dap.as "Audience Segments and Lookalikes to Freewheel" "Alternative" "Integration"
        bwpfo = fsp.ebs -> fsp.bbp "BACS & Wire Payments File Out" "Automate" "Integration"
        brdte = dap.barb -> dap.cedw "BARB ratings data to EDW" "SFTP" "Integration"
        btsfau = dap.barb -> cp.stel "BARB to Stellar for Audience Universe" "SFTP" "Integration"
        btsfi = dap.barb -> cp.stel "BARB to Stellar for Impacts" "SFTP" "Integration"
        bpsri = fsp.bbp -> fsp.ebs "Barclay Payment Statement Receipt In" "Automate" "Integration"
        bsi = fsp.bbp -> fsp.ebs "Barclay Statement In" "Automate" "Integration"
        bbdc = fsp.ebs -> fsp.bsw "Basware Business Department Codes" "Alternative" "Integration"
        bcer = fsp.ebs -> fsp.bsw "Basware Currency Exchange Rates" "Alternative" "Integration"
        bglcvr = fsp.ebs -> fsp.bsw "Basware GL Cross Validation Rules" "Alternative" "Integration"
        bglnc = fsp.ebs -> fsp.bsw "Basware GL Nominal Codes" "Alternative" "Integration"
        bic = fsp.ebs -> fsp.bsw "Basware Individual Codes" "Alternative" "Integration"
        bis = fsp.bsw -> fsp.ebs "Basware Invoice Statuses" "Alternative" "Integration"
        bpvpci = fsp.ebs -> fsp.bsw "Basware Payments/Void Payments/Cancelled Invoices" "Alternative" "Integration"
        bpcc = fsp.ebs -> fsp.bsw "Basware Pirate Code Combinations" "Alternative" "Integration"
        bprodc = fsp.ebs -> fsp.bsw "Basware Product Codes" "Alternative" "Integration"
        bprojc = fsp.ebs -> fsp.bsw "Basware Project Codes" "Alternative" "Integration"
        bws = fsp.ebs -> fsp.bsw "Basware Suppliers" "Alternative" "Integration"
        b2ebs = fsp.bsw -> fsp.ebs "Basware to EBS for Approved Invoices" "Automate" "Integration"
        b2sbi = fsp.bsw -> fsp.ebs "Basware to SplashBI (Oracle eBS Schema)" "Alternative" "Integration"
        b2sbi2 = fsp.bsw -> fsp.sbi "Basware to SplashBI (Oracle eBS Schema)" "Alternative" "Integration"
        bur = fsp.ebs -> fsp.bsw "Basware User Rights" "Alternative" "Integration"
        buriu = fsp.ebs -> fsp.bsw "Basware User Rights (Inactive users)" "Alternative" "Integration"
        bta = psp.acti -> psp.bp "Benefits to Actvipay" "Alternative" "Integration"
        bdte = cp.stel -> dap.cedw "Budget data to EDW" "Alternative" "Integration"
        btmii = sp.mod -> bms.bynd "Bynder to MediaGenix Image Integration" "Alternative" "Integration"
        btmitc = sp.mod -> bms.bynd "Bynder to MediaGenix Image Tagging Changes" "Alternative" "Integration"
        chptpr = psp.er -> dap.bor "C4 HR & Payroll to PowerBI Reporting" "Mule" "Integration"
        4io = fsp.ebs -> rsp.come "C4 intl overages" "SFTP" "Integration"
        cptyfa = vsp.yosp -> cp.stel "C4 Promo to YoSpace for Advertisements" "Mule" "Integration"
        4vatr = fsp.sov -> fsp.ebs "C4 VAT Returns" "Alternative" "Integration"
        cbsdte = vsp.sm -> dap.cedw "C4S Braintree Subscriber data to EDW" "Alternative" "Integration"
        cetf = vsp.free -> sp.pepl "C4S EPG to Freely" "Alternative" "Integration"
        cete = vsp.mpar -> dap.cedw "C4S Events to EDW" "Alternative" "Integration"
        cfvetba = vsp.ova -> vsp.free "C4S Freely Video Events to BitMovin Analytics" "Alternative" "Integration"
        cfvsfc = vsp.cdna -> vsp.free "C4S Freely Video Stream from CDN" "Alternative" "Integration"
        cmifc = vsp.cdna -> sp.mod "C4S MoD Images from CDN" "Alternative" "Integration"
        cqte = vsp.ova -> dap.cedw "C4S QoS to EDW" "Alternative" "Integration"
        csty = vsp.yosp -> bms.osp "C4S Streams to YoSpace" "Alternative" "Integration"
        ctaa = dap.wa -> vsp.c4sl "C4S to Adobe Analytics" "Alternative" "Integration"
        ctb = dap.barb -> vsp.c4sl "C4S to BARB" "Alternative" "Integration"
        ctc7t = vsp.c4sl -> bms.c7t "C4S to C4 7A Titles" "Alternative" "Integration"
        ctlvs = lpp.lsp -> vsp.c4sl "C4S to Licence Validation Service" "Alternative" "Integration"
        ctsma = vsp.sm -> vsp.c4sl "C4S to Subscription Management (Aptitude)" "Alternative" "Integration"
        ctt-ue = vsp.thin -> vsp.c4sl "C4S to ThinkAnalytics - User Events" "Alternative" "Integration"
        ctetaa = dap.wa -> vsp.mpar "C4S Tracking Events to Adobe Analytics" "Alternative" "Integration"
        ctetm = vsp.mpar -> vsp.c4sl "C4S Tracking Events to mParticle" "Alternative" "Integration"
        cvmtf = vsp.free -> sp.mod "C4S VoD Metadata to Freely" "Alternative" "Integration"
        c4st = mp.po -> mp.po "C4STELLARPROMO" "Alternative" "Integration"
        c4st2 = mp.po -> cp.stel "C4STELLARPROMO" "Alternative" "Integration"
        caapfsfd = cp.ap -> cp.stel "CARIA and Agency Portal from Stellar for Deals" "Mule" "Integration"
        cfsfcri = cp.cari -> cp.stel "CARIA from Stellar for Copy Rotation Instruction" "Mule" "Integration"
        ctsfcri = cp.cari -> cp.stel "CARIA to Stellar for Copy Rotation Instructions" "SFTP" "Integration"
        ctsfdacc = cp.cari -> cp.stel "CARIA to STELLAR for Deals and Campaign creation" "SFTP" "Integration"
        cro2c = fsp.ebs -> rsp.come "Cash Receipts from Oracle to Comet" "Alternative" "Integration"
        ctt = bms.pcgs -> bms.ptis "CGS to TIS2" "Alternative" "Integration"
        c4itr = mmp.msp -> mmp.pmm "Channel 4 Interstitals to RedBee" "Mule" "Integration"
        c4srtb = mp.braz -> vsp.c4sl "Channel 4 Streaming Recommendations to Braze" "Alternative" "Integration"
        c4tpt = mmp.msp -> bms.asp "Channel 4 to PFT token" "Mule" "Integration"
        crbtas = dap.as -> dap.dcri "Clean Room (Brandm4tch) to Audience Segmentation" "Alternative" "Integration"
        crbtas2 = dap.as -> dap.dcrs "Clean Room (Brandm4tch) to Audience Segmentation" "Alternative" "Integration"
        ctsfcci = cp.fsh -> cp.stel "Clearcast to Stellar for Copy Clearance Information" "Mule" "Integration"
        ctf = cp.fsh -> bms.cmt "CMT to Freewheel" "Alternative" "Integration"
        ctp = bms.pira -> bms.cmt "CMT to Pirate" "Mule" "Integration"
        ctpc = bms.cmt -> bms.pcX "CMT to Promo Create" "Alternative" "Integration"
        ctpo = mp.po -> bms.cmt "CMT to Promo Optimiser" "Alternative" "Integration"
        ccii = rsp.come -> fsp.ebs "Comet C4I Invoice Interface" "Alternative" "Integration"
        cffli = fsp.ebs -> rsp.come "Comet FFL Invoice Interface" "Automate" "Integration"
        cai = bms.pira -> rsp.pris "Contract & Agreement info" "Mule" "Integration"
        caiX = csp.pcc -> rsp.pap "Contract/Prog & Agreement info" "Alternative" "Integration"
        cpdta = bms.pira -> sbs.anda "Contracts PAC data to Anda" "Alternative" "Integration"
        cctf = cp.cc -> cp.fsh "Copy Central to Freewheel" "Alternative" "Integration"
        ccts = cp.cc -> cp.stel "Copy Central to Stellar" "Alternative" "Integration"
        ctll = psp.tlh -> psp.ll "Cornerstone to LinkedIn Learning" "Alternative" "Integration"
        epct = psp.fes -> fsp.ebs "EBS project codes to FES" "Alternative" "Integration"
        et4f = psp.4peo -> fsp.ebs "EBS to 4People for Employees" "Alternative" "Integration"
        ebstrd = fsp.ebs -> fsp.bsw "EBS to Basware for Reference & Transactional data" "Alternative" "Integration"
        etcf = rsp.come -> fsp.ebs "EBS to Comet for Cash Receipts" "SFTP" "Integration"
        ebsmc = fsp.msc -> fsp.ebs "EBS to Mastercard for Employee credit card transactions" "Alternative" "Integration"
        ebspir = fsp.ebs -> rsp.come "EBS to Pirate (Comet Flim4)" "Automate, SFTP" "Integration"
        ebsstr = fsp.ebs -> cp.stel "EBS to Stellar Daily exchange rate (in) Invoices (out)" "Alternative" "Integration"
        ebscex = fsp.ebs -> cp.stel "EBS to Stellar for Currency Exchange" "SFTP" "Integration"
        ebplan = fsp.ebs -> fsp.wda "eBusiness to Planning" "Alternative" "Integration"
        e4ti = dap.dcri -> dap.cedw "EDW 4 to Infosum" "Alternative" "Integration"
        emcstmdf = dap.df -> dap.cedw "EDW Marketing Campaign Snapshots to Microsoft Data Fabric" "Alternative" "Integration"
        emctmdf = dap.df -> dap.cedw "EDW Marketing Campaign to Microsoft Data Fabric" "Alternative" "Integration"
        esitb = mp.braz -> dap.cedw "EDW Streaming Identity to Braze" "Alternative" "Integration"
        etdf-sd = dap.df -> dap.cedw "EDW to  Data Fabric - Spots data" "Alternative" "Integration"
        etapsp = dap.cedw -> rsp.pap "EDW to Artist Payment Systems (Pirate)" "Alternative" "Integration"
        etb = mp.braz -> dap.cedw "EDW to Braze" "Alternative" "Integration"
        etm-ipcau = dap.cedw -> dap.as "EDW to Mediarithmics - Instream Promo Control Audience Upload" "Alternative" "Integration"
        etm-sud = dap.as -> dap.cedw "EDW to Mediarithmics - Streaming User Data" "Alternative" "Integration"
        ett-v = vsp.thin -> dap.cedw "EDW to ThinkAnalytics - Viewers" "Alternative" "Integration"
        etdftp = dap.cedw -> bms.pira "EDW TX data feed to Pirate" "Alternative" "Integration"
        fgl = bms.pira -> fsp.ebs "Failed GL lines" "Alternative" "Integration"
        fvte = cp.fsh -> dap.cedw "Feewheel v4logs to EDW" "Alternative" "Integration"
        faebs = fsp.ebs -> fsp.faf "Finance Approval to E-Business Suite" "Alternative" "Integration"
        ffsffdovc = cp.fsh -> dap.cedw "Freewheel from Stellar for Forecast data of VOD Campaign" "Mule" "Integration"
        ffsffdovc2 = cp.fsh -> cp.stel "Freewheel from Stellar for Forecast data of VOD Campaign" "Mule" "Integration"
        fltmdf = cp.fsh -> dap.df "Freewheel logs to Microsoft Data Fabric" "Alternative" "Integration"
        ftiecua = dap.dcri -> cp.fsh "Freewheel to Infosum (Exposed Campaign Users Attribution)" "Alternative" "Integration"
        ftsffrdca = cp.fsh -> cp.stel "Freewheel to Stellar for Freewheel reference data changes API" "Alternative" "Integration"
        ftsvvfcsap = cp.fsh -> cp.stel "Freewheel to Stellar VoD Views for Commercial, Sponsorship and Promotions" "SFTP" "Integration"
        frtpa = mmp.msp -> bms.prta2 "From RedBee to Pirate ASRUN" "Mule" "Integration"
        fstpfcr = cp.stel -> bms.pira "From Stellar to Pirate for Commercial Registrations" "Alternative" "Integration"
        idtc = bms.bynd -> vsp.c4sl "Image DAM to C4S" "Alternative" "Integration"
        imcfstp = rsp.soun -> bms.pira "Interstial music cuesheets from Soundmouse to Pirate" "Automate, SFTP" "Integration"
        icnf = rsp.pris -> fsp.ebs "Invoice/credit note for Royalties" "Automate" "Integration"
        lspp = bms.pira -> vsp.c4sl "Logging Sheets & Programme Parts" "Alternative" "Integration"
        lcflr = lpp.lsp -> mmp.ppsp "LSP Contribution Feed ( Line Record)" "Alternative" "Integration"
        lmfd = lpp.lsp -> mmp.msp "LSP Media File Delivery" "Alternative" "Integration"
        lm = lpp.lsp -> bms.osp "LSP Multicast" "Alternative" "Integration"
        lsto = bms.osp -> lpp.lsp "LSP Simulcast to OSLP" "Alternative" "Integration"
        ltpa = bms.pira -> lpp.lsp "LSP to Pirate Asruns" "Alternative" "Integration"
        mtbb = bms.bynd -> sp.mod "MediaGenix to Bynder Brand" "Alternative" "Integration"
        mtfpi = cp.fsh -> sp.mod "MediaGenix to FreeWheel Programme Info" "Alternative" "Integration"
        mtgc4vc = bms.grac -> sp.mod "MediaGenix to Gracenote Channel 4 VoD Catalogue" "Mule" "Integration"
        mtmbvsi = sp.mod -> sp.mod "MediaGenix to MediaGenix BARB VOD Schedule Integration" "Alternative" "Integration"
        mtpecw = bms.pira -> sp.mod "MediaGenix to Pirate EPG Content Warnings" "Mule" "Integration"
        mttc4vc = vsp.thin -> sp.mod "MediaGenix to ThinkAnalytics Channel 4 VoD Catalogue" "Mule" "Integration"
        mtbfms = mp.braz -> dap.as "Mediarithmics to Braze for Marketing Segments" "Alternative" "Integration"
        mtffas = cp.fsh -> dap.as "Mediarithmics to Freewheel for ALA segments" "Alternative" "Integration"
        mticga = dap.dcri -> dap.as "Mediarithmics to Infosum (Control Group attribution)" "Alternative" "Integration"
        mvrtp = mmp.msp -> sp.mod "MoD  VoD Request to PFT" "Alternative" "Integration"
        msdte = vsp.sm -> dap.cedw "MPP Subscriber data to EDW" "Alternative" "Integration"
        mcra = mmp.msp -> bms.asp "MSP Content Request API" "Alternative" "Integration"
        mcra2 = mmp.msp -> lpp.lsp "MSP Content Request API" "Alternative" "Integration"
        mcra3 = mmp.msp -> bms.osp "MSP Content Request API" "Alternative" "Integration"
        mcra4 = mmp.msp -> mmp.ppsp "MSP Content Request API" "Alternative" "Integration"
        mmvfto = mmp.msp -> bms.osp "MSP Master Video Files to OLSP" "Alternative" "Integration"
        mmfd-abs = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired BBC Studios" "Alternative" "Integration"
        mmfd-af = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired Fox/Disney" "Alternative" "Integration"
        mmfd-ag = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired Generic" "Alternative" "Integration"
        mmfd-as = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired Sony" "Alternative" "Integration"
        mmfd-at = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired Turner" "Alternative" "Integration"
        mmfd-aw = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired Warner" "Alternative" "Integration"
        mmfd-c = mmp.msp -> cp.cari "MSP Media File Delivery - Commercials" "Alternative" "Integration"
        mmfd-c2 = mmp.msp -> cp.cc "MSP Media File Delivery - Commercials" "Alternative" "Integration"
        mmfd-cp = mmp.msp -> csp.pc "MSP Media File Delivery - Commissioned Programmes" "Alternative" "Integration"
        mmfd-i = mmp.msp -> csp.pc "MSP Media File Delivery - Interstitials" "Alternative" "Integration"
        mmfd-lvr = mmp.msp -> lpp.lsp "MSP Media File Delivery - LSP Video Recordings" "Alternative" "Integration"
        mmfd-lvrX = mmp.msp -> lpp.lsp "MSP Media File Delivery - LSP Voiceover Recordings" "Alternative" "Integration"
        mmfd-mmtsflft = mmp.msp -> cp.stel "MSP Media File Delivery - MB Media to Stellar for Long Form teleshopping" "SFTP" "Integration"
        mmfd-mv = mmp.msp -> cp.cari "MSP Media File Delivery - Music Videos" "Alternative" "Integration"
        mmfd-sad = mmp.msp -> bms.asp "MSP Media File Delivery - Subtitles & Audio Description" "Alternative" "Integration"
        mmfd-s = mmp.msp -> bms.asp "MSP Media File Delivery - Supertrusted" "Alternative" "Integration"
        mmfd-s2 = mmp.msp -> mmp.ppsp "MSP Media File Delivery - Supertrusted" "Alternative" "Integration"
        mpvba = mmp.msp -> mmp.pvb "MSP Pirate Video Browse API" "Alternative" "Integration"
        mpvbfh = mmp.msp -> mmp.pvb "MSP Pirate Video Browse File Hosting" "Alternative" "Integration"
        msfr = mmp.msp -> bms.pira "MSP Schedule File Receipt" "Alternative" "Integration"
        mti = mmp.msp -> mmp.uv "MSP Tape Ingest" "Alternative" "Integration"
        mtp = mmp.pmm -> mmp.msp "MSP to Pirate" "Mule" "Integration"
        mtrta = mmp.rta -> mmp.msp "MSP to Ready to Air" "Alternative" "Integration"
        mts = rsp.soun -> mmp.msp "MSP to Soundmouse" "Alternative" "Integration"
        mtc4df = mmp.msp -> bms.pira "MSPs to Channel 4 DFS folders" "Mule" "Integration"
        nos = bms.pc -> rsp.prrs "Name of Supplier" "Alternative" "Integration"
        ntn = rsp.pris -> bms.pira "New transmitted notifications" "Alternative" "Integration"
        oscn = fsp.ebs -> rsp.prrs "Oracle suppliers contact names" "Alternative" "Integration"
        oatax = fsp.ebs -> fsp.atax "Oracle to AlphaTax" "Alternative" "Integration"
        otunx = fsp.ebs -> fsp.tgn "Oracle to Tungsten XML Invoice feed" "Mule" "Integration"
        pfpfstp = rsp.soun -> bms.pira "PAC form PDFs from Soundmouse to Pirate" "Automate, SFTP" "Integration"
        pfxfstp = rsp.soun -> bms.pira "PAC form XMLs from Soundmouse to Pirate" "Automate, SFTP" "Integration"
        pmfsfaf = mmp.msp -> cp.stel "Peach Media from Stellar for Attribution files" "Mule" "Integration"
        patveo = bms.pira -> sp.pass "Pirate A55 to VMS (ex Optimum)" "Mule" "Integration"
        patveo2 = bms.pira -> sp.pepl "Pirate A55 to VMS (ex Optimum)" "Mule" "Integration"
        patveo3 = bms.pira -> bms.pvmsv "Pirate A55 to VMS (ex Optimum)" "Mule" "Integration"
        passtc = bms.pira -> vsp.c4sl "Pirate Advance Scheduling System to C4S" "Alternative" "Integration"
        pctc = bms.pira -> vsp.c4sl "Pirate Certification to C4S" "Alternative" "Integration"
        pctb = bms.bynd -> bms.pcgs "Pirate CGS to Bynder" "Mule" "Integration"
        pctf = cp.fsh -> bms.pcgs "Pirate CGS to Freewheel" "Mule" "Integration"
        pctmfvo = mmp.msp -> bms.pcgs "Pirate CGS to MSP for VPS origin" "Mule" "Integration"
        pctsfpapi = bms.pcgs -> cp.stel "Pirate CGS to Stellar for Programme and Platform information" "Alternative" "Integration"
        pctfX = cp.fsh -> bms.pcgs "Pirate Creatives to Freewheel" "Mule" "Integration"
        pffrfs = bms.pira -> bms.asp "Pirate fetch from RedBee for Subtitles" "Mule" "Integration"
        pirgl = fsp.ebs -> rsp.come "Pirate GL posted Transactions" "Alternative" "Integration"
        pptasb = mmp.msp -> sp.ppps "Pirate PPS to AWS S3 Bucket" "Mule" "Integration"
        ppitf = cp.fsh -> bms.pcgs "Pirate Programme Info to FreeWheel" "Mule" "Integration"
        prmstc = bms.pira -> vsp.c4sl "Pirate Rights Management System to C4S" "Alternative" "Integration"
        prdtoe = rmp.prms -> dap.cedw "PIRATE RMS data to  Oracle EDW" "Alternative" "Integration"
        pta = lpp.ac -> sp.mod "Pirate To Amagi" "Alternative" "Integration"
        ptbfca = sp.mod -> bms.pira "Pirate to BeBanjo for Catalogue Assets" "Mule" "Integration"
        ptbfca2 = sp.mod -> csp.pp "Pirate to BeBanjo for Catalogue Assets" "Mule" "Integration"
        ptbfls = sp.mod -> bms.pira "Pirate to BeBanjo for Linear Scheduling" "Mule" "Integration"
        ptbfls2 = sp.mod -> sp.pass "Pirate to BeBanjo for Linear Scheduling" "Mule" "Integration"
        ptbfma = sp.mod -> bms.pira "Pirate to BeBanjo for Media Assets" "Mule" "Integration"
        ptbfma2 = sp.mod -> mmp.pmm "Pirate to BeBanjo for Media Assets" "Mule" "Integration"
        ptbfr = sp.mod -> rmp.prms "Pirate to BeBanjo for Rights" "Mule" "Integration"
        ptbfs = sp.mod -> bms.pira "Pirate to BeBanjo for Segment" "Mule" "Integration"
        ptbdf = mmp.pmm -> bms.bynd "Pirate to Bynder data flow" "Alternative" "Integration"
        ptcpft = mmp.msp -> mmp.pvb "Pirate to Clear (Prime Focus Technology)" "Mule" "Integration"
        ptcs = bms.pira -> mmp.msp "Pirate to Compliance Service" "Alternative" "Integration"
        ptdfvp = bms.et -> bms.pira "Pirate to DUK Freesat VOD publication" "Alternative" "Integration"
        ptdfvpX = bms.et -> bms.pira "Pirate to DUK Freeview VOD publication" "Alternative" "Integration"
        pte = bms.pira -> fsp.ebs "Pirate to EBS" "Alternative" "Integration"
        ptes = bms.pira -> mmp.msp "Pirate to Editorial Service" "Alternative" "Integration"
        ptgc4ce = bms.pira -> bms.grac "Pirate to Gracenote Channel 4 channel EPGs" "Mule" "Integration"
        ptgmce = bms.pira -> bms.grac "Pirate to Gracenote music channel EPGs" "Alternative" "Integration"
        ptk = sp.ppps -> dap.barb "Pirate to Kantar" "Mule" "Integration"
        ptkfa = dap.barb -> mmp.pmm "Pirate to Kantar for Assets" "Mule" "Integration"
        ptl = lpp.lsp -> bms.pira "Pirate To LSP" "Alternative" "Integration"
        ptl2 = lpp.lsp -> cp.stel "Pirate To LSP" "Alternative" "Integration"
        ptmocm = sp.mod -> bms.pira "Pirate to MediaGenix On-Demand Content Metadata" "Mule" "Integration"
        ptmocm2 = sp.mod -> sp.pepl "Pirate to MediaGenix On-Demand Content Metadata" "Mule" "Integration"
        ptpo = sp.ppps -> mp.po "Pirate To Promo Optimser" "Mule" "Integration"
        ptss = lpp.lsp -> sp.ppps "Pirate to Schedule Service" "Alternative" "Integration"
        pts = bms.pira -> cp.stel "Pirate to Stellar" "Alternative" "Integration"
        ptsfac = sp.pitts -> cp.stel "Pirate to Stellar for ASRUN commercial" "Automate, SFTP" "Integration"
        ptsfan = sp.ppps -> cp.stel "Pirate to Stellar for ASRUN Non-commercial" "Alternative" "Integration"
        ptsfset = sp.ppps -> cp.stel "Pirate to Stellar for Schedule & Event timings" "Alternative" "Integration"
        ptsufb = cp.stel -> cp.ap "Pirate to Stellar update for Brand" "Mule" "Integration"
        pvtrmpn = mmp.msp -> bms.ptis "Pirate VPS to (RedBee, M2A, PFT, NLDR)" "Mule" "Integration"
        pvts = mmp.msp -> mmp.pmm "Pirate VPS to S3" "Mule" "Integration"
        pwfts = bms.pira -> cp.stel "Pirate Weekly Forecast to Stellar" "Automate" "Integration"
        pvtcrps = rsp.prrs -> rmp.prms "Portal view to capture Royalty Producer shares" "Alternative" "Integration"
        pdfpts = rsp.soun -> bms.pira "Post-TX data from Pirate to Soundmouse" "Automate, SFTP" "Integration"
        pcf = mmp.ppsp -> lpp.lsp "PPSP Contribution Feed" "Alternative" "Integration"
        pmfd = mmp.ppsp -> mmp.msp "PPSP Media File Delivery" "Alternative" "Integration"
        pdfptsX = rsp.soun -> bms.pira "Pre-TX data from Pirate to Soundmouse" "Automate, SFTP" "Integration"
        plcdiabas = cp.stel -> dap.cedw "Processes linear campaign data, including agreements, breaks and spots" "Alternative" "Integration"
        prte = rsp.come -> fsp.ebs "Producer Reporting to EBS" "Automate" "Integration"
        proebs = fsp.ebs -> rsp.come "Producer Reporting to Oracle eBusiness Suite " "Alternative" "Integration"
        pptpfesdi = bms.ppp -> csp.pcc "Producers Portal to Pirate for Ed Spec Diversity info" "Mule" "Integration"
        pasmcmcfstp = rsp.soun -> bms.pira "Programme and social media clip music cuesheets from Soundmouse to Pirate" "Automate, SFTP" "Integration"
        ppi = fsp.ebs -> bms.pira "programme Payments Interface" "Alternative" "Integration"
        pctm = sp.mod -> bms.pcX "Promo Create To Movida" "Mule" "Integration"
        pctp = bms.pira -> bms.pcX "Promo Create To Pirate" "Mule" "Integration"
        potp = bms.pira -> mp.po "Promo Optimiser to Pirate" "Mule" "Integration"
        rtata4 = lpp.lsp -> vsp.c4sl "Real Time As-Run to ALL 4" "Alternative" "Integration"
        rdfpfcf = bms.pira -> rsp.pris "Recoupment/Advances data from Programme Finance Committee form" "Alternative" "Integration"
        rad = csp.pcc -> rsp.pap "Repeat agreement data" "Alternative" "Integration"
        rtc7t = rmp.prms -> bms.c7t "Rights to C4 7A Titles" "Alternative" "Integration"
        rswe = bms.pc -> rsp.prrs "Royalty Statement (welcome Email)" "Alternative" "Integration"
        scfmd = fsp.ebs -> cp.sc "Sales CRM to Finance ERP - Customer Master Data" "Mule" "Integration"
        scfic = fsp.ebs -> cp.sc "Sales CRM to Finance ERP - Invoice Creation" "Mule" "Integration"
        se = rsp.come -> rsp.pap "Sales Entry" "Alternative" "Integration"
        str = lpp.lsp -> bms.pira "SSAPI to RTAR" "Mule" "Integration"
        sdfp = rsp.prrs -> fsp.bsw "Statement data (for pre-approved PO's)" "Alternative" "Integration"
        scdta = cp.ap -> cp.stel "Stellar commercial data to Agencies" "Mule" "Integration"
        stapkfpd = cp.ap -> cp.stel "Stellar to Agency Portal &  K2 for programme data" "Mule" "Integration"
        stapfcap = cp.ap -> cp.stel "Stellar to Agency Portal for CB and PIB" "Alternative" "Integration"
        strebs = fsp.ebs -> cp.stel "Stellar to EBS for Sales Orders & New Customers" "Alternative" "Integration"
        ste-cpadpagl = cp.stel -> dap.cedw "STELLAR to EDW - Campaign Position and Deal Position at Group Level" "Alternative" "Integration"
        ste-dtbuipcr = cp.stel -> dap.cedw "STELLAR to EDW - Data to be used in PIB & CB reporting" "Alternative" "Integration"
        ste-pbpgd = cp.stel -> dap.cedw "STELLAR to EDW - Processes Base Price Group data" "Alternative" "Integration"
        ste-rsrvpt = cp.stel -> dap.cedw "STELLAR to EDW - ROI Sponsorship Revenue values per transmission" "Alternative" "Integration"
        ste-scd = cp.stel -> dap.cedw "STELLAR to EDW - Sponsorship campaign data" "Alternative" "Integration"
        stefrcocs = cp.stel -> dap.cedw "Stellar to EDW for ROI calculation on Channel sets" "Alternative" "Integration"
        stffabdac = cp.fsh -> cp.stel "Stellar to Freewheel for Agencies, Brand, Deals and Campaigns" "Mule" "Integration"
        stnabfptsl = dap.barb -> cp.stel "Stellar to NIELSEN and BARB for post transmission Spot Log" "SFTP" "Integration"
        stof2 = cp.stel -> fsp.ebs "Stellar to Oracle Financials about Agency financial exposure" "Alternative" "Integration"
        stof1 = cp.stel -> fsp.ebs "Stellar to Oracle Financials on Credit Policy" "Alternative" "Integration"
        stof = cp.stel -> fsp.ebs "Stellar to Oracle Financials on invoicing" "Alternative" "Integration"
        stpmfspf = mmp.msp -> cp.stel "Stellar to Peach Media for Spot Plus files" "Mule" "Integration"
        stpfcbpi = sp.ppps -> cp.stel "Stellar to Pirate for Commercial break pattern information" "Alternative" "Integration"
        stpfccr = cp.stel -> sp.ppps "Stellar to Pirate for Commercial Copy Registrations" "SFTP" "Integration"
        stpfcp = sp.pitts -> cp.stel "Stellar to Pirate for commercial playlist" "SFTP" "Integration"
        stpfppi = cp.stel -> sp.ppps "Stellar to Pirate for Product placement indicator" "Alternative" "Integration"
        stpfpc = cp.stel -> sp.ppps "Stellar to Pirate for Promotional Campaigns" "Alternative" "Integration"
        stpfpcr = cp.stel -> sp.ppps "Stellar to Pirate for Promotions Copy Registrations" "Alternative" "Integration"
        stpfsc = cp.stel -> sp.ppps "Stellar to Pirate for Sponsorship Campaign" "Alternative" "Integration"
        stpfscoc = cp.stel -> sp.ppps "Stellar to Pirate for Sponsorship Clocknumbers or Copy" "Alternative" "Integration"
        stpfse = cp.stel -> sp.ppps "Stellar to Pirate for Sponsorship Events" "Alternative" "Integration"
        stpfsefp = cp.stel -> sp.ppps "Stellar to Pirate for Sponsorship Events for Partners" "SFTP" "Integration"
        stpftp = cp.stel -> sp.ppps "Stellar to Pirate for Trail patterns" "Alternative" "Integration"
        stufac = mmp.msp -> cp.stel "Stellar to UKTV for Ad Certification" "SFTP" "Integration"
        stufccr = mmp.msp -> cp.stel "Stellar to UKTV for Commercial Copy Registrations" "SFTP" "Integration"
        scte = vsp.c4sl -> dap.cedw "Streaming Consent to EDW" "Alternative" "Integration"
        sbde = fsp.ebs -> rsp.pap "Supplier Bank Details Exist" "Automate" "Integration"
        sffptee = rsp.prrs -> dap.cedw "Supplier fields from PIRATE to EDW(Redshift) EDW(Oracle)" "Alternative" "Integration"
        supinf = fsp.ebs -> rsp.pris "Supplier Information" "Alternative" "Integration"
        suprec = fsp.ebs -> rsp.pap "Supplier Records" "Alternative" "Integration"
        ttbstcr = rsp.ted -> dap.cedw "Ted tables batch synchronisation to Coeus Redshift" "Alternative" "Integration"
        ttn = rsp.soun -> bms.pira "Ted to Neo" "Automate, SFTP" "Integration"
        tts = rsp.soun -> bms.pira "Ted to Silvermouse" "Automate, SFTP" "Integration"
        ttc-r = vsp.thin -> vsp.c4sl "ThinkAnalytics to C4S - Recommendation" "Alternative" "Integration"
        tsfptb = dap.barb -> sp.pass "TX Schedule from PIRATE to BARB" "Alternative" "Integration"
        vptc = bms.osp -> vsp.c4sl "Video Pipeline to C4S" "Alternative" "Integration"
        vtcs = mmp.msp -> bms.ppc "VisionCloud to Compliance Service" "Mule" "Integration"
        vvd = dap.cedw -> rsp.prrs "VOD Views Data" "Alternative" "Integration"
        waadte = dap.wa -> dap.cedw "Web Analytics (AA) data to EDW" "Alternative" "Integration"
        wdsbi = fsp.wda -> fsp.ebs "Workday Adaptive to SplashBI (Oracle eBS Schema)" "Mule" "Integration"
        wdsbi2 = fsp.wda -> fsp.sbi "Workday Adaptive to SplashBI (Oracle eBS Schema)" "Mule" "Integration"
        ytf = vsp.yosp -> cp.fsh "YoSpace to Freewheel" "Alternative" "Integration"
        
    }
    
    views {
        
        terminology {
            person "Team"
            softwareSystem "Platform"
            container "Application"
        }
        
        themes https://raw.githubusercontent.com/synchrotron/c4c4/main/assets/c4-default-theme.json
        
        branding {
            logo https://raw.githubusercontent.com/synchrotron/c4c4/main/assets/4-logo-black.png
            font "4Text" https://raw.githubusercontent.com/synchrotron/c4c4/main/assets/4Text-Regular.ttf
        }
    }
}