workspace "Channel 4 Core" "Enterprise Systems - Generated from LeanIX" {

    !identifiers hierarchical

    model {
    
        archetypes {
            application = container
        }
        
        /* ============================================================
           ORGANISATIONS / TEAMS (from LeanIX UserGroups)
           ============================================================ */
        
        c4cc = person "Client Sales & Engagement" ""
        c4ci = person "Partnerships" ""
        c4cs = person "Sales Operations" "Sales Operations handle the content supply chain for commercial content and plan placements withi..."
        ea = person "Agency" ""
        c4ct = person "Broadcast Technology" ""
        c4ca = person "AV" ""
        c4csX = person "Ad Tech" ""
        c4csXX = person "Campaign" ""
        c4csXXX = person "Traffic" ""
        c4ctX = person "Trading" ""
        c4ccX = person "Presentation and Access Services" ""
        c4cf = person "Content Finance" ""
        c4mc = person "Communications" ""
        c4mm = person "Audience Integration" ""
        c4caX = person "Corporate Legal and Compliance" "Sub-team of Commercial Affairs that handle legal and compliance for all our content. Assigning ce..."
        c4ccXX = person "Content Delivery" ""
        c4m4 = person "4Studio" ""
        c4mp = person "Product" ""
        epp = person "Partner Platform" "User group to describe partner platforms such as DUK, Youview or Sky"
        c4ccXXX = person "Programme Information" "Programme Information provide distinctive, top quality, informative copy with the relevant tone o..."
        c4ccXXXX = person "Commissioning Office" ""
        ep = person "Producer" ""
        c4caXX = person "Commercial Affairs" "The commercial affairs teams handle entitlements and agreements, including rights) with out conte..."
        c4ccXXXXX = person "Content Strategy & Planning" "The Content Strategy team plans exhibition windows for our content on linear and non-linear using..."
        c4ccXXXXXX = person "Youth and Digital" ""
        c4ccXXXXXXX = person "Content Management" "Technical and business team that handle content media supply chain."
        ccf = person "Finance" ""
        c4csXXXX = person "Strategy & Consumer Insight" ""
        c4mmX = person "Marketing" ""
        c4ciX = person "Innovation" ""
        c4ccXXXXXXXX = person "Daytime and Features" ""
        c4ccXXXXXXXXX = person "Drama" ""
        c4ccXXXXXXXXXX = person "Factual" ""
        c4ccXXXXXXXXXXX = person "Factual Entertainment" ""
        c4ccXXXXXXXXXXXX = person "News, Current Affairs & Sport" ""
        c4f4 = person "Film 4" ""
        c4caXXX = person "Business Affairs" ""
        c4ccXXXXXXXXXXXXX = person "Comedy" ""
        c4ccXXXXXXXXXXXXXX = person "Commissioning Operations" ""
        c4ccXXXXXXXXXXXXXXX = person "Entertainment" ""
        c4ccXXXXXXXXXXXXXXXX = person "Duty Desk" "Team that handles live content operations for our linear channels."
        c4cp = person "People" ""
        c4m = person "MVE" ""
        c4m4X = person "4Creative" "Creative Team that creates new content for Channel 4."
        c4c = person "Commercial" ""
        c4caXXXX = person "Production Finance" ""
        c4csXXXXX = person "Programmatic and Audience" ""
        c4csXXXXXX = person "Data Science" ""
        c4csXXXXXXX = person "Audience Research" ""
        c4ctXX = person "Technology" ""
        c4ciXX = person "Digital" ""
        c4mmXX = person "Digital Marketing" ""
        c4mpX = person "Insights" ""
        c4 = person "Channel 4" ""
        ccfrss = person "Shared Services" "Team responsible for any financial transactional incoming and outgoing payment processing. Typica..."
        c4mpXX = person "Consumer Product" ""
        c4mpXXX = person "Digital Marketing (Product)" ""
        c4ccXXXXXXXXXXXXXXXXX = person "Content & Commissioning" ""
        c4cX = person "Corporate" ""
        c4cpX = person "Employee Relations" ""
        c4ctXXX = person "Corporate Technology" ""
        c4cpXX = person "Learning and Development" ""
        c4cfX = person "Procurement" ""
        c4caXXXXX = person "Corporate Legal & Governance" ""
        ev = person "Viewer" ""
        c4mpXXXX = person "All 4 Editorial" ""
        c4mpXXXXX = person "Growth (Subscriptions)" ""
        c4cfXX = person "Facilities Management" ""

        /* ============================================================
           COMMERCIAL PLATFORM
           ============================================================ */
        
        cp = softwareSystem "Commercial Platform" "Platform from LeanIX" {
            
            ap = container "Agency Portal" "Empowering advertising agencies with their Channel4 campaign data." "paas"
            cari = container "Caria" "The platform on which UK & Irish airtime is traded, and upon which copy rotation instructions are..." "saas"
            cc = container "Copy Central" "Service that provides information about copy restrictions and/or certifications. Also known as Cl..." ""
            fsh = container "Freewheel Streaming Hub" "Freewheel Streaming Hub (aka MRM) is a software application that enables publishers and broadcast..." "saas"
            inno = container "Innovid" "Innovid is the only independent omni-channel advertising and analytics platform built for televis..." "saas"
            moat = container "Moat" "Moat enables measuring consumer attention across channels, devices, and platforms" "saas"
            sc = container "Sales CRM" "" ""
            stel = container "Stellar" "Channel4's Sales Order Processing System" "onPremise"
        }

        /* ============================================================
           CONTENT MANAGEMENT PLATFORM
           ============================================================ */
        
        bms = softwareSystem "Content Management Platform" "The applications and components that support the media management and linear scheduling for our l..." {
            
            asp = container "Access Service Provider" "" ""
            acf = container "Acquired Cash Forecast" "For the management of cashflow for acquired content, this is all captured on a spreadsheet called..." "desktopOrLaptop"
            bynd = container "Bynder" "Bynder is an AI-powered, SaaS DAM solution that allows brands to easily create, find and use thei..." "saas"
            c7t = container "C4 7A Titles" "Home grown system to schedule long form content on YouTube with workflow for Rights and Compliance." "saas"
            cmt = container "CMT" "Hosted by I2, CMT is a web-based tool with secure log-in credentials . The tool allows Long Term ..." "saas"
            dasd = container "DTT Audio & Signing Date prompts with peak stats (with RB amendments)" "Business Objects report Displays the total volume of transmitted content during a time period, an..." ""
            et = container "Everyone TV" "Everyone TV is the new name for Digital UK. [JV with UK PSB's] NOTE: This is NOT an Application E..." ""
            grac = container "Gracenote" "Gracenote is the world’s leading entertainment data and technology company. We power the top musi..." "saas"
            mod = container "MediaGenix On Demand" "BeBanjo Movida VOD Management system (Comprising of systems which schedule and manage transcode a..." "saas"
            olss = container "OFCOM Licensing Services-Online Services-MIDCOM" "This is the OFCOM platform used by our Access Services team to upload of our reporting to OFCOM." ""
            osp = container "OnLine Service Provider" "Provides capabilities for ingest, transformation, transcoding, encryption and delivery of VOD; li..." "saas"
            ol = container "Order list" "Setting a budget and its' allocations genres & channels. Existing commitments also captured. Targ..." ""
            pira = container "Pirate" "Pirate is a collection of applications used by various departments. Commercial affairs (business ..." ""
            p4ws = container "4Producers (Web Site)" "eCommissioning system. Allows C4 to engage with Production companies for Production companies to ..." "saas"
            pass = container "Advance Scheduling System" "The Advanced Scheduling System (A55) provides a view of a schedule for a specific channel and dat..." "desktopOrLaptop"
            pbm = container "Brand Management" "An application where can create or update Pirate Brands. This enables the business to group toget..." "desktopOrLaptop"
            pc = container "Companies" "This application allows users to create companies like production companies, studios etc" "desktopOrLaptop"
            pcgs = container "Content Generation System" "Generates the required detailed metadata required for each target platform and sends the appropri..." "desktopOrLaptop"
            pcps = container "Content Planning System" "VOD Scheduling" "desktopOrLaptop"
            pdap = container "Director and Producer Reporting System" "DPRS Transmission/Sales Report This report works in various stages: 1. A list of all contract num..." "desktopOrLaptop"
            pfas = container "Film Advanced Scheduling" "Manages the film scheduling scenarios based on deals purchased" "desktopOrLaptop"
            pge = container "General Enquiry" "Contains query functionality and several reports that can be run based on a broad range of topics..." "desktopOrLaptop"
            pip = container "Interface Payments" "Maintenance tables for 1. Nominal accounts – specifying what codes are valid 2. Specifying which ..." "desktopOrLaptop"
            pitt = container "Interface To Transmission Systems" "ITS prepares final schedules for Playout systems. It uses Programme schedules generated from PPS ..." "onPremise"
            pmam = container "Management Account Maintenance" "Maintenance of reference data related to Management Accounts (Programme Finance)  Not used much,..." "desktopOrLaptop"
            pmm = container "Media Management" "Video browse can also be launched from this application" "desktopOrLaptop"
            pofg = container "OFCOM File Generator" "Review one or more channels for their compliance with statutory commercial minutage regulations. ..." "desktopOrLaptop"
            ppps = container "Presentation Planning System" "Manages the detailed channel schedules with all the relevant transmission content required for br..." "desktopOrLaptop"
            pppsX = container "Presentation Planning System - PPS.NET" "This is the .NET version of PPS NOTE: We need to create all VOD processes and link one to this ap..." "desktopOrLaptop"
            ppp = container "Producers Portal" "An app which allows C4 to engage with Production companies for Production companies to fill in th..." "onPremise"
            ppc = container "Programme Certification" "Programme Certification gives the users of the system the ability look at the assets when they ar..." "desktopOrLaptop"
            prta = container "Real Time As-Run 2" "Provides real-time playout updates to Pirate systems." "onPremise"
            pswo = container "Stock Write Off" "Channel 4 commission or purchase programmes (stock) to be consumed by the schedule using annual t..." "desktopOrLaptop"
            psfv = container "Subtitle File Viewer" "Provides a view over the content of subtitles and the ability to quickly search for bad-language ..." "hybrid"
            ptis = container "Transcode Initiation Service" "TIS2 is the back-end engine of the VoD system, running background jobs ranging from asset synchro..." "onPremise"
            pvb = container "Video Browse" "Video Browse is a client-side.NET application that is part of the Pirate domain. It provides user..." "onPremise"
            pve = container "Viewer Enquiry" "Viewing the logged calls made by viewers regarding transmitted programmes. EXE name: VE" "desktopOrLaptop"
            pvms = container "VOD Management System (VMS)" "" "desktopOrLaptop"
            pvma = container "VoD Material Allocation" "VoD Material Allocation is small module inside Media Management. This module used by Programme Ma..." "desktopOrLaptop"
            pvt = container "VOD Tracker" "Support tool for monitoring VOD systems and workflows" "desktopOrLaptop"
            pt = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" ""
            pcX = container "Promo Create" "Hosted by I2, CMT is a web-based tool with secure log-in credentials . The tool allows Long Term ..." "saas"
            scf = container "Sky Curated Feeds" "Web application designed to create ordered curated lists for presentation on Sky UVP/VRP platforms" ""
            soun = container "Soundmouse" "Representation of Soundmouse as company. Covers all SaaS products offered by Soundmouse: Soundmou..." "saas"
            spap = container "Soundmouse Pre-TX and Post-TX Exporter" "Creates both Pre-TX and Post-TX export files to Soundmouse for music reporting and production rep..." ""
            spri = container "Sprinklr" "Sprinklr is a social media management platform that enables enterprise brands to connect with cus..." "saas"
            ssfa = container "Subtitling Sep FLS and Teletext with Subtotals (with Ray Amendments)" "Business Objects Report 'Subtitling Sep FLS and Teletext with Subtotals (with Ray Amendments)' - ..." ""
            tb = container "The Bible" "The bible is a host of information related to the programme idea, such as the programme descripti..." "onPremise"
            typ = container "Three Year Plan" "" ""
        }

        /* ============================================================
           CONTENT SOURCING PLATFORM
           ============================================================ */
        
        csp = softwareSystem "Content Sourcing Platform" "Platform from LeanIX" {
            
            crmc = container "Customer Relationship Manager  (Content)" "A system used by the commissioning dept to track and manage programme ideas from pitch to greenlight" "paas"
            dist = container "Distributor" "Supplier of acquired content e.g. a US Studio" ""
            pasc = container "Acquisition Stock Control" "A Read-only/Live reporting tool, allowing users to track stock usage (available, scheduled, used)..." "desktopOrLaptop"
            pcf = container "Cashflow Forecasting" "Forecasting tool for managing cash, when are production companies actually going to be paid compa..." "desktopOrLaptop"
            pcc = container "Commissioning Cycle" "Manages the agreements of commissioned content." "desktopOrLaptop"
            pp = container "Programmes" "" "desktopOrLaptop"
            ppX = container "Purchases" "" "desktopOrLaptop"
            pc = container "Production Company" "Supplier of commissioned content e.g. All 3 Media NOTE: NOT an application" ""
        }

        /* ============================================================
           DATA AND ANALYTICS PLATFORM
           ============================================================ */
        
        dap = softwareSystem "Data and Analytics Platform" "An extensive Massive Parallel Processing (MPP) platform designed for analytics tasks, which inclu..." {
            
            as = container "Audience Segmentation" "Enables publishers and broadcasters to grow and retain audiences and increase monetisation for a ..." "saas"
            barb = container "BARB" "Founded by the major organisations in the UK television and advertising industry, BARB is respons..." "onPremise"
            bor = container "Business Objects Reporting" "This application represents all Business Object reports generated by BI team and are read by busi..." "hybrid"
            cedw = container "Enterprise Data Warehouse" "Data Warehouse application used as a host of analytics data in a star schema or a columnar databa..." "hybrid"
            c4 = container "Core 4" "https://www.core4.channel4.com/hub Core4 is Channel 4's quantitative insight community, made up o..." ""
            dcri = container "Data Clean Room (InfoSum)" "A data platform with a vision to connect the world’s data without ever sharing it – by developing..." "saas"
            dcrs = container "Data Clean Room (Snowflake)" "A data platform with a vision to connect the world’s data without ever sharing it – by developing..." "saas"
            df = container "Data Fabric" "Data Fabric is an innovative approach designed to simplify and streamline data management across ..." "saas"
            tabl = container "Tableau" "Tableau is a data visualization tool used in the Business Intelligence Industry. It helps in simp..." "saas"
            wa = container "Web Analytics" "Web Analytics software used by M&VE for All 4 & Online Services Adobe Analytics is the solution f..." "saas"
        }

        /* ============================================================
           FINANCE SYSTEMS PLATFORM
           ============================================================ */
        
        fsp = softwareSystem "Finance Systems Platform" "Platform from LeanIX" {
            
            atax = container "Alphatax" "Corporation tax compliance software, providing complete control over the preparation and manageme..." ""
            bbp = container "Barclays Banking Portal" "Barclays Online platform used to transact FX deals. File Gateway is a host to host connectivity p..." ""
            bdn = container "Barclays.Net" "Barclays service used to download statements." ""
            bsw = container "Basware" "Enterprise software for financial processes, purchase to pay and financial management. Manage Inv..." "saas"
            cmx = container "Cachematrix" "SaaS solution for cash management" ""
            ebs = container "E-Business Suite" "Channel4 Oracle E-business Suite application used in Finance department for Accounts, Cash and As..." "onPremise"
            faf = container "Finance Approval Form" "" ""
            msc = container "Mastercard" "" ""
            odf = container "Oracle eBS Excel data files" "These are a collection of manually generated .xslx files out of Oracle e-Business that contain va..." ""
            pjc = container "Project Codes" "App used to generate project codes which are used in Oracle and across Channel 4." ""
            sov = container "Sovos" "Sovos helps in digital transformation of tax, with complete, connected offerings for tax determin..." "saas"
            sbi = container "SplashBI" "SplashBI is an all-in-one framework for visualising, reporting and analysing data." "saas"
            tgn = container "Tungsten Network" "Tungsten provide a multiple distribution channel service to a single stream invoice feed." ""
            wda = container "Workday Adaptive" "Workday Adaptive is Channel 4 Finance's Planning and Consolidation tool" "saas"
        }

        /* ============================================================
           LINEAR PLAYOUT PLATFORM
           ============================================================ */
        
        lpp = softwareSystem "Linear Playout Platform" "Platform from LeanIX" {
            
            ac = container "Amagi Cloudport" "<https://www.amagi.com/products/cloudport-cloud-playout>\ \ Amagi CLOUDPORT supports media ingest..." "saas"
            lsp = container "Linear Service Provider" "" "saas"
            ppps = container "Presentation Planning System" "Manages the detailed channel schedules with all the relevant transmission content required for br..." "desktopOrLaptop"
            pt = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" ""
            sp = container "Stargate Portal" "" "saas"
        }

        /* ============================================================
           MARKETING PLATFORM
           ============================================================ */
        
        mp = softwareSystem "Marketing Platform" "Platform from LeanIX" {
            
            braz = container "Braze" "Braze is a mobile marketing automation platform that provides a CRM and multichannel messaging su..." "saas"
            mpar = container "mParticle" "mParticle is a Customer Data Platform. It collects customer data once through secure APIs and SDK..." "saas"
            po = container "Promo Optimizer" "User-friendly TV promo scheduling tool. Leveraging advanced optimization and sequencing algorithm..." ""
        }

        /* ============================================================
           MEDIA MANAGEMENT PLATFORM
           ============================================================ */
        
        mmp = softwareSystem "Media Management Platform" "Platform from LeanIX" {
            
            awar = container "Awards" "Awards is a repository of all awards won by Channel 4 or where Channel 4 has been nominated. Plat..." "saas"
            msp = container "Media Service Provider" "Service provider for Digital Asset Management System" "saas"
            pmm = container "Media Management" "Video browse can also be launched from this application" "desktopOrLaptop"
            pvb = container "Video Browse" "Video Browse is a client-side.NET application that is part of the Pirate domain. It provides user..." "onPremise"
            pt = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" ""
            ppsp = container "Post Production Service Provider" "Post production service is pre-integrated to MSP and has suites available in HFR. This work can b..." ""
            rta = container "Ready to Air" "Deliver pre-transmission & pre-release video to journalists securely and reliably, wherever they ..." ""
            uv = container "Underground Vault" "Team that handles live content operations for our linear channels.Controlled and secure location ..." ""
        }

        /* ============================================================
           PEOPLE SYSTEMS PLATFORM
           ============================================================ */
        
        psp = softwareSystem "People Systems Platform" "Platform from LeanIX" {
            
            4peo = container "4People" "4People is a cloud HR and people system that empowers mid-size organisations to effectively respo..." "saas"
            acti = container "ActivPay" "Actvipay is Channel 4's 3rd party payroll provider." "saas"
            ac = container "Alert Cascade" "Crisis event mass communication tool" "desktopOrLaptop"
            bp = container "Benefits Portal" "" "saas"
            er = container "Executive Reporting" "Bespoke set of reports created in Power BI and served for the purpose of business reporting for t..." "paas"
            fes = container "Freelancer Engagement System" "HR system to request freelancers and bring them onboard. Freelancers submit timesheets via FES. O..." "onPremise"
            ll = container "LinkedIn Learning" "LinkedIn Learning offers video courses taught by industry experts in software, creative, and busi..." "saas"
            popp = container "Poppulo" "Internal communications Internal Communication, newsletter system. Used by internal comms. Integr..." "saas"
            tlh = container "The Learning Hive" "Cornerstone is a cloud-based learning and talent management solutions platform." "saas"
        }

        /* ============================================================
           RIGHTS MANAGEMENT PLATFORM
           ============================================================ */
        
        rmp = softwareSystem "Rights Management Platform" "Platform from LeanIX" {
            
            prms = container "Rights Management System" "" "desktopOrLaptop"
            pt = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" ""
            rc = container "Repeats Clearances" "This excel spreadsheet is our record of all programmes repeated on C4 with details of any rights/..." ""
            soun = container "Soundmouse" "Representation of Soundmouse as company. Covers all SaaS products offered by Soundmouse: Soundmou..." "saas"
        }

        /* ============================================================
           ROYALTIES AND SALES PLATFORM
           ============================================================ */
        
        rsp = softwareSystem "Royalties and Sales Platform" "Platform from LeanIX" {
            
            come = container "COMET" "Channel 4 International and National Rights Licencing Software used by Channel 4 to manage Films ..." "desktopOrLaptop"
            eps = container "Exclusivity Payment Schedules" "Contains payment details due to the artist for an exclusivity deal" ""
            neo = container "Neo" "NEO is a Soundmouse application that 4Studio and Rights Team users use. NEO does a shazam of soci..." ""
            pap = container "Artist Payments" "Application for reporting artist royalties" "desktopOrLaptop"
            pris = container "Royalties Income system" "Manages the Statements and chasing of Statements to ensure Royalties owed to Channel 4 are tracke..." "desktopOrLaptop"
            prrs = container "Royalties Reporting System" "RRS Overview Description: The Royalty Reporting System (RRS) is an application used for the conso..." "onPremise"
            pt = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" ""
            rc = container "Repeats Clearances" "This excel spreadsheet is our record of all programmes repeated on C4 with details of any rights/..." ""
            sd = container "Sargent Disc" "Sargent-Disc is the U.K.’s foremost entertainment-technology provider, building cloud-based workf..." ""
            soun = container "Soundmouse" "Representation of Soundmouse as company. Covers all SaaS products offered by Soundmouse: Soundmou..." "saas"
            ted = container "Ted" "Ted is a (tactical) web application that is used by 4Studio to capture key information concerning..." "iaas"
            ussw = container "UK Secondary Sales Wishlist" "" ""
            vr = container "VOD Revenue" "" ""
            vwgm = container "VOD Writers Guild & Musician Payments" "" ""
            wga = container "Writers Guild Advances" "" ""
        }

        /* ============================================================
           SCHEDULING PLATFORM
           ============================================================ */
        
        sp = softwareSystem "Scheduling Platform" "The Scheduling Platform is a core functional domain that orchestrates the creation and management..." {
            
            mod = container "MediaGenix On Demand" "BeBanjo Movida VOD Management system (Comprising of systems which schedule and manage transcode a..." "saas"
            pass = container "Advance Scheduling System" "The Advanced Scheduling System (A55) provides a view of a schedule for a specific channel and dat..." "desktopOrLaptop"
            pepl = container "Electronic Press Listing" "Sends Electronic Programme Guide to other platforms Carries Rights information such as restart" "desktopOrLaptop"
            pitt = container "Interface To Transmission Systems" "ITS prepares final schedules for Playout systems. It uses Programme schedules generated from PPS ..." "onPremise"
            ppps = container "Presentation Planning System" "Manages the detailed channel schedules with all the relevant transmission content required for br..." "desktopOrLaptop"
            pppsX = container "Presentation Planning System - PPS.NET" "This is the .NET version of PPS NOTE: We need to create all VOD processes and link one to this ap..." "desktopOrLaptop"
        }

        /* ============================================================
           SMALL BUSINESS SERVICES
           ============================================================ */
        
        sbs = softwareSystem "Small Business Services" "A set of small applications delivering discreet business processes usually hosted on SQL on prem ..." {
            
            anda = container "ANDA" "ANDA is a document archive repository. Where physical documents need to be archived (signed contr..." "onPremise"
            comp = container "Competitions" "It is used by Legal & Compliance to select winners and runner ups for Channel 4 competitions. The..." "onPremise"
            cms = container "Contract Management System" "Contract Management System, used as a repository for contracts Owned by Procurement storing the m..." "onPremise"
            dsd = container "Diversity Suppliers DB" "This is a database of supplier information used by the Creative Diversity team based in Glasgow," "onPremise"
            fa = container "FOIA Application" "Application built on SQL Server for storing Freedom of Information Act requests" ""
            mc = container "Music Clearance" "It is used by colleagues in CACL - Commercial Affairs every time Channel 4 license a music track ..." "hybrid"
            pps = container "Post Production Schedule" "This application is used by 4Creative to plan the development of on-air promotional material and ..." ""
            pr = container "Producer Reporting" "It is used by Finance to format the producer reporting statements. The application takes all the ..." ""
            sac = container "Stills and Clips" "" ""
            time = container "Timesheets" "" "onPremise"
        }

        /* ============================================================
           VIDEO STREAMING PLATFORM
           ============================================================ */
        
        vsp = softwareSystem "Video Streaming Platform" "Includes all items that provide the value chain" {
            
            c4sl = container "Channel 4 Streaming (Legacy)" "Video on Demand platform across many devices including https://channel4.com" "iaas"
            cdna = container "Content Distribution Network (Accenture)" "Logical representation of the CDN's used by Channel 4 Streaming, controlled and maintained by Acc..." ""
            free = container "Freely" "" ""
            mpar = container "mParticle" "mParticle is a Customer Data Platform. It collects customer data once through secure APIs and SDK..." "saas"
            ova = container "Online Video Analytics" "Real-Time Streaming Video Intelligence" "saas"
            pipe = container "PIPE" "The CMS that drivers Channel 4 Streaming UX in the apps" "iaas"
            sm = container "Subscription Management" "The application that manages our subscription products such as offers and deals." "saas"
            sl = container "Sumo Logic" "Sumo Logic is a cloud-based log management and analytics service that leverages machine-generated..." "saas"
            tr = container "Tag Recommender" "A Data Science led application to aid the Channel 4 Streaming editors with tagging for Brands" "iaas"
            thin = container "ThinkAnalytics" "World leaders in AI personalized content discovery, hyper-targeted advertising and customer insight." "saas"
            yosp = container "YoSpace" "Dynamic Ad Insertion (replacement of linear ads) on live streams to our owned and operated stream..." "saas"
        }

        /* ============================================================
           WORKSPACE SYSTEMS PLATFORM
           ============================================================ */
        
        wsp = softwareSystem "Workspace Systems Platform" "Platform from LeanIX" {
            
            ac = container "Alert Cascade" "Crisis event mass communication tool" "desktopOrLaptop"
            ce = container "Concept Evolution" "FM Job sheets for building maintenance used by Facilities & Workspace" "onPremise"
            egen = container "Egencia" "Egencia is a SaaS platform developed by Amex GBT that offers corporate travel management solution..." "saas"
            tb = container "Taxi Booking" "This application describes are taxi booking capability at Channel 4." "saas"
            tb-n = container "Taxi Booking - non-London" "This application is used for London based Taxi bookings to and from Horseferry Road" "saas"
        }
        
        /* ============================================================
           PERSON -> APPLICATION RELATIONSHIPS
           ============================================================ */
        
        c4ccToAp = c4cc -> cp.ap "Uses"
        c4ciToAp = c4ci -> cp.ap "Uses"
        c4csToAp = c4cs -> cp.ap "Uses"
        eaToAp = ea -> cp.ap "Uses"
        c4ctToCari = c4ct -> cp.cari "Uses"
        eaToCari = ea -> cp.cari "Uses"
        c4csToCc = c4cs -> cp.cc "Uses"
        c4csToFsh = c4cs -> cp.fsh "Uses"
        c4csToInno = c4cs -> cp.inno "Uses"
        c4caToSc = c4ca -> cp.sc "AV = Audio Visual"
        c4csToSc = c4cs -> cp.sc "Uses"
        c4csXToSc = c4csX -> cp.sc "Uses"
        c4ccToStel = c4cc -> cp.stel "Uses"
        c4ciToStel = c4ci -> cp.stel "Uses"
        c4csToStel = c4cs -> cp.stel "Uses"
        c4csXXToStel = c4csXX -> cp.stel "Uses"
        c4csXXXToStel = c4csXXX -> cp.stel "Uses"
        c4ctXToStel = c4ctX -> cp.stel "Uses"
        c4ccXToAsp = c4ccX -> bms.asp "Uses"
        c4cfToAcf = c4cf -> bms.acf "Uses"
        c4mcToBynd = c4mc -> bms.bynd "Uses"
        c4mmToBynd = c4mm -> bms.bynd "Uses"
        c4ciToC7t = c4ci -> bms.c7t "Uses"
        c4caXToC7t = c4caX -> bms.c7t "Uses"
        c4ccXXToC7t = c4ccXX -> bms.c7t "Uses"
        c4m4ToC7t = c4m4 -> bms.c7t "Uses"
        c4mpToC7t = c4mp -> bms.c7t "Uses"
        c4ccXToDasd = c4ccX -> bms.dasd "Uses"
        eppToEt = epp -> bms.et "Uses"
        eppToGrac = epp -> bms.grac "Uses"
        c4ccXXXToMod = c4ccXXX -> bms.mod "Uses"
        c4ccXToOlss = c4ccX -> bms.olss "Uses"
        c4ccXXXToOsp = c4ccXXX -> bms.osp "Uses"
        c4ctToOsp = c4ct -> bms.osp "Uses"
        c4cfToOl = c4cf -> bms.ol "Uses"
        c4ccXXXXToP4ws = c4ccXXXX -> bms.p4ws "Uses"
        epToP4ws = ep -> bms.p4ws "Uses"
        c4csToPass = c4cs -> bms.pass "Uses"
        c4ctXToPass = c4ctX -> bms.pass "Uses"
        c4caXXToPass = c4caXX -> bms.pass "Uses"
        c4ccXXXXXToPass = c4ccXXXXX -> bms.pass "Uses"
        c4ccXXXXXXToPass = c4ccXXXXXX -> bms.pass "Uses"
        c4ccXXXXXXXToPass = c4ccXXXXXXX -> bms.pass "Uses"
        ccfToPass = ccf -> bms.pass "Uses"
        c4csXXXXToPass = c4csXXXX -> bms.pass "Uses"
        c4mmXToPass = c4mmX -> bms.pass "Uses"
        c4mpToPass = c4mp -> bms.pass "Uses"
        c4caXXToPbm = c4caXX -> bms.pbm "Uses"
        ccfToPbm = ccf -> bms.pbm "Uses"
        c4cfToPbm = c4cf -> bms.pbm "Uses"
        c4ciXToPc = c4ciX -> bms.pc "Uses"
        c4caXXToPc = c4caXX -> bms.pc "Uses"
        c4ccXXXXXToPc = c4ccXXXXX -> bms.pc "Uses"
        c4ccXXXXXXXXToPc = c4ccXXXXXXXX -> bms.pc "Uses"
        c4ccXXXXXXXXXToPc = c4ccXXXXXXXXX -> bms.pc "Uses"
        c4ccXXXXXXXXXXToPc = c4ccXXXXXXXXXX -> bms.pc "Uses"
        c4ccXXXXXXXXXXXToPc = c4ccXXXXXXXXXXX -> bms.pc "Uses"
        c4ccXXXXXXXXXXXXToPc = c4ccXXXXXXXXXXXX -> bms.pc "Uses"
        c4ccXXXXXXToPc = c4ccXXXXXX -> bms.pc "Uses"
        c4ccXXXXXXXToPc = c4ccXXXXXXX -> bms.pc "Uses"
        ccfToPc = ccf -> bms.pc "Uses"
        c4cfToPc = c4cf -> bms.pc "Uses"
        c4csXXXXToPc = c4csXXXX -> bms.pc "Uses"
        c4f4ToPc = c4f4 -> bms.pc "Uses"
        c4m4ToPc = c4m4 -> bms.pc "Uses"
        c4mmXToPc = c4mmX -> bms.pc "Uses"
        c4mpToPc = c4mp -> bms.pc "Uses"
        c4ciXToPcgs = c4ciX -> bms.pcgs "Uses"
        c4csToPcgs = c4cs -> bms.pcgs "Uses"
        c4caXXToPcgs = c4caXX -> bms.pcgs "Uses"
        c4ccXXXXXXXXXToPcgs = c4ccXXXXXXXXX -> bms.pcgs "Uses"
        c4ccXXXXXXXXXXXXToPcgs = c4ccXXXXXXXXXXXX -> bms.pcgs "Uses"
        c4ccXXXXXXXToPcgs = c4ccXXXXXXX -> bms.pcgs "Uses"
        c4ccXXXToPcgs = c4ccXXX -> bms.pcgs "Uses"
        c4csXXXXToPcgs = c4csXXXX -> bms.pcgs "Uses"
        c4m4ToPcgs = c4m4 -> bms.pcgs "Uses"
        c4mcToPcgs = c4mc -> bms.pcgs "Uses"
        c4mmXToPcgs = c4mmX -> bms.pcgs "Uses"
        c4mpToPcgs = c4mp -> bms.pcgs "Uses"
        c4ciXToPcps = c4ciX -> bms.pcps "Uses"
        c4csToPcps = c4cs -> bms.pcps "Uses"
        c4caXXToPcps = c4caXX -> bms.pcps "Uses"
        c4ccXXXXXToPcps = c4ccXXXXX -> bms.pcps "Uses"
        c4ccXXXXXXXXXToPcps = c4ccXXXXXXXXX -> bms.pcps "Uses"
        c4ccXXXXXXXToPcps = c4ccXXXXXXX -> bms.pcps "Uses"
        c4ccXXXToPcps = c4ccXXX -> bms.pcps "Uses"
        c4mpToPcps = c4mp -> bms.pcps "Uses"
        c4caXXXToPdap = c4caXXX -> bms.pdap "Uses"
        c4csToPfas = c4cs -> bms.pfas "Uses"
        c4caXXToPfas = c4caXX -> bms.pfas "Uses"
        c4ccXXXXXToPfas = c4ccXXXXX -> bms.pfas "Uses"
        ccfToPfas = ccf -> bms.pfas "Uses"
        c4csXXXXToPfas = c4csXXXX -> bms.pfas "Uses"
        c4ciXToPge = c4ciX -> bms.pge "Uses"
        c4csToPge = c4cs -> bms.pge "Uses"
        c4ctXToPge = c4ctX -> bms.pge "Uses"
        c4caXXToPge = c4caXX -> bms.pge "Uses"
        c4ccXXXXXXXXXXXXXToPge = c4ccXXXXXXXXXXXXX -> bms.pge "Uses"
        c4ccXXXXToPge = c4ccXXXX -> bms.pge "Uses"
        c4ccXXXXXXXXXXXXXXToPge = c4ccXXXXXXXXXXXXXX -> bms.pge "Uses"
        c4ccXXXXXToPge = c4ccXXXXX -> bms.pge "Uses"
        c4ccXXXXXXXXToPge = c4ccXXXXXXXX -> bms.pge "Uses"
        c4ccXXXXXXXXXToPge = c4ccXXXXXXXXX -> bms.pge "Uses"
        c4ccXXXXXXXXXXXXXXXToPge = c4ccXXXXXXXXXXXXXXX -> bms.pge "Uses"
        c4ccXXXXXXXXXXToPge = c4ccXXXXXXXXXX -> bms.pge "Uses"
        c4ccXXXXXXXXXXXToPge = c4ccXXXXXXXXXXX -> bms.pge "Uses"
        c4ccXXXXXXXXXXXXToPge = c4ccXXXXXXXXXXXX -> bms.pge "Uses"
        c4ccXXXXXXToPge = c4ccXXXXXX -> bms.pge "Uses"
        c4ccXXXXXXXToPge = c4ccXXXXXXX -> bms.pge "Uses"
        c4ccXXToPge = c4ccXX -> bms.pge "Uses"
        c4ccXXXXXXXXXXXXXXXXToPge = c4ccXXXXXXXXXXXXXXXX -> bms.pge "Uses"
        c4ccXToPge = c4ccX -> bms.pge "Uses"
        c4ccXXXToPge = c4ccXXX -> bms.pge "Not all information is available and needs to be obtained from other sources. Clunky"
        ccfToPge = ccf -> bms.pge "Uses"
        c4cpToPge = c4cp -> bms.pge "Uses"
        c4csXXXXToPge = c4csXXXX -> bms.pge "Uses"
        c4f4ToPge = c4f4 -> bms.pge "Uses"
        c4mToPge = c4m -> bms.pge "Uses"
        c4m4XToPge = c4m4X -> bms.pge "Uses"
        c4m4ToPge = c4m4 -> bms.pge "Uses"
        c4mcToPge = c4mc -> bms.pge "Uses"
        c4mmXToPge = c4mmX -> bms.pge "Uses"
        c4mpToPge = c4mp -> bms.pge "Uses"
        c4ccXXXXXXToPip = c4ccXXXXXX -> bms.pip "Uses"
        c4ccXXXXXXXToPip = c4ccXXXXXXX -> bms.pip "Uses"
        ccfToPip = ccf -> bms.pip "Uses"
        c4cfToPip = c4cf -> bms.pip "Uses"
        c4mmXToPip = c4mmX -> bms.pip "Uses"
        c4mpToPip = c4mp -> bms.pip "Uses"
        c4ccXXXToPitt = c4ccXXX -> bms.pitt "Uses"
        c4csToPmam = c4cs -> bms.pmam "Uses"
        c4ccXXXXXXXToPmam = c4ccXXXXXXX -> bms.pmam "Uses"
        ccfToPmam = ccf -> bms.pmam "Uses"
        c4cfToPmam = c4cf -> bms.pmam "Uses"
        c4csToPmm = c4cs -> bms.pmm "Uses"
        c4caXXToPmm = c4caXX -> bms.pmm "Uses"
        c4ccXXXXXToPmm = c4ccXXXXX -> bms.pmm "Uses"
        c4ccXXXXXXXXXXToPmm = c4ccXXXXXXXXXX -> bms.pmm "Uses"
        c4ccXXXXXXXXXXXXToPmm = c4ccXXXXXXXXXXXX -> bms.pmm "Uses"
        c4ccXXXXXXToPmm = c4ccXXXXXX -> bms.pmm "Uses"
        c4ccXXXXXXXToPmm = c4ccXXXXXXX -> bms.pmm "Uses"
        c4ccXXToPmm = c4ccXX -> bms.pmm "Uses"
        c4m4XToPmm = c4m4X -> bms.pmm "Uses"
        c4mmXToPmm = c4mmX -> bms.pmm "Uses"
        c4csToPofg = c4cs -> bms.pofg "Uses"
        c4ccXXXXXXXToPofg = c4ccXXXXXXX -> bms.pofg "Uses"
        ccfToPofg = ccf -> bms.pofg "Uses"
        c4cfToPofg = c4cf -> bms.pofg "Uses"
        c4csToPpps = c4cs -> bms.ppps "Uses"
        c4caXXToPpps = c4caXX -> bms.ppps "Uses"
        c4ccXXXXXToPpps = c4ccXXXXX -> bms.ppps "Uses"
        c4ccXXXXXXXXXXXToPpps = c4ccXXXXXXXXXXX -> bms.ppps "Uses"
        c4ccXXXXXXXToPpps = c4ccXXXXXXX -> bms.ppps "Uses"
        c4ccXToPpps = c4ccX -> bms.ppps "Uses"
        c4csXXXXToPpps = c4csXXXX -> bms.ppps "Uses"
        c4m4XToPpps = c4m4X -> bms.ppps "Uses"
        c4m4ToPpps = c4m4 -> bms.ppps "Uses"
        c4mmXToPpps = c4mmX -> bms.ppps "Uses"
        c4mpToPpps = c4mp -> bms.ppps "Uses"
        c4ciXToPppsX = c4ciX -> bms.pppsX "Uses"
        c4csToPppsX = c4cs -> bms.pppsX "Uses"
        c4caXXToPppsX = c4caXX -> bms.pppsX "Uses"
        c4ccXXXXXToPppsX = c4ccXXXXX -> bms.pppsX "Uses"
        c4ccXXXXXXXXXXToPppsX = c4ccXXXXXXXXXX -> bms.pppsX "Uses"
        c4ccXXXXXXXXXXXToPppsX = c4ccXXXXXXXXXXX -> bms.pppsX "Uses"
        c4ccXXXXXXXToPppsX = c4ccXXXXXXX -> bms.pppsX "Uses"
        ccfToPppsX = ccf -> bms.pppsX "Uses"
        c4m4XToPppsX = c4m4X -> bms.pppsX "Uses"
        c4mmXToPppsX = c4mmX -> bms.pppsX "Uses"
        c4caXXToPpp = c4caXX -> bms.ppp "Uses"
        c4ccXXXXXXXXXXXXXToPpp = c4ccXXXXXXXXXXXXX -> bms.ppp "Uses"
        c4ccXXXXXToPpp = c4ccXXXXX -> bms.ppp "Uses"
        c4ccXXXXXXXXToPpp = c4ccXXXXXXXX -> bms.ppp "Uses"
        c4ccXXXXXXXXXToPpp = c4ccXXXXXXXXX -> bms.ppp "Uses"
        c4ccXXXXXXXXXXXXXXXToPpp = c4ccXXXXXXXXXXXXXXX -> bms.ppp "Uses"
        c4ccXXXXXXXXXXToPpp = c4ccXXXXXXXXXX -> bms.ppp "Uses"
        c4ccXXXXXXXXXXXToPpp = c4ccXXXXXXXXXXX -> bms.ppp "Uses"
        c4ccXXXXXXXXXXXXToPpp = c4ccXXXXXXXXXXXX -> bms.ppp "Uses"
        c4ccXXXXXXToPpp = c4ccXXXXXX -> bms.ppp "Uses"
        c4ccXXXXXXXToPpp = c4ccXXXXXXX -> bms.ppp "Uses"
        ccfToPpp = ccf -> bms.ppp "Uses"
        c4csXXXXToPpp = c4csXXXX -> bms.ppp "Uses"
        c4f4ToPpp = c4f4 -> bms.ppp "Uses"
        c4m4XToPpp = c4m4X -> bms.ppp "Uses"
        c4mmXToPpp = c4mmX -> bms.ppp "Uses"
        epToPpp = ep -> bms.ppp "Uses"
        c4csToPpc = c4cs -> bms.ppc "Uses"
        c4caXXToPpc = c4caXX -> bms.ppc "Uses"
        c4caXToPpc = c4caX -> bms.ppc "Uses"
        c4ccXXXXXToPpc = c4ccXXXXX -> bms.ppc "Uses"
        c4ccXXXXXXXXToPpc = c4ccXXXXXXXX -> bms.ppc "Uses"
        c4ccXXXXXXXXXToPpc = c4ccXXXXXXXXX -> bms.ppc "Uses"
        c4ccXXXXXXXXXXToPpc = c4ccXXXXXXXXXX -> bms.ppc "Uses"
        c4ccXXXXXXXXXXXToPpc = c4ccXXXXXXXXXXX -> bms.ppc "Uses"
        c4ccXXXXXXXXXXXXToPpc = c4ccXXXXXXXXXXXX -> bms.ppc "Uses"
        c4ccXXXXXXToPpc = c4ccXXXXXX -> bms.ppc "Uses"
        c4ccXXXXXXXToPpc = c4ccXXXXXXX -> bms.ppc "Uses"
        c4csXXXXToPpc = c4csXXXX -> bms.ppc "Uses"
        c4m4XToPpc = c4m4X -> bms.ppc "Uses"
        c4mmXToPpc = c4mmX -> bms.ppc "Uses"
        c4ccXXXToPrta = c4ccXXX -> bms.prta "Uses"
        ccfToPswo = ccf -> bms.pswo "Uses"
        c4cfToPswo = c4cf -> bms.pswo "Uses"
        c4ccXXXXXXXToPsfv = c4ccXXXXXXX -> bms.psfv "Uses"
        c4ccXXXToPsfv = c4ccXXX -> bms.psfv "Uses"
        c4m4ToPsfv = c4m4 -> bms.psfv "Uses"
        c4ccXXXToPtis = c4ccXXX -> bms.ptis "Uses"
        c4cToPvb = c4c -> bms.pvb "Uses"
        c4caXToPvb = c4caX -> bms.pvb "Uses"
        c4ccXXXXXXXToPvb = c4ccXXXXXXX -> bms.pvb "Uses"
        c4ccXXXXXXXXXXXXXXXXToPvb = c4ccXXXXXXXXXXXXXXXX -> bms.pvb "Uses"
        c4ccXXXToPvb = c4ccXXX -> bms.pvb "Uses"
        c4ciXToPve = c4ciX -> bms.pve "Uses"
        c4csToPve = c4cs -> bms.pve "Uses"
        c4caXXToPve = c4caXX -> bms.pve "Uses"
        c4ccXXXXXToPve = c4ccXXXXX -> bms.pve "Uses"
        c4ccXXXXXXXXXXXToPve = c4ccXXXXXXXXXXX -> bms.pve "Uses"
        c4ccXXXXXXXToPve = c4ccXXXXXXX -> bms.pve "Uses"
        c4ccXXXToPve = c4ccXXX -> bms.pve "Uses"
        c4csXXXXToPve = c4csXXXX -> bms.pve "Uses"
        c4mmXToPve = c4mmX -> bms.pve "Uses"
        c4mpToPve = c4mp -> bms.pve "Uses"
        c4ciXToPvms = c4ciX -> bms.pvms "Uses"
        c4caXXToPvms = c4caXX -> bms.pvms "Uses"
        c4ccXXXXXToPvms = c4ccXXXXX -> bms.pvms "Uses"
        c4ccXXXXXXXToPvms = c4ccXXXXXXX -> bms.pvms "Uses"
        c4ccXXXToPvma = c4ccXXX -> bms.pvma "Uses"
        c4cfToSoun = c4cf -> bms.soun "Uses"
        c4ccXToSsfa = c4ccX -> bms.ssfa "Uses"
        c4ccXXXToTb = c4ccXXX -> bms.tb "Uses"
        epToDist = ep -> csp.dist "Uses"
        c4caXXToPasc = c4caXX -> csp.pasc "Uses"
        c4caXXXXToPasc = c4caXXXX -> csp.pasc "Uses"
        c4ccXXXXXToPasc = c4ccXXXXX -> csp.pasc "Uses"
        ccfToPasc = ccf -> csp.pasc "Uses"
        c4csToPcf = c4cs -> csp.pcf "Uses"
        c4caXXToPcf = c4caXX -> csp.pcf "Uses"
        c4ccXXXXXXToPcf = c4ccXXXXXX -> csp.pcf "Uses"
        c4ccXXXXXXXToPcf = c4ccXXXXXXX -> csp.pcf "Uses"
        ccfToPcf = ccf -> csp.pcf "Uses"
        c4cfToPcf = c4cf -> csp.pcf "Uses"
        c4ciXToPcc = c4ciX -> csp.pcc "Uses"
        c4csToPcc = c4cs -> csp.pcc "Uses"
        c4caXXToPcc = c4caXX -> csp.pcc "Uses"
        c4ccXXXXXXXXXXXXXToPcc = c4ccXXXXXXXXXXXXX -> csp.pcc "Uses"
        c4ccXXXXToPcc = c4ccXXXX -> csp.pcc "Uses"
        c4ccXXXXXToPcc = c4ccXXXXX -> csp.pcc "Uses"
        c4ccXXXXXXXXToPcc = c4ccXXXXXXXX -> csp.pcc "Uses"
        c4ccXXXXXXXXXToPcc = c4ccXXXXXXXXX -> csp.pcc "Uses"
        c4ccXXXXXXXXXXXXXXXToPcc = c4ccXXXXXXXXXXXXXXX -> csp.pcc "Uses"
        c4ccXXXXXXXXXXToPcc = c4ccXXXXXXXXXX -> csp.pcc "Uses"
        c4ccXXXXXXXXXXXToPcc = c4ccXXXXXXXXXXX -> csp.pcc "Uses"
        c4ccXXXXXXXXXXXXToPcc = c4ccXXXXXXXXXXXX -> csp.pcc "Uses"
        c4ccXXXXXXToPcc = c4ccXXXXXX -> csp.pcc "Uses"
        c4ccXXXXXXXToPcc = c4ccXXXXXXX -> csp.pcc "Uses"
        ccfToPcc = ccf -> csp.pcc "Uses"
        c4csXXXXToPcc = c4csXXXX -> csp.pcc "Uses"
        c4f4ToPcc = c4f4 -> csp.pcc "Uses"
        c4m4XToPcc = c4m4X -> csp.pcc "Uses"
        c4mmXToPcc = c4mmX -> csp.pcc "Uses"
        epToPcc = ep -> csp.pcc "Uses"
        c4ciXToPp = c4ciX -> csp.pp "Uses"
        c4csToPp = c4cs -> csp.pp "Uses"
        c4caXXToPp = c4caXX -> csp.pp "Uses"
        c4ccXXXXXToPp = c4ccXXXXX -> csp.pp "Uses"
        c4ccXXXXXXXXToPp = c4ccXXXXXXXX -> csp.pp "Uses"
        c4ccXXXXXXXXXToPp = c4ccXXXXXXXXX -> csp.pp "Uses"
        c4ccXXXXXXXXXXToPp = c4ccXXXXXXXXXX -> csp.pp "Uses"
        c4ccXXXXXXXXXXXToPp = c4ccXXXXXXXXXXX -> csp.pp "Uses"
        c4ccXXXXXXXXXXXXToPp = c4ccXXXXXXXXXXXX -> csp.pp "Uses"
        c4ccXXXXXXToPp = c4ccXXXXXX -> csp.pp "Uses"
        c4ccXXXXXXXToPp = c4ccXXXXXXX -> csp.pp "Uses"
        c4ccXXXToPp = c4ccXXX -> csp.pp "Uses"
        ccfToPp = ccf -> csp.pp "Uses"
        c4f4ToPp = c4f4 -> csp.pp "Uses"
        c4mcToPp = c4mc -> csp.pp "Uses"
        c4caXXToPpX = c4caXX -> csp.ppX "Uses"
        c4ccXXXXXToPpX = c4ccXXXXX -> csp.ppX "Uses"
        c4ccXXXXXXXXToPpX = c4ccXXXXXXXX -> csp.ppX "Uses"
        c4ccXXXToPpX = c4ccXXX -> csp.ppX "Uses"
        ccfToPpX = ccf -> csp.ppX "Uses"
        c4csXXXXXToAs = c4csXXXXX -> dap.as "Uses"
        c4csToBarb = c4cs -> dap.barb "Uses"
        c4csXXXXXXToBarb = c4csXXXXXX -> dap.barb "Uses"
        c4ccToBor = c4cc -> dap.bor "Uses"
        c4ciToBor = c4ci -> dap.bor "Uses"
        c4csToBor = c4cs -> dap.bor "Uses"
        c4ctXToBor = c4ctX -> dap.bor "Uses"
        c4csXXXXXXXToCedw = c4csXXXXXXX -> dap.cedw "Uses"
        c4csXXXXXXToCedw = c4csXXXXXX -> dap.cedw "Uses"
        c4ctXXToCedw = c4ctXX -> dap.cedw "Uses"
        c4csXXXXXXXToC4 = c4csXXXXXXX -> dap.c4 "Uses"
        c4csToDcri = c4cs -> dap.dcri "Uses"
        c4ciXXToDcrs = c4ciXX -> dap.dcrs "Uses"
        c4mmToDcrs = c4mm -> dap.dcrs "C4 Audience Team and Marketing team use the Data Clean Room solution for creating overlapping aud..."
        c4mmXXToDcrs = c4mmXX -> dap.dcrs "Uses"
        c4csToDf = c4cs -> dap.df "Uses"
        c4csXToDf = c4csX -> dap.df "Uses"
        c4mpXToTabl = c4mpX -> dap.tabl "Uses"
        c4mpXToWa = c4mpX -> dap.wa "Uses"
        ccfToAtax = ccf -> fsp.atax "Uses"
        ccfToBbp = ccf -> fsp.bbp "Uses"
        c4ToBsw = c4 -> fsp.bsw "Raise and approve POs"
        ccfToBsw = ccf -> fsp.bsw "Uses"
        ccfrssToBsw = ccfrss -> fsp.bsw "Uses"
        ccfToEbs = ccf -> fsp.ebs "Uses"
        ccfrssToEbs = ccfrss -> fsp.ebs "Uses"
        c4ToFaf = c4 -> fsp.faf "Uses"
        ccfToMsc = ccf -> fsp.msc "Uses"
        ccfToSov = ccf -> fsp.sov "Uses"
        ccfToSbi = ccf -> fsp.sbi "Uses"
        ccfrssToSbi = ccfrss -> fsp.sbi "Uses"
        ccfrssToTgn = ccfrss -> fsp.tgn "Uses"
        ccfToWda = ccf -> fsp.wda "Uses"
        c4ccXXXXXXXXXXXXXXXXToLsp = c4ccXXXXXXXXXXXXXXXX -> lpp.lsp "Uses"
        c4ccXXXToLsp = c4ccXXX -> lpp.lsp "Uses"
        c4ctToLsp = c4ct -> lpp.lsp "Uses"
        c4ctToSp = c4ct -> lpp.sp "Uses"
        c4mmXXToBraz = c4mmXX -> mp.braz "Uses"
        c4mpXXToMpar = c4mpXX -> mp.mpar "Uses"
        c4mpXXXToMpar = c4mpXXX -> mp.mpar "Uses"
        c4ccXXXXXToAwar = c4ccXXXXX -> mmp.awar "Uses"
        c4csXXXToMsp = c4csXXX -> mmp.msp "Uses"
        c4ccXXXXXXXXXXXXXXXXXToMsp = c4ccXXXXXXXXXXXXXXXXX -> mmp.msp "Uses"
        c4ccXXXXXXXToMsp = c4ccXXXXXXX -> mmp.msp "Uses"
        c4ccXToMsp = c4ccX -> mmp.msp "Uses"
        c4ctToMsp = c4ct -> mmp.msp "Uses"
        c4m4XToMsp = c4m4X -> mmp.msp "Uses"
        epToMsp = ep -> mmp.msp "Uses"
        c4caXToPpsp = c4caX -> mmp.ppsp "Uses"
        c4ctToPpsp = c4ct -> mmp.ppsp "Uses"
        c4m4XToPpsp = c4m4X -> mmp.ppsp "Uses"
        c4To4peo = c4 -> psp.4peo "Uses"
        c4cpTo4peo = c4cp -> psp.4peo "Uses"
        c4ToActi = c4 -> psp.acti "Uses"
        c4cpToActi = c4cp -> psp.acti "Uses"
        c4cXToAc = c4cX -> psp.ac "Uses"
        c4ToBp = c4 -> psp.bp "Uses"
        c4cpXToBp = c4cpX -> psp.bp "Uses"
        c4ctXXXToEr = c4ctXXX -> psp.er "Uses"
        c4ToFes = c4 -> psp.fes "Uses"
        c4cpToFes = c4cp -> psp.fes "Uses"
        c4ToLl = c4 -> psp.ll "Uses"
        c4cpXXToLl = c4cpXX -> psp.ll "Uses"
        c4cpToPopp = c4cp -> psp.popp "Uses"
        c4ToTlh = c4 -> psp.tlh "Uses"
        c4csToPrms = c4cs -> rmp.prms "Uses"
        c4caXXToPrms = c4caXX -> rmp.prms "Uses"
        c4ccXXXXXToPrms = c4ccXXXXX -> rmp.prms "Uses"
        c4ccXXXXXXXXXToPrms = c4ccXXXXXXXXX -> rmp.prms "Uses"
        c4ccXXXXXXXToPrms = c4ccXXXXXXX -> rmp.prms "Uses"
        c4ccXXXToPrms = c4ccXXX -> rmp.prms "Uses"
        ccfToPrms = ccf -> rmp.prms "Uses"
        c4m4ToPrms = c4m4 -> rmp.prms "Uses"
        c4mmXToPrms = c4mmX -> rmp.prms "Uses"
        c4caXXToRc = c4caXX -> rmp.rc "Uses"
        c4ciToCome = c4ci -> rsp.come "Uses"
        c4caXXToCome = c4caXX -> rsp.come "Uses"
        c4ccXXXToCome = c4ccXXX -> rsp.come "Uses"
        ccfrssToCome = ccfrss -> rsp.come "Uses"
        c4caXXToEps = c4caXX -> rsp.eps "Uses"
        c4caXXToNeo = c4caXX -> rsp.neo "Uses"
        c4csToPap = c4cs -> rsp.pap "Uses"
        c4caXXToPap = c4caXX -> rsp.pap "Uses"
        ccfToPap = ccf -> rsp.pap "Uses"
        c4csXXXXToPap = c4csXXXX -> rsp.pap "Uses"
        c4caXXToPris = c4caXX -> rsp.pris "Uses"
        c4ccXXXToPris = c4ccXXX -> rsp.pris "Uses"
        ccfToPris = ccf -> rsp.pris "Uses"
        c4m4ToPris = c4m4 -> rsp.pris "Uses"
        c4caXXToPrrs = c4caXX -> rsp.prrs "Uses"
        ccfToPrrs = ccf -> rsp.prrs "Uses"
        c4caXXToSd = c4caXX -> rsp.sd "Uses"
        c4m4ToTed = c4m4 -> rsp.ted "Uses"
        c4ccXXXXXToPepl = c4ccXXXXX -> sp.pepl "Uses"
        c4ccXXXXXXToPepl = c4ccXXXXXX -> sp.pepl "Uses"
        c4ccXXXXXXXToPepl = c4ccXXXXXXX -> sp.pepl "Uses"
        c4ccXXXToPepl = c4ccXXX -> sp.pepl "Uses"
        c4mcToPepl = c4mc -> sp.pepl "Uses"
        c4caXToAnda = c4caX -> sbs.anda "Uses"
        c4ccXXXToAnda = c4ccXXX -> sbs.anda "Clunky and difficult to use."
        c4cfXToCms = c4cfX -> sbs.cms "Uses"
        c4caXXXXXToFa = c4caXXXXX -> sbs.fa "Uses"
        c4ctXXToTime = c4ctXX -> sbs.time "Uses"
        evToC4sl = ev -> vsp.c4sl "Uses"
        c4mpXXXXToPipe = c4mpXXXX -> vsp.pipe "Uses"
        c4mpXXXXXToSm = c4mpXXXXX -> vsp.sm "Uses"
        c4ctXXToSl = c4ctXX -> vsp.sl "Uses"
        c4ccXXXToTr = c4ccXXX -> vsp.tr "Uses"
        c4mpXXToThin = c4mpXX -> vsp.thin "Uses"
        c4cfXXToCe = c4cfXX -> wsp.ce "Uses"
        c4ToEgen = c4 -> wsp.egen "Uses"
        ccfToEgen = ccf -> wsp.egen "Uses"

        /* ============================================================
           APPLICATION -> APPLICATION RELATIONSHIPS (from LeanIX Interfaces)
           ============================================================ */
        
        4ta = psp.4peo -> psp.acti "4People to ActivePay" "Mule" "Integration"
        4tac = psp.4peo -> wsp.ac "4People to Alert cascade" "Mule" "Integration"
        4tb = psp.4peo -> wsp.ac "4People to Benefits" "Mule" "Integration"
        4tce = psp.4peo -> wsp.ce "4People to Concept Evolution" "Mule" "Integration"
        4tcm = psp.4peo -> sbs.cms "4People to Contract Management System(CMS)" "Mule" "Integration"
        4tc = psp.4peo -> psp.tlh "4People to Cornerstone" "Mule" "Integration"
        4te = psp.4peo -> wsp.egen "4People to Egencia" "Mule" "Integration"
        4toe = psp.4peo -> fsp.ebs "4People to Oracle EBS" "Mule" "Integration"
        4tp = psp.4peo -> fsp.wda "4People to Planning" "Alternative" "Integration"
        4tpX = psp.4peo -> psp.popp "4People to Poppulo" "Mule" "Integration"
        atsf = sp.pass -> cp.stel "A55 to Stellar for Advanced Schedule data flow" "SFTP" "Integration"
        aptf = psp.acti -> fsp.wda "Active Pay to Financial Planning" "Mule" "Integration"
        atoe = psp.acti -> fsp.ebs "ActivPay to Oracle EBS" "Mule" "Integration"
        asst = vsp.yosp -> vsp.c4sl "Ad Serving System to C4S" "Alternative" "Integration"
        aate = dap.wa -> dap.cedw "Adobe Analytics to EDW" "Alternative" "Integration"
        apff = cp.ap -> bms.pbm "Agency Portal fetch from Pirate for Brand" "Mule" "Integration"
        apffX = cp.ap -> cp.stel "Agency Portal fetch from Stellar for Programme" "Mule" "Integration"
        apfs = cp.ap -> cp.stel "Agency Portal from Stellar for Pick Your Own transmission" "Mule" "Integration"
        ai = csp.pcc -> rsp.prrs "Agreement Information" "Alternative" "Integration"
        ap = rsp.sd -> rsp.pap "Artist payments" "Automate" "Integration"
        adaa = bms.asp -> mmp.msp "ASP Delivery Acknowledgment API" "Alternative" "Integration"
        alss = lpp.lsp -> bms.asp "ASP live subtitle streams to LSP" "Alternative" "Integration"
        alls = bms.asp -> lpp.lsp "ASP low latency stream from LSP" "Alternative" "Integration"
        apja = bms.asp -> mmp.msp "ASP Production Job API" "Alternative" "Integration"
        apjs = mmp.msp -> bms.asp "ASP Production Job Status API" "Alternative" "Integration"
        asfp = bms.asp -> bms.pira "ASP Schedule from Pirate" "Alternative" "Integration"
        assm = bms.asp -> mmp.msp "ASP Signer Source Media File Delivery" "Alternative" "Integration"
        avcm = bms.asp -> mmp.msp "ASP Viewing Copy Media File Delivery" "Alternative" "Integration"
        asal = cp.fsh -> dap.as "Audience Segments and Lookalikes to Freewheel" "Alternative" "Integration"
        bwpfo = fsp.ebs -> fsp.bbp "BACS & Wire Payments File Out" "Automate" "Integration"
        brdt = dap.barb -> dap.cedw "BARB ratings data to EDW" "SFTP" "Integration"
        btsf = dap.barb -> cp.stel "BARB to Stellar for Audience Universe" "SFTP" "Integration"
        btsfX = dap.barb -> cp.stel "BARB to Stellar for Impacts" "SFTP" "Integration"
        bpsri = fsp.bbp -> fsp.ebs "Barclay Payment Statement Receipt In" "Automate" "Integration"
        bsi = fsp.bbp -> fsp.ebs "Barclay Statement In" "Automate" "Integration"
        bbdc = fsp.ebs -> fsp.bsw "Basware Business Department Codes" "Alternative" "Integration"
        bcer = fsp.ebs -> fsp.bsw "Basware Currency Exchange Rates" "Alternative" "Integration"
        bglcvr = fsp.ebs -> fsp.bsw "Basware GL Cross Validation Rules" "Alternative" "Integration"
        bglnc = fsp.ebs -> fsp.bsw "Basware GL Nominal Codes" "Alternative" "Integration"
        bic = fsp.ebs -> fsp.bsw "Basware Individual Codes" "Alternative" "Integration"
        bis = fsp.bsw -> fsp.ebs "Basware Invoice Statuses" "Alternative" "Integration"
        bpvpci = fsp.ebs -> fsp.bsw "Basware Payments/Void Payments/Cancelled Invoices" "Alternative" "Integration"
        bpcc = fsp.ebs -> fsp.bsw "Basware Pirate Code Combinations" "Alternative" "Integration"
        bprodc = fsp.ebs -> fsp.bsw "Basware Product Codes" "Alternative" "Integration"
        bprojc = fsp.ebs -> fsp.bsw "Basware Project Codes" "Alternative" "Integration"
        bws = fsp.ebs -> fsp.bsw "Basware Suppliers" "Alternative" "Integration"
        b2ebs = fsp.bsw -> fsp.ebs "Basware to EBS for Approved Invoices" "Automate" "Integration"
        b2sbi = fsp.bsw -> fsp.ebs "Basware to SplashBI (Oracle eBS Schema)" "Alternative" "Integration"
        b2sbi2 = fsp.bsw -> fsp.sbi "Basware to SplashBI (Oracle eBS Schema)" "Alternative" "Integration"
        bur = fsp.ebs -> fsp.bsw "Basware User Rights" "Alternative" "Integration"
        buriu = fsp.ebs -> fsp.bsw "Basware User Rights (Inactive users)" "Alternative" "Integration"
        bta = psp.acti -> psp.bp "Benefits to Actvipay" "Alternative" "Integration"
        bdte = cp.stel -> dap.cedw "Budget data to EDW" "Alternative" "Integration"
        btmi = sp.mod -> bms.bynd "Bynder to MediaGenix Image Integration" "Alternative" "Integration"
        btmiX = sp.mod -> bms.bynd "Bynder to MediaGenix Image Tagging Changes" "Alternative" "Integration"
        chpt = psp.er -> dap.bor "C4 HR & Payroll to PowerBI Reporting" "Mule" "Integration"
        4io = fsp.ebs -> rsp.come "C4 intl overages" "SFTP" "Integration"
        cpty = vsp.yosp -> cp.stel "C4 Promo to YoSpace for Advertisements" "Mule" "Integration"
        4vatr = fsp.sov -> fsp.ebs "C4 VAT Returns" "Alternative" "Integration"
        cbsd = vsp.sm -> dap.cedw "C4S Braintree Subscriber data to EDW" "Alternative" "Integration"
        cetf = vsp.free -> sp.pepl "C4S EPG to Freely" "Alternative" "Integration"
        cete = vsp.mpar -> dap.cedw "C4S Events to EDW" "Alternative" "Integration"
        cfve = vsp.ova -> vsp.free "C4S Freely Video Events to BitMovin Analytics" "Alternative" "Integration"
        cfvs = vsp.cdna -> vsp.free "C4S Freely Video Stream from CDN" "Alternative" "Integration"
        cmif = vsp.cdna -> sp.mod "C4S MoD Images from CDN" "Alternative" "Integration"
        cqte = vsp.ova -> dap.cedw "C4S QoS to EDW" "Alternative" "Integration"
        csty = vsp.yosp -> bms.osp "C4S Streams to YoSpace" "Alternative" "Integration"
        ctaa = dap.wa -> vsp.c4sl "C4S to Adobe Analytics" "Alternative" "Integration"
        ctb = dap.barb -> vsp.c4sl "C4S to BARB" "Alternative" "Integration"
        ctc7 = vsp.c4sl -> bms.c7t "C4S to C4 7A Titles" "Alternative" "Integration"
        ctlv = lpp.lsp -> vsp.c4sl "C4S to Licence Validation Service" "Alternative" "Integration"
        ctsm = vsp.sm -> vsp.c4sl "C4S to Subscription Management (Aptitude)" "Alternative" "Integration"
        ctt- = vsp.thin -> vsp.c4sl "C4S to ThinkAnalytics - User Events" "Alternative" "Integration"
        ctet = dap.wa -> vsp.mpar "C4S Tracking Events to Adobe Analytics" "Alternative" "Integration"
        ctetX = vsp.mpar -> vsp.c4sl "C4S Tracking Events to mParticle" "Alternative" "Integration"
        cvmt = vsp.free -> sp.mod "C4S VoD Metadata to Freely" "Alternative" "Integration"
        c4st = mp.po -> mp.po "C4STELLARPROMO" "Alternative" "Integration"
        c4st2 = mp.po -> cp.stel "C4STELLARPROMO" "Alternative" "Integration"
        caap = cp.ap -> cp.stel "CARIA and Agency Portal from Stellar for Deals" "Mule" "Integration"
        cfsf = cp.cari -> cp.stel "CARIA from Stellar for Copy Rotation Instruction" "Mule" "Integration"
        ctsf = cp.cari -> cp.stel "CARIA to Stellar for Copy Rotation Instructions" "SFTP" "Integration"
        ctsfX = cp.cari -> cp.stel "CARIA to STELLAR for Deals and Campaign creation" "SFTP" "Integration"
        cro2c = fsp.ebs -> rsp.come "Cash Receipts from Oracle to Comet" "Alternative" "Integration"
        ctt = bms.pcgs -> bms.ptis "CGS to TIS2" "Alternative" "Integration"
        c4it = mmp.msp -> mmp.pmm "Channel 4 Interstitals to RedBee" "Mule" "Integration"
        c4sr = mp.braz -> vsp.c4sl "Channel 4 Streaming Recommendations to Braze" "Alternative" "Integration"
        c4tp = mmp.msp -> bms.asp "Channel 4 to PFT token" "Mule" "Integration"
        crbt = dap.as -> dap.dcri "Clean Room (Brandm4tch) to Audience Segmentation" "Alternative" "Integration"
        crbt2 = dap.as -> dap.dcrs "Clean Room (Brandm4tch) to Audience Segmentation" "Alternative" "Integration"
        ctsfXX = cp.fsh -> cp.stel "Clearcast to Stellar for Copy Clearance Information" "Mule" "Integration"
        ctf = cp.fsh -> bms.cmt "CMT to Freewheel" "Alternative" "Integration"
        ctp = bms.pira -> bms.cmt "CMT to Pirate" "Mule" "Integration"
        ctpc = bms.cmt -> bms.pcX "CMT to Promo Create" "Alternative" "Integration"
        ctpo = mp.po -> bms.cmt "CMT to Promo Optimiser" "Alternative" "Integration"
        ccii = rsp.come -> fsp.ebs "Comet C4I Invoice Interface" "Alternative" "Integration"
        cffli = fsp.ebs -> rsp.come "Comet FFL Invoice Interface" "Automate" "Integration"
        cai = bms.pira -> rsp.pris "Contract & Agreement info" "Mule" "Integration"
        caiX = csp.pcc -> rsp.pap "Contract/Prog & Agreement info" "Alternative" "Integration"
        cpdt = bms.pira -> sbs.anda "Contracts PAC data to Anda" "Alternative" "Integration"
        cctf = cp.cc -> cp.fsh "Copy Central to Freewheel" "Alternative" "Integration"
        ccts = cp.cc -> cp.stel "Copy Central to Stellar" "Alternative" "Integration"
        ctll = psp.tlh -> psp.ll "Cornerstone to LinkedIn Learning" "Alternative" "Integration"
        epct = psp.fes -> fsp.ebs "EBS project codes to FES" "Alternative" "Integration"
        et4f = psp.4peo -> fsp.ebs "EBS to 4People for Employees" "Alternative" "Integration"
        ebstrd = fsp.ebs -> fsp.bsw "EBS to Basware for Reference & Transactional data" "Alternative" "Integration"
        etcf = rsp.come -> fsp.ebs "EBS to Comet for Cash Receipts" "SFTP" "Integration"
        ebsmc = fsp.msc -> fsp.ebs "EBS to Mastercard for Employee credit card transactions" "Alternative" "Integration"
        ebspir = fsp.ebs -> rsp.come "EBS to Pirate (Comet Flim4)" "Automate, SFTP" "Integration"
        ebsstr = fsp.ebs -> cp.stel "EBS to Stellar Daily exchange rate (in) Invoices (out)" "Alternative" "Integration"
        ebscex = fsp.ebs -> cp.stel "EBS to Stellar for Currency Exchange" "SFTP" "Integration"
        ebplan = fsp.ebs -> fsp.wda "eBusiness to Planning" "Alternative" "Integration"
        e4ti = dap.dcri -> dap.cedw "EDW 4 to Infosum" "Alternative" "Integration"
        emcs = dap.df -> dap.cedw "EDW Marketing Campaign Snapshots to Microsoft Data Fabric" "Alternative" "Integration"
        emct = dap.df -> dap.cedw "EDW Marketing Campaign to Microsoft Data Fabric" "Alternative" "Integration"
        esit = mp.braz -> dap.cedw "EDW Streaming Identity to Braze" "Alternative" "Integration"
        etdf = dap.df -> dap.cedw "EDW to  Data Fabric - Spots data" "Alternative" "Integration"
        etap = dap.cedw -> rsp.pap "EDW to Artist Payment Systems (Pirate)" "Alternative" "Integration"
        etb = mp.braz -> dap.cedw "EDW to Braze" "Alternative" "Integration"
        etm- = dap.cedw -> dap.as "EDW to Mediarithmics - Instream Promo Control Audience Upload" "Alternative" "Integration"
        etm-X = dap.as -> dap.cedw "EDW to Mediarithmics - Streaming User Data" "Alternative" "Integration"
        ett- = vsp.thin -> dap.cedw "EDW to ThinkAnalytics - Viewers" "Alternative" "Integration"
        etdfX = dap.cedw -> bms.pira "EDW TX data feed to Pirate" "Alternative" "Integration"
        fgl = bms.pira -> fsp.ebs "Failed GL lines" "Alternative" "Integration"
        fvte = cp.fsh -> dap.cedw "Feewheel v4logs to EDW" "Alternative" "Integration"
        faebs = fsp.ebs -> fsp.faf "Finance Approval to E-Business Suite" "Alternative" "Integration"
        ffsf = cp.fsh -> dap.cedw "Freewheel from Stellar for Forecast data of VOD Campaign" "Mule" "Integration"
        ffsf2 = cp.fsh -> cp.stel "Freewheel from Stellar for Forecast data of VOD Campaign" "Mule" "Integration"
        fltm = cp.fsh -> dap.df "Freewheel logs to Microsoft Data Fabric" "Alternative" "Integration"
        ftie = dap.dcri -> cp.fsh "Freewheel to Infosum (Exposed Campaign Users Attribution)" "Alternative" "Integration"
        ftsf = cp.fsh -> cp.stel "Freewheel to Stellar for Freewheel reference data changes API" "Alternative" "Integration"
        ftsv = cp.fsh -> cp.stel "Freewheel to Stellar VoD Views for Commercial, Sponsorship and Promotions" "SFTP" "Integration"
        frtp = mmp.msp -> bms.prta "From RedBee to Pirate ASRUN" "Mule" "Integration"
        fstp = cp.stel -> bms.pira "From Stellar to Pirate for Commercial Registrations" "Alternative" "Integration"
        idtc = bms.bynd -> vsp.c4sl "Image DAM to C4S" "Alternative" "Integration"
        imcf = rsp.soun -> bms.pira "Interstial music cuesheets from Soundmouse to Pirate" "Automate, SFTP" "Integration"
        icnf = rsp.pris -> fsp.ebs "Invoice/credit note for Royalties" "Automate" "Integration"
        lspp = bms.pira -> vsp.c4sl "Logging Sheets & Programme Parts" "Alternative" "Integration"
        lcfl = lpp.lsp -> mmp.ppsp "LSP Contribution Feed ( Line Record)" "Alternative" "Integration"
        lmfd = lpp.lsp -> mmp.msp "LSP Media File Delivery" "Alternative" "Integration"
        lm = lpp.lsp -> bms.osp "LSP Multicast" "Alternative" "Integration"
        lsto = bms.osp -> lpp.lsp "LSP Simulcast to OSLP" "Alternative" "Integration"
        ltpa = bms.pira -> lpp.lsp "LSP to Pirate Asruns" "Alternative" "Integration"
        mtbb = bms.bynd -> sp.mod "MediaGenix to Bynder Brand" "Alternative" "Integration"
        mtfp = cp.fsh -> sp.mod "MediaGenix to FreeWheel Programme Info" "Alternative" "Integration"
        mtgc = bms.grac -> sp.mod "MediaGenix to Gracenote Channel 4 VoD Catalogue" "Mule" "Integration"
        mtmb = sp.mod -> sp.mod "MediaGenix to MediaGenix BARB VOD Schedule Integration" "Alternative" "Integration"
        mtpe = bms.pira -> sp.mod "MediaGenix to Pirate EPG Content Warnings" "Mule" "Integration"
        mttc = vsp.thin -> sp.mod "MediaGenix to ThinkAnalytics Channel 4 VoD Catalogue" "Mule" "Integration"
        mtbf = mp.braz -> dap.as "Mediarithmics to Braze for Marketing Segments" "Alternative" "Integration"
        mtff = cp.fsh -> dap.as "Mediarithmics to Freewheel for ALA segments" "Alternative" "Integration"
        mtic = dap.dcri -> dap.as "Mediarithmics to Infosum (Control Group attribution)" "Alternative" "Integration"
        mvrt = mmp.msp -> sp.mod "MoD  VoD Request to PFT" "Alternative" "Integration"
        msdt = vsp.sm -> dap.cedw "MPP Subscriber data to EDW" "Alternative" "Integration"
        mcra = mmp.msp -> bms.asp "MSP Content Request API" "Alternative" "Integration"
        mcra2 = mmp.msp -> lpp.lsp "MSP Content Request API" "Alternative" "Integration"
        mcra3 = mmp.msp -> bms.osp "MSP Content Request API" "Alternative" "Integration"
        mcra4 = mmp.msp -> mmp.ppsp "MSP Content Request API" "Alternative" "Integration"
        mmvf = mmp.msp -> bms.osp "MSP Master Video Files to OLSP" "Alternative" "Integration"
        mmfd = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired BBC Studios" "Alternative" "Integration"
        mmfdX = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired Fox/Disney" "Alternative" "Integration"
        mmfdXX = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired Generic" "Alternative" "Integration"
        mmfdXXX = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired Sony" "Alternative" "Integration"
        mmfdXXXX = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired Turner" "Alternative" "Integration"
        mmfdXXXXX = mmp.msp -> csp.dist "MSP Media File Delivery - Acquired Warner" "Alternative" "Integration"
        mmfdXXXXXX = mmp.msp -> cp.cari "MSP Media File Delivery - Commercials" "Alternative" "Integration"
        mmfd2 = mmp.msp -> cp.cc "MSP Media File Delivery - Commercials" "Alternative" "Integration"
        mmfdXXXXXXX = mmp.msp -> csp.pc "MSP Media File Delivery - Commissioned Programmes" "Alternative" "Integration"
        mmfdXXXXXXXX = mmp.msp -> csp.pc "MSP Media File Delivery - Interstitials" "Alternative" "Integration"
        mmfdXXXXXXXXX = mmp.msp -> lpp.lsp "MSP Media File Delivery - LSP Video Recordings" "Alternative" "Integration"
        mmfdXXXXXXXXXX = mmp.msp -> lpp.lsp "MSP Media File Delivery - LSP Voiceover Recordings" "Alternative" "Integration"
        mmfdXXXXXXXXXXX = mmp.msp -> cp.stel "MSP Media File Delivery - MB Media to Stellar for Long Form teleshopping" "SFTP" "Integration"
        mmfdXXXXXXXXXXXX = mmp.msp -> cp.cari "MSP Media File Delivery - Music Videos" "Alternative" "Integration"
        mmfdXXXXXXXXXXXXX = mmp.msp -> bms.asp "MSP Media File Delivery - Subtitles & Audio Description" "Alternative" "Integration"
        mmfdXXXXXXXXXXXXXX = mmp.msp -> bms.asp "MSP Media File Delivery - Supertrusted" "Alternative" "Integration"
        mmfd2X = mmp.msp -> mmp.ppsp "MSP Media File Delivery - Supertrusted" "Alternative" "Integration"
        mpvb = mmp.msp -> mmp.pvb "MSP Pirate Video Browse API" "Alternative" "Integration"
        mpvbX = mmp.msp -> mmp.pvb "MSP Pirate Video Browse File Hosting" "Alternative" "Integration"
        msfr = mmp.msp -> bms.pira "MSP Schedule File Receipt" "Alternative" "Integration"
        mti = mmp.msp -> mmp.uv "MSP Tape Ingest" "Alternative" "Integration"
        mtp = mmp.pmm -> mmp.msp "MSP to Pirate" "Mule" "Integration"
        mtrt = mmp.rta -> mmp.msp "MSP to Ready to Air" "Alternative" "Integration"
        mts = rsp.soun -> mmp.msp "MSP to Soundmouse" "Alternative" "Integration"
        mtc4 = mmp.msp -> bms.pira "MSPs to Channel 4 DFS folders" "Mule" "Integration"
        nos = bms.pc -> rsp.prrs "Name of Supplier" "Alternative" "Integration"
        ntn = rsp.pris -> bms.pira "New transmitted notifications" "Alternative" "Integration"
        ebssbi = fsp.ebs -> fsp.ebs "Oracle EBS to SplashBI (Oracle eBS Schema)" "Alternative" "Integration"
        ebssbi2 = fsp.ebs -> fsp.sbi "Oracle EBS to SplashBI (Oracle eBS Schema)" "Alternative" "Integration"
        oscn = fsp.ebs -> rsp.prrs "Oracle suppliers contact names" "Alternative" "Integration"
        oatax = fsp.ebs -> fsp.atax "Oracle to AlphaTax" "Alternative" "Integration"
        opisx = fsp.ebs -> fsp.ebs "Oracle to PublicIS XML Invoice feed" "Mule" "Integration"
        otunx = fsp.ebs -> fsp.tgn "Oracle to Tungsten XML Invoice feed" "Mule" "Integration"
        pfpf = rsp.soun -> bms.pira "PAC form PDFs from Soundmouse to Pirate" "Automate, SFTP" "Integration"
        pfxf = rsp.soun -> bms.pira "PAC form XMLs from Soundmouse to Pirate" "Automate, SFTP" "Integration"
        pmfs = mmp.msp -> cp.stel "Peach Media from Stellar for Attribution files" "Mule" "Integration"
        patv = bms.pira -> sp.pass "Pirate A55 to VMS (ex Optimum)" "Mule" "Integration"
        patv2 = bms.pira -> sp.pepl "Pirate A55 to VMS (ex Optimum)" "Mule" "Integration"
        patv3 = bms.pira -> bms.pvms "Pirate A55 to VMS (ex Optimum)" "Mule" "Integration"
        pass = bms.pira -> vsp.c4sl "Pirate Advance Scheduling System to C4S" "Alternative" "Integration"
        pctc = bms.pira -> vsp.c4sl "Pirate Certification to C4S" "Alternative" "Integration"
        pctb = bms.bynd -> bms.pcgs "Pirate CGS to Bynder" "Mule" "Integration"
        pctf = cp.fsh -> bms.pcgs "Pirate CGS to Freewheel" "Mule" "Integration"
        pctm = mmp.msp -> bms.pcgs "Pirate CGS to MSP for VPS origin" "Mule" "Integration"
        pcts = bms.pcgs -> cp.stel "Pirate CGS to Stellar for Programme and Platform information" "Alternative" "Integration"
        pctfX = cp.fsh -> bms.pcgs "Pirate Creatives to Freewheel" "Mule" "Integration"
        pffr = bms.pira -> bms.asp "Pirate fetch from RedBee for Subtitles" "Mule" "Integration"
        pirgl = fsp.ebs -> rsp.come "Pirate GL posted Transactions" "Alternative" "Integration"
        ppta = mmp.msp -> sp.ppps "Pirate PPS to AWS S3 Bucket" "Mule" "Integration"
        ppit = cp.fsh -> bms.pcgs "Pirate Programme Info to FreeWheel" "Mule" "Integration"
        prms = bms.pira -> vsp.c4sl "Pirate Rights Management System to C4S" "Alternative" "Integration"
        prdt = rmp.prms -> dap.cedw "PIRATE RMS data to  Oracle EDW" "Alternative" "Integration"
        pta = lpp.ac -> sp.mod "Pirate To Amagi" "Alternative" "Integration"
        ptbf = sp.mod -> bms.pira "Pirate to BeBanjo for Catalogue Assets" "Mule" "Integration"
        ptbf2 = sp.mod -> csp.pp "Pirate to BeBanjo for Catalogue Assets" "Mule" "Integration"
        ptbfX = sp.mod -> bms.pira "Pirate to BeBanjo for Linear Scheduling" "Mule" "Integration"
        ptbf2X = sp.mod -> sp.pass "Pirate to BeBanjo for Linear Scheduling" "Mule" "Integration"
        ptbfXX = sp.mod -> bms.pira "Pirate to BeBanjo for Media Assets" "Mule" "Integration"
        ptbf2XX = sp.mod -> mmp.pmm "Pirate to BeBanjo for Media Assets" "Mule" "Integration"
        ptbfXXX = sp.mod -> rmp.prms "Pirate to BeBanjo for Rights" "Mule" "Integration"
        ptbfXXXX = sp.mod -> bms.pira "Pirate to BeBanjo for Segment" "Mule" "Integration"
        ptbd = mmp.pmm -> bms.bynd "Pirate to Bynder data flow" "Alternative" "Integration"
        ptcp = mmp.msp -> mmp.pvb "Pirate to Clear (Prime Focus Technology)" "Mule" "Integration"
        ptcs = bms.pira -> mmp.msp "Pirate to Compliance Service" "Alternative" "Integration"
        ptdf = bms.et -> bms.pira "Pirate to DUK Freesat VOD publication" "Alternative" "Integration"
        ptdfX = bms.et -> bms.pira "Pirate to DUK Freeview VOD publication" "Alternative" "Integration"
        pte = bms.pira -> fsp.ebs "Pirate to EBS" "Alternative" "Integration"
        ptes = bms.pira -> mmp.msp "Pirate to Editorial Service" "Alternative" "Integration"
        ptgc = bms.pira -> bms.grac "Pirate to Gracenote Channel 4 channel EPGs" "Mule" "Integration"
        ptgm = bms.pira -> bms.grac "Pirate to Gracenote music channel EPGs" "Alternative" "Integration"
        ptk = sp.ppps -> dap.barb "Pirate to Kantar" "Mule" "Integration"
        ptkf = dap.barb -> mmp.pmm "Pirate to Kantar for Assets" "Mule" "Integration"
        ptl = lpp.lsp -> bms.pira "Pirate To LSP" "Alternative" "Integration"
        ptl2 = lpp.lsp -> cp.stel "Pirate To LSP" "Alternative" "Integration"
        ptmo = sp.mod -> bms.pira "Pirate to MediaGenix On-Demand Content Metadata" "Mule" "Integration"
        ptmo2 = sp.mod -> sp.pepl "Pirate to MediaGenix On-Demand Content Metadata" "Mule" "Integration"
        ptpo = sp.ppps -> mp.po "Pirate To Promo Optimser" "Mule" "Integration"
        ptss = lpp.lsp -> sp.ppps "Pirate to Schedule Service" "Alternative" "Integration"
        pts = bms.pira -> cp.stel "Pirate to Stellar" "Alternative" "Integration"
        ptsf = sp.pitt -> cp.stel "Pirate to Stellar for ASRUN commercial" "Automate, SFTP" "Integration"
        ptsfX = sp.ppps -> cp.stel "Pirate to Stellar for ASRUN Non-commercial" "Alternative" "Integration"
        ptsfXX = sp.ppps -> cp.stel "Pirate to Stellar for Schedule & Event timings" "Alternative" "Integration"
        ptsu = cp.stel -> cp.ap "Pirate to Stellar update for Brand" "Mule" "Integration"
        pvtr = mmp.msp -> bms.ptis "Pirate VPS to (RedBee, M2A, PFT, NLDR)" "Mule" "Integration"
        pvts = mmp.msp -> mmp.pmm "Pirate VPS to S3" "Mule" "Integration"
        pwft = bms.pira -> cp.stel "Pirate Weekly Forecast to Stellar" "Automate" "Integration"
        pvtc = rsp.prrs -> rmp.prms "Portal view to capture Royalty Producer shares" "Alternative" "Integration"
        pdfp = rsp.soun -> bms.pira "Post-TX data from Pirate to Soundmouse" "Automate, SFTP" "Integration"
        pcf = mmp.ppsp -> lpp.lsp "PPSP Contribution Feed" "Alternative" "Integration"
        pmfd = mmp.ppsp -> mmp.msp "PPSP Media File Delivery" "Alternative" "Integration"
        pdfpX = rsp.soun -> bms.pira "Pre-TX data from Pirate to Soundmouse" "Automate, SFTP" "Integration"
        plcd = cp.stel -> dap.cedw "Processes linear campaign data, including agreements, breaks and spots" "Alternative" "Integration"
        prte = rsp.come -> fsp.ebs "Producer Reporting to EBS" "Automate" "Integration"
        proebs = fsp.ebs -> rsp.come "Producer Reporting to Oracle eBusiness Suite " "Alternative" "Integration"
        pptp = bms.ppp -> csp.pcc "Producers Portal to Pirate for Ed Spec Diversity info" "Mule" "Integration"
        pasm = rsp.soun -> bms.pira "Programme and social media clip music cuesheets from Soundmouse to Pirate" "Automate, SFTP" "Integration"
        ppi = fsp.ebs -> bms.pira "programme Payments Interface" "Alternative" "Integration"
        pctmX = sp.mod -> bms.pcX "Promo Create To Movida" "Mule" "Integration"
        pctp = bms.pira -> bms.pcX "Promo Create To Pirate" "Mule" "Integration"
        potp = bms.pira -> mp.po "Promo Optimiser to Pirate" "Mule" "Integration"
        rtat = lpp.lsp -> vsp.c4sl "Real Time As-Run to ALL 4" "Alternative" "Integration"
        rdfp = bms.pira -> rsp.pris "Recoupment/Advances data from Programme Finance Committee form" "Alternative" "Integration"
        rad = csp.pcc -> rsp.pap "Repeat agreement data" "Alternative" "Integration"
        rtc7 = rmp.prms -> bms.c7t "Rights to C4 7A Titles" "Alternative" "Integration"
        rswe = bms.pc -> rsp.prrs "Royalty Statement (welcome Email)" "Alternative" "Integration"
        scfmd = fsp.ebs -> cp.sc "Sales CRM to Finance ERP - Customer Master Data" "Mule" "Integration"
        scfic = fsp.ebs -> cp.sc "Sales CRM to Finance ERP - Invoice Creation" "Mule" "Integration"
        se = rsp.come -> rsp.pap "Sales Entry" "Alternative" "Integration"
        str = lpp.lsp -> bms.pira "SSAPI to RTAR" "Mule" "Integration"
        sdfp = rsp.prrs -> fsp.bsw "Statement data (for pre-approved PO's)" "Alternative" "Integration"
        scdt = cp.ap -> cp.stel "Stellar commercial data to Agencies" "Mule" "Integration"
        stap = cp.ap -> cp.stel "Stellar to Agency Portal &  K2 for programme data" "Mule" "Integration"
        stapX = cp.ap -> cp.stel "Stellar to Agency Portal for CB and PIB" "Alternative" "Integration"
        strebs = fsp.ebs -> cp.stel "Stellar to EBS for Sales Orders & New Customers" "Alternative" "Integration"
        ste- = cp.stel -> dap.cedw "STELLAR to EDW - Campaign Position and Deal Position at Group Level" "Alternative" "Integration"
        ste-X = cp.stel -> dap.cedw "STELLAR to EDW - Data to be used in PIB & CB reporting" "Alternative" "Integration"
        ste-XX = cp.stel -> dap.cedw "STELLAR to EDW - Processes Base Price Group data" "Alternative" "Integration"
        ste-XXX = cp.stel -> dap.cedw "STELLAR to EDW - ROI Sponsorship Revenue values per transmission" "Alternative" "Integration"
        ste-XXXX = cp.stel -> dap.cedw "STELLAR to EDW - Sponsorship campaign data" "Alternative" "Integration"
        stef = cp.stel -> dap.cedw "Stellar to EDW for ROI calculation on Channel sets" "Alternative" "Integration"
        stff = cp.fsh -> cp.stel "Stellar to Freewheel for Agencies, Brand, Deals and Campaigns" "Mule" "Integration"
        stna = dap.barb -> cp.stel "Stellar to NIELSEN and BARB for post transmission Spot Log" "SFTP" "Integration"
        stof2 = cp.stel -> fsp.ebs "Stellar to Oracle Financials about Agency financial exposure" "Alternative" "Integration"
        stof1 = cp.stel -> fsp.ebs "Stellar to Oracle Financials on Credit Policy" "Alternative" "Integration"
        stof = cp.stel -> fsp.ebs "Stellar to Oracle Financials on invoicing" "Alternative" "Integration"
        stpm = mmp.msp -> cp.stel "Stellar to Peach Media for Spot Plus files" "Mule" "Integration"
        stpf = sp.ppps -> cp.stel "Stellar to Pirate for Commercial break pattern information" "Alternative" "Integration"
        stpfX = cp.stel -> sp.ppps "Stellar to Pirate for Commercial Copy Registrations" "SFTP" "Integration"
        stpfXX = sp.pitt -> cp.stel "Stellar to Pirate for commercial playlist" "SFTP" "Integration"
        stpfXXX = cp.stel -> sp.ppps "Stellar to Pirate for Product placement indicator" "Alternative" "Integration"
        stpfXXXX = cp.stel -> sp.ppps "Stellar to Pirate for Promotional Campaigns" "Alternative" "Integration"
        stpfXXXXX = cp.stel -> sp.ppps "Stellar to Pirate for Promotions Copy Registrations" "Alternative" "Integration"
        stpfXXXXXX = cp.stel -> sp.ppps "Stellar to Pirate for Sponsorship Campaign" "Alternative" "Integration"
        stpfXXXXXXX = cp.stel -> sp.ppps "Stellar to Pirate for Sponsorship Clocknumbers or Copy" "Alternative" "Integration"
        stpfXXXXXXXX = cp.stel -> sp.ppps "Stellar to Pirate for Sponsorship Events" "Alternative" "Integration"
        stpfXXXXXXXXX = cp.stel -> sp.ppps "Stellar to Pirate for Sponsorship Events for Partners" "SFTP" "Integration"
        stpfXXXXXXXXXX = cp.stel -> sp.ppps "Stellar to Pirate for Trail patterns" "Alternative" "Integration"
        stuf = mmp.msp -> cp.stel "Stellar to UKTV for Ad Certification" "SFTP" "Integration"
        stufX = mmp.msp -> cp.stel "Stellar to UKTV for Commercial Copy Registrations" "SFTP" "Integration"
        scte = vsp.c4sl -> dap.cedw "Streaming Consent to EDW" "Alternative" "Integration"
        sbde = fsp.ebs -> rsp.pap "Supplier Bank Details Exist" "Automate" "Integration"
        sffp = rsp.prrs -> dap.cedw "Supplier fields from PIRATE to EDW(Redshift) EDW(Oracle)" "Alternative" "Integration"
        supinf = fsp.ebs -> rsp.pris "Supplier Information" "Alternative" "Integration"
        suprec = fsp.ebs -> rsp.pap "Supplier Records" "Alternative" "Integration"
        ttbs = rsp.ted -> dap.cedw "Ted tables batch synchronisation to Coeus Redshift" "Alternative" "Integration"
        ttn = rsp.soun -> bms.pira "Ted to Neo" "Automate, SFTP" "Integration"
        tts = rsp.soun -> bms.pira "Ted to Silvermouse" "Automate, SFTP" "Integration"
        ttc- = vsp.thin -> vsp.c4sl "ThinkAnalytics to C4S - Recommendation" "Alternative" "Integration"
        tsfp = dap.barb -> sp.pass "TX Schedule from PIRATE to BARB" "Alternative" "Integration"
        vptc = bms.osp -> vsp.c4sl "Video Pipeline to C4S" "Alternative" "Integration"
        vtcs = mmp.msp -> bms.ppc "VisionCloud to Compliance Service" "Mule" "Integration"
        vvd = dap.cedw -> rsp.prrs "VOD Views Data" "Alternative" "Integration"
        waad = dap.wa -> dap.cedw "Web Analytics (AA) data to EDW" "Alternative" "Integration"
        wdsbi = fsp.wda -> fsp.ebs "Workday Adaptive to SplashBI (Oracle eBS Schema)" "Mule" "Integration"
        wdsbi2 = fsp.wda -> fsp.sbi "Workday Adaptive to SplashBI (Oracle eBS Schema)" "Mule" "Integration"
        ytf = vsp.yosp -> cp.fsh "YoSpace to Freewheel" "Alternative" "Integration"
        
    }
    
    views {
        
        terminology {
            person "Team"
            softwareSystem "Platform"
            container "Application"
        }
        
        themes https://raw.githubusercontent.com/synchrotron/c4c4/main/assets/c4-default-theme.json
        
        branding {
            logo https://raw.githubusercontent.com/synchrotron/c4c4/main/assets/4-logo-black.png
            font "4Text" https://raw.githubusercontent.com/synchrotron/c4c4/main/assets/4Text-Regular.ttf
        }
    }
}