workspace "Channel 4 Core" "Enterprise Systems - Generated from LeanIX" {

    !identifiers flat

    model {
    
        archetypes {
            application = container
        }
        
        /* ============================================================
           ORGANISATIONS / TEAMS (from LeanIX UserGroups)
           ============================================================ */
        
        c4cc = person "Client Sales & Engagement" ""
        c4ci = person "Partnerships" ""
        c4cs = person "Sales Operations" "Sales Operations handle the content supply chain for commercial content and plan placements withi..."
        ea = person "Agency" ""
        c4ct = person "Broadcast Technology" ""
        c4ca = person "AV" ""
        c4csX = person "Ad Tech" ""
        c4csXX = person "Campaign" ""
        c4csXXX = person "Traffic" ""
        c4ctX = person "Trading" ""
        c4ccX = person "Presentation and Access Services" ""
        c4cf = person "Content Finance" ""
        c4mc = person "Communications" ""
        c4mm = person "Audience Integration" ""
        c4caX = person "Corporate Legal and Compliance" "Sub-team of Commercial Affairs that handle legal and compliance for all our content. Assigning ce..."
        c4ccXX = person "Content Delivery" ""
        c4m4 = person "4Studio" ""
        c4mp = person "Product" ""
        epp = person "Partner Platform" "User group to describe partner platforms such as DUK, Youview or Sky"
        c4ccXXX = person "Programme Information" "Programme Information provide distinctive, top quality, informative copy with the relevant tone o..."
        c4ccXXXX = person "Commissioning Office" ""
        ep = person "Producer" ""
        c4caXX = person "Commercial Affairs" "The commercial affairs teams handle entitlements and agreements, including rights) with out conte..."
        c4ccXXXXX = person "Content Strategy & Planning" "The Content Strategy team plans exhibition windows for our content on linear and non-linear using..."
        c4ccXXXXXX = person "Youth and Digital" ""
        c4ccXXXXXXX = person "Content Management" "Technical and business team that handle content media supply chain."
        ccf = person "Finance" ""
        c4csXXXX = person "Strategy & Consumer Insight" ""
        c4mmX = person "Marketing" ""
        c4ciX = person "Innovation" ""
        c4ccXXXXXXXX = person "Daytime and Features" ""
        c4ccXXXXXXXXX = person "Drama" ""
        c4ccXXXXXXXXXX = person "Factual" ""
        c4ccXXXXXXXXXXX = person "Factual Entertainment" ""
        c4ccXXXXXXXXXXXX = person "News, Current Affairs & Sport" ""
        c4f4 = person "Film 4" ""
        c4caXXX = person "Business Affairs" ""
        c4ccXXXXXXXXXXXXX = person "Comedy" ""
        c4ccXXXXXXXXXXXXXX = person "Commissioning Operations" ""
        c4ccXXXXXXXXXXXXXXX = person "Entertainment" ""
        c4ccXXXXXXXXXXXXXXXX = person "Duty Desk" "Team that handles live content operations for our linear channels."
        c4cp = person "People" ""
        c4m = person "MVE" ""
        c4m4X = person "4Creative" "Creative Team that creates new content for Channel 4."
        c4c = person "Commercial" ""
        c4caXXXX = person "Production Finance" ""
        c4csXXXXX = person "Programmatic and Audience" ""
        c4csXXXXXX = person "Data Science" ""
        c4csXXXXXXX = person "Audience Research" ""
        c4ctXX = person "Technology" ""
        c4ciXX = person "Digital" ""
        c4mmXX = person "Digital Marketing" ""
        c4mpX = person "Insights" ""
        c4X = person "Channel 4" ""
        ccfrss = person "Shared Services" "Team responsible for any financial transactional incoming and outgoing payment processing. Typica..."
        c4mpXX = person "Consumer Product" ""
        c4mpXXX = person "Digital Marketing (Product)" ""
        c4ccXXXXXXXXXXXXXXXXX = person "Content & Commissioning" ""
        c4cX = person "Corporate" ""
        c4cpX = person "Employee Relations" ""
        c4ctXXX = person "Corporate Technology" ""
        c4cpXX = person "Learning and Development" ""
        c4cfX = person "Procurement" ""
        c4caXXXXX = person "Corporate Legal & Governance" ""
        ev = person "Viewer" ""
        c4mpXXXX = person "All 4 Editorial" ""
        c4mpXXXXX = person "Growth (Subscriptions)" ""
        c4cfXX = person "Facilities Management" ""

        /* ============================================================
           COMMERCIAL PLATFORM
           ============================================================ */
        
        cp = softwareSystem "Commercial Platform" "Platform from LeanIX" {
            
            ap = container "Agency Portal" "Empowering advertising agencies with their Channel4 campaign data." "Application"
            cari = container "Caria" "The platform on which UK & Irish airtime is traded, and upon which copy rotation instructions are..." "Application"
            cc = container "Copy Central" "Service that provides information about copy restrictions and/or certifications. Also known as Cl..." "Application"
            fsh = container "Freewheel Streaming Hub" "Freewheel Streaming Hub (aka MRM) is a software application that enables publishers and broadcast..." "Application"
            inno = container "Innovid" "Innovid is the only independent omni-channel advertising and analytics platform built for televis..." "Application"
            moat = container "Moat" "Moat enables measuring consumer attention across channels, devices, and platforms" "Application"
            sc = container "Sales CRM" "" "Application"
            stel = container "Stellar" "Channel4's Sales Order Processing System" "Application"
        }

        /* ============================================================
           CONTENT MANAGEMENT PLATFORM
           ============================================================ */
        
        cmp = softwareSystem "Content Management Platform" "The applications and components that support the media management and linear scheduling for our l..." {
            
            asp = container "Access Service Provider" "" "Application"
            acf = container "Acquired Cash Forecast" "For the management of cashflow for acquired content, this is all captured on a spreadsheet called..." "Application"
            bynd = container "Bynder" "Bynder is an AI-powered, SaaS DAM solution that allows brands to easily create, find and use thei..." "Application"
            c7t = container "C4 7A Titles" "Home grown system to schedule long form content on YouTube with workflow for Rights and Compliance." "Application"
            cmt = container "CMT" "Hosted by I2, CMT is a web-based tool with secure log-in credentials . The tool allows Long Term ..." "Application"
            dasd = container "DTT Audio & Signing Date prompts with peak stats (with RB amendments)" "Business Objects report Displays the total volume of transmitted content during a time period, an..." "Application"
            et = container "Everyone TV" "Everyone TV is the new name for Digital UK. [JV with UK PSB's] NOTE: This is NOT an Application E..." "Application"
            grac = container "Gracenote" "Gracenote is the world’s leading entertainment data and technology company. We power the top musi..." "Application"
            mod = container "MediaGenix On Demand" "BeBanjo Movida VOD Management system (Comprising of systems which schedule and manage transcode a..." "Application"
            olss = container "OFCOM Licensing Services-Online Services-MIDCOM" "This is the OFCOM platform used by our Access Services team to upload of our reporting to OFCOM." "Application"
            osp = container "OnLine Service Provider" "Provides capabilities for ingest, transformation, transcoding, encryption and delivery of VOD; li..." "Application"
            ol = container "Order list" "Setting a budget and its' allocations genres & channels. Existing commitments also captured. Targ..." "Application"
            pira = container "Pirate" "Pirate is a collection of applications used by various departments. Commercial affairs (business ..." "Application"
            p4ws = container "4Producers (Web Site)" "eCommissioning system. Allows C4 to engage with Production companies for Production companies to ..." "Application"
            pass = container "Advance Scheduling System" "The Advanced Scheduling System (A55) provides a view of a schedule for a specific channel and dat..." "Application"
            pbm = container "Brand Management" "An application where can create or update Pirate Brands. This enables the business to group toget..." "Application"
            pc = container "Companies" "This application allows users to create companies like production companies, studios etc" "Application"
            pcgs = container "Content Generation System" "Generates the required detailed metadata required for each target platform and sends the appropri..." "Application"
            pcps = container "Content Planning System" "VOD Scheduling" "Application"
            pdap = container "Director and Producer Reporting System" "DPRS Transmission/Sales Report This report works in various stages: 1. A list of all contract num..." "Application"
            pfas = container "Film Advanced Scheduling" "Manages the film scheduling scenarios based on deals purchased" "Application"
            pge = container "General Enquiry" "Contains query functionality and several reports that can be run based on a broad range of topics..." "Application"
            pip = container "Interface Payments" "Maintenance tables for 1. Nominal accounts – specifying what codes are valid 2. Specifying which ..." "Application"
            pitt = container "Interface To Transmission Systems" "ITS prepares final schedules for Playout systems. It uses Programme schedules generated from PPS ..." "Application"
            pmam = container "Management Account Maintenance" "Maintenance of reference data related to Management Accounts (Programme Finance)  Not used much,..." "Application"
            pmm = container "Media Management" "Video browse can also be launched from this application" "Application"
            pofg = container "OFCOM File Generator" "Review one or more channels for their compliance with statutory commercial minutage regulations. ..." "Application"
            ppps = container "Presentation Planning System" "Manages the detailed channel schedules with all the relevant transmission content required for br..." "Application"
            pppsX = container "Presentation Planning System - PPS.NET" "This is the .NET version of PPS NOTE: We need to create all VOD processes and link one to this ap..." "Application"
            ppp = container "Producers Portal" "An app which allows C4 to engage with Production companies for Production companies to fill in th..." "Application"
            ppc = container "Programme Certification" "Programme Certification gives the users of the system the ability look at the assets when they ar..." "Application"
            prta = container "Real Time As-Run 2" "Provides real-time playout updates to Pirate systems." "Application"
            pswo = container "Stock Write Off" "Channel 4 commission or purchase programmes (stock) to be consumed by the schedule using annual t..." "Application"
            psfv = container "Subtitle File Viewer" "Provides a view over the content of subtitles and the ability to quickly search for bad-language ..." "Application"
            ptis = container "Transcode Initiation Service" "TIS2 is the back-end engine of the VoD system, running background jobs ranging from asset synchro..." "Application"
            pvb = container "Video Browse" "Video Browse is a client-side.NET application that is part of the Pirate domain. It provides user..." "Application"
            pve = container "Viewer Enquiry" "Viewing the logged calls made by viewers regarding transmitted programmes. EXE name: VE" "Application"
            pvms = container "VOD Management System (VMS)" "" "Application"
            pvma = container "VoD Material Allocation" "VoD Material Allocation is small module inside Media Management. This module used by Programme Ma..." "Application"
            pvt = container "VOD Tracker" "Support tool for monitoring VOD systems and workflows" "Application"
            pt = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" "Application"
            pcX = container "Promo Create" "Hosted by I2, CMT is a web-based tool with secure log-in credentials . The tool allows Long Term ..." "Application"
            scf = container "Sky Curated Feeds" "Web application designed to create ordered curated lists for presentation on Sky UVP/VRP platforms" "Application"
            soun = container "Soundmouse" "Representation of Soundmouse as company. Covers all SaaS products offered by Soundmouse: Soundmou..." "Application"
            spap = container "Soundmouse Pre-TX and Post-TX Exporter" "Creates both Pre-TX and Post-TX export files to Soundmouse for music reporting and production rep..." "Application"
            spri = container "Sprinklr" "Sprinklr is a social media management platform that enables enterprise brands to connect with cus..." "Application"
            ssfa = container "Subtitling Sep FLS and Teletext with Subtotals (with Ray Amendments)" "Business Objects Report 'Subtitling Sep FLS and Teletext with Subtotals (with Ray Amendments)' - ..." "Application"
            tb = container "The Bible" "The bible is a host of information related to the programme idea, such as the programme descripti..." "Application"
            typ = container "Three Year Plan" "" "Application"
        }

        /* ============================================================
           CONTENT SOURCING PLATFORM
           ============================================================ */
        
        csp = softwareSystem "Content Sourcing Platform" "Platform from LeanIX" {
            
            crmc = container "Customer Relationship Manager  (Content)" "A system used by the commissioning dept to track and manage programme ideas from pitch to greenlight" "Application"
            dist = container "Distributor" "Supplier of acquired content e.g. a US Studio" "Application"
            pasc = container "Acquisition Stock Control" "A Read-only/Live reporting tool, allowing users to track stock usage (available, scheduled, used)..." "Application"
            pcf = container "Cashflow Forecasting" "Forecasting tool for managing cash, when are production companies actually going to be paid compa..." "Application"
            pcc = container "Commissioning Cycle" "Manages the agreements of commissioned content." "Application"
            pp = container "Programmes" "" "Application"
            ppX = container "Purchases" "" "Application"
            pcXX = container "Production Company" "Supplier of commissioned content e.g. All 3 Media NOTE: NOT an application" "Application"
        }

        /* ============================================================
           DATA AND ANALYTICS PLATFORM
           ============================================================ */
        
        daap = softwareSystem "Data and Analytics Platform" "An extensive Massive Parallel Processing (MPP) platform designed for analytics tasks, which inclu..." {
            
            as = container "Audience Segmentation" "Enables publishers and broadcasters to grow and retain audiences and increase monetisation for a ..." "Application"
            barb = container "BARB" "Founded by the major organisations in the UK television and advertising industry, BARB is respons..." "Application"
            bor = container "Business Objects Reporting" "This application represents all Business Object reports generated by BI team and are read by busi..." "Application"
            cedw = container "Enterprise Data Warehouse" "Data Warehouse application used as a host of analytics data in a star schema or a columnar databa..." "Application"
            c4 = container "Core 4" "https://www.core4.channel4.com/hub Core4 is Channel 4's quantitative insight community, made up o..." "Application"
            dcri = container "Data Clean Room (InfoSum)" "A data platform with a vision to connect the world’s data without ever sharing it – by developing..." "Application"
            dcrs = container "Data Clean Room (Snowflake)" "A data platform with a vision to connect the world’s data without ever sharing it – by developing..." "Application"
            df = container "Data Fabric" "Data Fabric is an innovative approach designed to simplify and streamline data management across ..." "Application"
            tabl = container "Tableau" "Tableau is a data visualization tool used in the Business Intelligence Industry. It helps in simp..." "Application"
            wa = container "Web Analytics" "Web Analytics software used by M&VE for All 4 & Online Services Adobe Analytics is the solution f..." "Application"
        }

        /* ============================================================
           FINANCE SYSTEMS PLATFORM
           ============================================================ */
        
        fsp = softwareSystem "Finance Systems Platform" "Platform from LeanIX" {
            
            atax = container "Alphatax" "Corporation tax compliance software, providing complete control over the preparation and manageme..." "Application"
            bbp = container "Barclays Banking Portal" "Barclays Online platform used to transact FX deals. File Gateway is a host to host connectivity p..." "Application"
            bdn = container "Barclays.Net" "Barclays service used to download statements." "Application"
            bsw = container "Basware" "Enterprise software for financial processes, purchase to pay and financial management. Manage Inv..." "Application"
            cmx = container "Cachematrix" "SaaS solution for cash management" "Application"
            ebs = container "E-Business Suite" "Channel4 Oracle E-business Suite application used in Finance department for Accounts, Cash and As..." "Application"
            faf = container "Finance Approval Form" "" "Application"
            msc = container "Mastercard" "" "Application"
            odf = container "Oracle eBS Excel data files" "These are a collection of manually generated .xslx files out of Oracle e-Business that contain va..." "Application"
            pjc = container "Project Codes" "App used to generate project codes which are used in Oracle and across Channel 4." "Application"
            sov = container "Sovos" "Sovos helps in digital transformation of tax, with complete, connected offerings for tax determin..." "Application"
            sbi = container "SplashBI" "SplashBI is an all-in-one framework for visualising, reporting and analysing data." "Application"
            tgn = container "Tungsten Network" "Tungsten provide a multiple distribution channel service to a single stream invoice feed." "Application"
            wda = container "Workday Adaptive" "Workday Adaptive is Channel 4 Finance's Planning and Consolidation tool" "Application"
        }

        /* ============================================================
           LINEAR PLAYOUT PLATFORM
           ============================================================ */
        
        lpp = softwareSystem "Linear Playout Platform" "Platform from LeanIX" {
            
            ac = container "Amagi Cloudport" "<https://www.amagi.com/products/cloudport-cloud-playout>\ \ Amagi CLOUDPORT supports media ingest..." "Application"
            lsp = container "Linear Service Provider" "" "Application"
            pppsXX = container "Presentation Planning System" "Manages the detailed channel schedules with all the relevant transmission content required for br..." "Application"
            ptX = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" "Application"
            sp = container "Stargate Portal" "" "Application"
        }

        /* ============================================================
           MARKETING PLATFORM
           ============================================================ */
        
        mp = softwareSystem "Marketing Platform" "Platform from LeanIX" {
            
            braz = container "Braze" "Braze is a mobile marketing automation platform that provides a CRM and multichannel messaging su..." "Application"
            mpar = container "mParticle" "mParticle is a Customer Data Platform. It collects customer data once through secure APIs and SDK..." "Application"
            po = container "Promo Optimizer" "User-friendly TV promo scheduling tool. Leveraging advanced optimization and sequencing algorithm..." "Application"
        }

        /* ============================================================
           MEDIA MANAGEMENT PLATFORM
           ============================================================ */
        
        mmp = softwareSystem "Media Management Platform" "Platform from LeanIX" {
            
            awar = container "Awards" "Awards is a repository of all awards won by Channel 4 or where Channel 4 has been nominated. Plat..." "Application"
            msp = container "Media Service Provider" "Service provider for Digital Asset Management System" "Application"
            pmmX = container "Media Management" "Video browse can also be launched from this application" "Application"
            pvbX = container "Video Browse" "Video Browse is a client-side.NET application that is part of the Pirate domain. It provides user..." "Application"
            ptXX = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" "Application"
            ppsp = container "Post Production Service Provider" "Post production service is pre-integrated to MSP and has suites available in HFR. This work can b..." "Application"
            rta = container "Ready to Air" "Deliver pre-transmission & pre-release video to journalists securely and reliably, wherever they ..." "Application"
            uv = container "Underground Vault" "Team that handles live content operations for our linear channels.Controlled and secure location ..." "Application"
        }

        /* ============================================================
           PEOPLE SYSTEMS PLATFORM
           ============================================================ */
        
        psp = softwareSystem "People Systems Platform" "Platform from LeanIX" {
            
            4peo = container "4People" "4People is a cloud HR and people system that empowers mid-size organisations to effectively respo..." "Application"
            acti = container "ActivPay" "Actvipay is Channel 4's 3rd party payroll provider." "Application"
            acX = container "Alert Cascade" "Crisis event mass communication tool" "Application"
            bp = container "Benefits Portal" "" "Application"
            er = container "Executive Reporting" "Bespoke set of reports created in Power BI and served for the purpose of business reporting for t..." "Application"
            fes = container "Freelancer Engagement System" "HR system to request freelancers and bring them onboard. Freelancers submit timesheets via FES. O..." "Application"
            ll = container "LinkedIn Learning" "LinkedIn Learning offers video courses taught by industry experts in software, creative, and busi..." "Application"
            popp = container "Poppulo" "Internal communications Internal Communication, newsletter system. Used by internal comms. Integr..." "Application"
            tlh = container "The Learning Hive" "Cornerstone is a cloud-based learning and talent management solutions platform." "Application"
        }

        /* ============================================================
           RIGHTS MANAGEMENT PLATFORM
           ============================================================ */
        
        rmp = softwareSystem "Rights Management Platform" "Platform from LeanIX" {
            
            prms = container "Rights Management System" "" "Application"
            ptXXX = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" "Application"
            rc = container "Repeats Clearances" "This excel spreadsheet is our record of all programmes repeated on C4 with details of any rights/..." "Application"
            sounX = container "Soundmouse" "Representation of Soundmouse as company. Covers all SaaS products offered by Soundmouse: Soundmou..." "Application"
        }

        /* ============================================================
           ROYALTIES AND SALES PLATFORM
           ============================================================ */
        
        rasp = softwareSystem "Royalties and Sales Platform" "Platform from LeanIX" {
            
            come = container "COMET" "Channel 4 International and National Rights Licencing Software used by Channel 4 to manage Films ..." "Application"
            eps = container "Exclusivity Payment Schedules" "Contains payment details due to the artist for an exclusivity deal" "Application"
            neo = container "Neo" "NEO is a Soundmouse application that 4Studio and Rights Team users use. NEO does a shazam of soci..." "Application"
            pap = container "Artist Payments" "Application for reporting artist royalties" "Application"
            pris = container "Royalties Income system" "Manages the Statements and chasing of Statements to ensure Royalties owed to Channel 4 are tracke..." "Application"
            prrs = container "Royalties Reporting System" "RRS Overview Description: The Royalty Reporting System (RRS) is an application used for the conso..." "Application"
            ptXXXX = container "Pirate Tracker" "Monitoring Service for Pirate Services/applications" "Application"
            rcX = container "Repeats Clearances" "This excel spreadsheet is our record of all programmes repeated on C4 with details of any rights/..." "Application"
            sd = container "Sargent Disc" "Sargent-Disc is the U.K.’s foremost entertainment-technology provider, building cloud-based workf..." "Application"
            sounXX = container "Soundmouse" "Representation of Soundmouse as company. Covers all SaaS products offered by Soundmouse: Soundmou..." "Application"
            ted = container "Ted" "Ted is a (tactical) web application that is used by 4Studio to capture key information concerning..." "Application"
            ussw = container "UK Secondary Sales Wishlist" "" "Application"
            vr = container "VOD Revenue" "" "Application"
            vwgm = container "VOD Writers Guild & Musician Payments" "" "Application"
            wga = container "Writers Guild Advances" "" "Application"
        }

        /* ============================================================
           SCHEDULING PLATFORM
           ============================================================ */
        
        spX = softwareSystem "Scheduling Platform" "The Scheduling Platform is a core functional domain that orchestrates the creation and management..." {
            
            modX = container "MediaGenix On Demand" "BeBanjo Movida VOD Management system (Comprising of systems which schedule and manage transcode a..." "Application"
            passX = container "Advance Scheduling System" "The Advanced Scheduling System (A55) provides a view of a schedule for a specific channel and dat..." "Application"
            pepl = container "Electronic Press Listing" "Sends Electronic Programme Guide to other platforms Carries Rights information such as restart" "Application"
            pittX = container "Interface To Transmission Systems" "ITS prepares final schedules for Playout systems. It uses Programme schedules generated from PPS ..." "Application"
            pppsXXX = container "Presentation Planning System" "Manages the detailed channel schedules with all the relevant transmission content required for br..." "Application"
            pppsXXXX = container "Presentation Planning System - PPS.NET" "This is the .NET version of PPS NOTE: We need to create all VOD processes and link one to this ap..." "Application"
        }

        /* ============================================================
           SMALL BUSINESS SERVICES
           ============================================================ */
        
        sbs = softwareSystem "Small Business Services" "A set of small applications delivering discreet business processes usually hosted on SQL on prem ..." {
            
            anda = container "ANDA" "ANDA is a document archive repository. Where physical documents need to be archived (signed contr..." "Application"
            comp = container "Competitions" "It is used by Legal & Compliance to select winners and runner ups for Channel 4 competitions. The..." "Application"
            cms = container "Contract Management System" "Contract Management System, used as a repository for contracts Owned by Procurement storing the m..." "Application"
            dsd = container "Diversity Suppliers DB" "This is a database of supplier information used by the Creative Diversity team based in Glasgow," "Application"
            fa = container "FOIA Application" "Application built on SQL Server for storing Freedom of Information Act requests" "Application"
            mc = container "Music Clearance" "It is used by colleagues in CACL - Commercial Affairs every time Channel 4 license a music track ..." "Application"
            pps = container "Post Production Schedule" "This application is used by 4Creative to plan the development of on-air promotional material and ..." "Application"
            pr = container "Producer Reporting" "It is used by Finance to format the producer reporting statements. The application takes all the ..." "Application"
            sac = container "Stills and Clips" "" "Application"
            time = container "Timesheets" "" "Application"
        }

        /* ============================================================
           VIDEO STREAMING PLATFORM
           ============================================================ */
        
        vsp = softwareSystem "Video Streaming Platform" "Includes all items that provide the value chain" {
            
            c4sl = container "Channel 4 Streaming (Legacy)" "Video on Demand platform across many devices including https://channel4.com" "Application"
            cdna = container "Content Distribution Network (Accenture)" "Logical representation of the CDN's used by Channel 4 Streaming, controlled and maintained by Acc..." "Application"
            free = container "Freely" "" "Application"
            mparX = container "mParticle" "mParticle is a Customer Data Platform. It collects customer data once through secure APIs and SDK..." "Application"
            ova = container "Online Video Analytics" "Real-Time Streaming Video Intelligence" "Application"
            pipe = container "PIPE" "The CMS that drivers Channel 4 Streaming UX in the apps" "Application"
            sm = container "Subscription Management" "The application that manages our subscription products such as offers and deals." "Application"
            sl = container "Sumo Logic" "Sumo Logic is a cloud-based log management and analytics service that leverages machine-generated..." "Application"
            tr = container "Tag Recommender" "A Data Science led application to aid the Channel 4 Streaming editors with tagging for Brands" "Application"
            thin = container "ThinkAnalytics" "World leaders in AI personalized content discovery, hyper-targeted advertising and customer insight." "Application"
        }

        /* ============================================================
           WORKSPACE SYSTEMS PLATFORM
           ============================================================ */
        
        wsp = softwareSystem "Workspace Systems Platform" "Platform from LeanIX" {
            
            acXX = container "Alert Cascade" "Crisis event mass communication tool" "Application"
            ce = container "Concept Evolution" "FM Job sheets for building maintenance used by Facilities & Workspace" "Application"
            egen = container "Egencia" "Egencia is a SaaS platform developed by Amex GBT that offers corporate travel management solution..." "Application"
            tbX = container "Taxi Booking" "This application describes are taxi booking capability at Channel 4." "Application"
            tb-n = container "Taxi Booking - non-London" "This application is used for London based Taxi bookings to and from Horseferry Road" "Application"
        }
        
        /* ============================================================
           PERSON -> APPLICATION RELATIONSHIPS
           ============================================================ */
        
        c4ccToAp = c4cc -> ap "Uses"
        c4ciToAp = c4ci -> ap "Uses"
        c4csToAp = c4cs -> ap "Uses"
        eaToAp = ea -> ap "Uses"
        c4ctToCari = c4ct -> cari "Uses"
        eaToCari = ea -> cari "Uses"
        c4csToCc = c4cs -> cc "Uses"
        c4csToFsh = c4cs -> fsh "Uses"
        c4csToInno = c4cs -> inno "Uses"
        c4caToSc = c4ca -> sc "Uses"
        c4csToSc = c4cs -> sc "Uses"
        c4csXToSc = c4csX -> sc "Uses"
        c4ccToStel = c4cc -> stel "Uses"
        c4ciToStel = c4ci -> stel "Uses"
        c4csToStel = c4cs -> stel "Uses"
        c4csXXToStel = c4csXX -> stel "Uses"
        c4csXXXToStel = c4csXXX -> stel "Uses"
        c4ctXToStel = c4ctX -> stel "Uses"
        c4ccXToAsp = c4ccX -> asp "Uses"
        c4cfToAcf = c4cf -> acf "Uses"
        c4mcToBynd = c4mc -> bynd "Uses"
        c4mmToBynd = c4mm -> bynd "Uses"
        c4ciToC7t = c4ci -> c7t "Uses"
        c4caXToC7t = c4caX -> c7t "Uses"
        c4ccXXToC7t = c4ccXX -> c7t "Uses"
        c4m4ToC7t = c4m4 -> c7t "Uses"
        c4mpToC7t = c4mp -> c7t "Uses"
        c4ccXToDasd = c4ccX -> dasd "Uses"
        eppToEt = epp -> et "Uses"
        eppToGrac = epp -> grac "Uses"
        c4ccXXXToModX = c4ccXXX -> modX "Uses"
        c4ccXToOlss = c4ccX -> olss "Uses"
        c4ccXXXToOsp = c4ccXXX -> osp "Uses"
        c4ctToOsp = c4ct -> osp "Uses"
        c4cfToOl = c4cf -> ol "Uses"
        c4ccXXXXToP4ws = c4ccXXXX -> p4ws "Uses"
        epToP4ws = ep -> p4ws "Uses"
        c4csToPassX = c4cs -> passX "Uses"
        c4ctXToPassX = c4ctX -> passX "Uses"
        c4caXXToPassX = c4caXX -> passX "Uses"
        c4ccXXXXXToPassX = c4ccXXXXX -> passX "Uses"
        c4ccXXXXXXToPassX = c4ccXXXXXX -> passX "Uses"
        c4ccXXXXXXXToPassX = c4ccXXXXXXX -> passX "Uses"
        ccfToPassX = ccf -> passX "Uses"
        c4csXXXXToPassX = c4csXXXX -> passX "Uses"
        c4mmXToPassX = c4mmX -> passX "Uses"
        c4mpToPassX = c4mp -> passX "Uses"
        c4caXXToPbm = c4caXX -> pbm "Uses"
        ccfToPbm = ccf -> pbm "Uses"
        c4cfToPbm = c4cf -> pbm "Uses"
        c4ciXToPc = c4ciX -> pc "Uses"
        c4caXXToPc = c4caXX -> pc "Uses"
        c4ccXXXXXToPc = c4ccXXXXX -> pc "Uses"
        c4ccXXXXXXXXToPc = c4ccXXXXXXXX -> pc "Uses"
        c4ccXXXXXXXXXToPc = c4ccXXXXXXXXX -> pc "Uses"
        c4ccXXXXXXXXXXToPc = c4ccXXXXXXXXXX -> pc "Uses"
        c4ccXXXXXXXXXXXToPc = c4ccXXXXXXXXXXX -> pc "Uses"
        c4ccXXXXXXXXXXXXToPc = c4ccXXXXXXXXXXXX -> pc "Uses"
        c4ccXXXXXXToPc = c4ccXXXXXX -> pc "Uses"
        c4ccXXXXXXXToPc = c4ccXXXXXXX -> pc "Uses"
        ccfToPc = ccf -> pc "Uses"
        c4cfToPc = c4cf -> pc "Uses"
        c4csXXXXToPc = c4csXXXX -> pc "Uses"
        c4f4ToPc = c4f4 -> pc "Uses"
        c4m4ToPc = c4m4 -> pc "Uses"
        c4mmXToPc = c4mmX -> pc "Uses"
        c4mpToPc = c4mp -> pc "Uses"
        c4ciXToPcgs = c4ciX -> pcgs "Uses"
        c4csToPcgs = c4cs -> pcgs "Uses"
        c4caXXToPcgs = c4caXX -> pcgs "Uses"
        c4ccXXXXXXXXXToPcgs = c4ccXXXXXXXXX -> pcgs "Uses"
        c4ccXXXXXXXXXXXXToPcgs = c4ccXXXXXXXXXXXX -> pcgs "Uses"
        c4ccXXXXXXXToPcgs = c4ccXXXXXXX -> pcgs "Uses"
        c4ccXXXToPcgs = c4ccXXX -> pcgs "Uses"
        c4csXXXXToPcgs = c4csXXXX -> pcgs "Uses"
        c4m4ToPcgs = c4m4 -> pcgs "Uses"
        c4mcToPcgs = c4mc -> pcgs "Uses"
        c4mmXToPcgs = c4mmX -> pcgs "Uses"
        c4mpToPcgs = c4mp -> pcgs "Uses"
        c4ciXToPcps = c4ciX -> pcps "Uses"
        c4csToPcps = c4cs -> pcps "Uses"
        c4caXXToPcps = c4caXX -> pcps "Uses"
        c4ccXXXXXToPcps = c4ccXXXXX -> pcps "Uses"
        c4ccXXXXXXXXXToPcps = c4ccXXXXXXXXX -> pcps "Uses"
        c4ccXXXXXXXToPcps = c4ccXXXXXXX -> pcps "Uses"
        c4ccXXXToPcps = c4ccXXX -> pcps "Uses"
        c4mpToPcps = c4mp -> pcps "Uses"
        c4caXXXToPdap = c4caXXX -> pdap "Uses"
        c4csToPfas = c4cs -> pfas "Uses"
        c4caXXToPfas = c4caXX -> pfas "Uses"
        c4ccXXXXXToPfas = c4ccXXXXX -> pfas "Uses"
        ccfToPfas = ccf -> pfas "Uses"
        c4csXXXXToPfas = c4csXXXX -> pfas "Uses"
        c4ciXToPge = c4ciX -> pge "Uses"
        c4csToPge = c4cs -> pge "Uses"
        c4ctXToPge = c4ctX -> pge "Uses"
        c4caXXToPge = c4caXX -> pge "Uses"
        c4ccXXXXXXXXXXXXXToPge = c4ccXXXXXXXXXXXXX -> pge "Uses"
        c4ccXXXXToPge = c4ccXXXX -> pge "Uses"
        c4ccXXXXXXXXXXXXXXToPge = c4ccXXXXXXXXXXXXXX -> pge "Uses"
        c4ccXXXXXToPge = c4ccXXXXX -> pge "Uses"
        c4ccXXXXXXXXToPge = c4ccXXXXXXXX -> pge "Uses"
        c4ccXXXXXXXXXToPge = c4ccXXXXXXXXX -> pge "Uses"
        c4ccXXXXXXXXXXXXXXXToPge = c4ccXXXXXXXXXXXXXXX -> pge "Uses"
        c4ccXXXXXXXXXXToPge = c4ccXXXXXXXXXX -> pge "Uses"
        c4ccXXXXXXXXXXXToPge = c4ccXXXXXXXXXXX -> pge "Uses"
        c4ccXXXXXXXXXXXXToPge = c4ccXXXXXXXXXXXX -> pge "Uses"
        c4ccXXXXXXToPge = c4ccXXXXXX -> pge "Uses"
        c4ccXXXXXXXToPge = c4ccXXXXXXX -> pge "Uses"
        c4ccXXToPge = c4ccXX -> pge "Uses"
        c4ccXXXXXXXXXXXXXXXXToPge = c4ccXXXXXXXXXXXXXXXX -> pge "Uses"
        c4ccXToPge = c4ccX -> pge "Uses"
        c4ccXXXToPge = c4ccXXX -> pge "Uses"
        ccfToPge = ccf -> pge "Uses"
        c4cpToPge = c4cp -> pge "Uses"
        c4csXXXXToPge = c4csXXXX -> pge "Uses"
        c4f4ToPge = c4f4 -> pge "Uses"
        c4mToPge = c4m -> pge "Uses"
        c4m4XToPge = c4m4X -> pge "Uses"
        c4m4ToPge = c4m4 -> pge "Uses"
        c4mcToPge = c4mc -> pge "Uses"
        c4mmXToPge = c4mmX -> pge "Uses"
        c4mpToPge = c4mp -> pge "Uses"
        c4ccXXXXXXToPip = c4ccXXXXXX -> pip "Uses"
        c4ccXXXXXXXToPip = c4ccXXXXXXX -> pip "Uses"
        ccfToPip = ccf -> pip "Uses"
        c4cfToPip = c4cf -> pip "Uses"
        c4mmXToPip = c4mmX -> pip "Uses"
        c4mpToPip = c4mp -> pip "Uses"
        c4ccXXXToPittX = c4ccXXX -> pittX "Uses"
        c4csToPmam = c4cs -> pmam "Uses"
        c4ccXXXXXXXToPmam = c4ccXXXXXXX -> pmam "Uses"
        ccfToPmam = ccf -> pmam "Uses"
        c4cfToPmam = c4cf -> pmam "Uses"
        c4csToPmmX = c4cs -> pmmX "Uses"
        c4caXXToPmmX = c4caXX -> pmmX "Uses"
        c4ccXXXXXToPmmX = c4ccXXXXX -> pmmX "Uses"
        c4ccXXXXXXXXXXToPmmX = c4ccXXXXXXXXXX -> pmmX "Uses"
        c4ccXXXXXXXXXXXXToPmmX = c4ccXXXXXXXXXXXX -> pmmX "Uses"
        c4ccXXXXXXToPmmX = c4ccXXXXXX -> pmmX "Uses"
        c4ccXXXXXXXToPmmX = c4ccXXXXXXX -> pmmX "Uses"
        c4ccXXToPmmX = c4ccXX -> pmmX "Uses"
        c4m4XToPmmX = c4m4X -> pmmX "Uses"
        c4mmXToPmmX = c4mmX -> pmmX "Uses"
        c4csToPofg = c4cs -> pofg "Uses"
        c4ccXXXXXXXToPofg = c4ccXXXXXXX -> pofg "Uses"
        ccfToPofg = ccf -> pofg "Uses"
        c4cfToPofg = c4cf -> pofg "Uses"
        c4csToPppsXXX = c4cs -> pppsXXX "Uses"
        c4caXXToPppsXXX = c4caXX -> pppsXXX "Uses"
        c4ccXXXXXToPppsXXX = c4ccXXXXX -> pppsXXX "Uses"
        c4ccXXXXXXXXXXXToPppsXXX = c4ccXXXXXXXXXXX -> pppsXXX "Uses"
        c4ccXXXXXXXToPppsXXX = c4ccXXXXXXX -> pppsXXX "Uses"
        c4ccXToPppsXXX = c4ccX -> pppsXXX "Uses"
        c4csXXXXToPppsXXX = c4csXXXX -> pppsXXX "Uses"
        c4m4XToPppsXXX = c4m4X -> pppsXXX "Uses"
        c4m4ToPppsXXX = c4m4 -> pppsXXX "Uses"
        c4mmXToPppsXXX = c4mmX -> pppsXXX "Uses"
        c4mpToPppsXXX = c4mp -> pppsXXX "Uses"
        c4ciXToPppsXXXX = c4ciX -> pppsXXXX "Uses"
        c4csToPppsXXXX = c4cs -> pppsXXXX "Uses"
        c4caXXToPppsXXXX = c4caXX -> pppsXXXX "Uses"
        c4ccXXXXXToPppsXXXX = c4ccXXXXX -> pppsXXXX "Uses"
        c4ccXXXXXXXXXXToPppsXXXX = c4ccXXXXXXXXXX -> pppsXXXX "Uses"
        c4ccXXXXXXXXXXXToPppsXXXX = c4ccXXXXXXXXXXX -> pppsXXXX "Uses"
        c4ccXXXXXXXToPppsXXXX = c4ccXXXXXXX -> pppsXXXX "Uses"
        ccfToPppsXXXX = ccf -> pppsXXXX "Uses"
        c4m4XToPppsXXXX = c4m4X -> pppsXXXX "Uses"
        c4mmXToPppsXXXX = c4mmX -> pppsXXXX "Uses"
        c4caXXToPpp = c4caXX -> ppp "Uses"
        c4ccXXXXXXXXXXXXXToPpp = c4ccXXXXXXXXXXXXX -> ppp "Uses"
        c4ccXXXXXToPpp = c4ccXXXXX -> ppp "Uses"
        c4ccXXXXXXXXToPpp = c4ccXXXXXXXX -> ppp "Uses"
        c4ccXXXXXXXXXToPpp = c4ccXXXXXXXXX -> ppp "Uses"
        c4ccXXXXXXXXXXXXXXXToPpp = c4ccXXXXXXXXXXXXXXX -> ppp "Uses"
        c4ccXXXXXXXXXXToPpp = c4ccXXXXXXXXXX -> ppp "Uses"
        c4ccXXXXXXXXXXXToPpp = c4ccXXXXXXXXXXX -> ppp "Uses"
        c4ccXXXXXXXXXXXXToPpp = c4ccXXXXXXXXXXXX -> ppp "Uses"
        c4ccXXXXXXToPpp = c4ccXXXXXX -> ppp "Uses"
        c4ccXXXXXXXToPpp = c4ccXXXXXXX -> ppp "Uses"
        ccfToPpp = ccf -> ppp "Uses"
        c4csXXXXToPpp = c4csXXXX -> ppp "Uses"
        c4f4ToPpp = c4f4 -> ppp "Uses"
        c4m4XToPpp = c4m4X -> ppp "Uses"
        c4mmXToPpp = c4mmX -> ppp "Uses"
        epToPpp = ep -> ppp "Uses"
        c4csToPpc = c4cs -> ppc "Uses"
        c4caXXToPpc = c4caXX -> ppc "Uses"
        c4caXToPpc = c4caX -> ppc "Uses"
        c4ccXXXXXToPpc = c4ccXXXXX -> ppc "Uses"
        c4ccXXXXXXXXToPpc = c4ccXXXXXXXX -> ppc "Uses"
        c4ccXXXXXXXXXToPpc = c4ccXXXXXXXXX -> ppc "Uses"
        c4ccXXXXXXXXXXToPpc = c4ccXXXXXXXXXX -> ppc "Uses"
        c4ccXXXXXXXXXXXToPpc = c4ccXXXXXXXXXXX -> ppc "Uses"
        c4ccXXXXXXXXXXXXToPpc = c4ccXXXXXXXXXXXX -> ppc "Uses"
        c4ccXXXXXXToPpc = c4ccXXXXXX -> ppc "Uses"
        c4ccXXXXXXXToPpc = c4ccXXXXXXX -> ppc "Uses"
        c4csXXXXToPpc = c4csXXXX -> ppc "Uses"
        c4m4XToPpc = c4m4X -> ppc "Uses"
        c4mmXToPpc = c4mmX -> ppc "Uses"
        c4ccXXXToPrta = c4ccXXX -> prta "Uses"
        ccfToPswo = ccf -> pswo "Uses"
        c4cfToPswo = c4cf -> pswo "Uses"
        c4ccXXXXXXXToPsfv = c4ccXXXXXXX -> psfv "Uses"
        c4ccXXXToPsfv = c4ccXXX -> psfv "Uses"
        c4m4ToPsfv = c4m4 -> psfv "Uses"
        c4ccXXXToPtis = c4ccXXX -> ptis "Uses"
        c4cToPvbX = c4c -> pvbX "Uses"
        c4caXToPvbX = c4caX -> pvbX "Uses"
        c4ccXXXXXXXToPvbX = c4ccXXXXXXX -> pvbX "Uses"
        c4ccXXXXXXXXXXXXXXXXToPvbX = c4ccXXXXXXXXXXXXXXXX -> pvbX "Uses"
        c4ccXXXToPvbX = c4ccXXX -> pvbX "Uses"
        c4ciXToPve = c4ciX -> pve "Uses"
        c4csToPve = c4cs -> pve "Uses"
        c4caXXToPve = c4caXX -> pve "Uses"
        c4ccXXXXXToPve = c4ccXXXXX -> pve "Uses"
        c4ccXXXXXXXXXXXToPve = c4ccXXXXXXXXXXX -> pve "Uses"
        c4ccXXXXXXXToPve = c4ccXXXXXXX -> pve "Uses"
        c4ccXXXToPve = c4ccXXX -> pve "Uses"
        c4csXXXXToPve = c4csXXXX -> pve "Uses"
        c4mmXToPve = c4mmX -> pve "Uses"
        c4mpToPve = c4mp -> pve "Uses"
        c4ciXToPvms = c4ciX -> pvms "Uses"
        c4caXXToPvms = c4caXX -> pvms "Uses"
        c4ccXXXXXToPvms = c4ccXXXXX -> pvms "Uses"
        c4ccXXXXXXXToPvms = c4ccXXXXXXX -> pvms "Uses"
        c4ccXXXToPvma = c4ccXXX -> pvma "Uses"
        c4cfToSounXX = c4cf -> sounXX "Uses"
        c4ccXToSsfa = c4ccX -> ssfa "Uses"
        c4ccXXXToTb = c4ccXXX -> tb "Uses"
        epToDist = ep -> dist "Uses"
        c4caXXToPasc = c4caXX -> pasc "Uses"
        c4caXXXXToPasc = c4caXXXX -> pasc "Uses"
        c4ccXXXXXToPasc = c4ccXXXXX -> pasc "Uses"
        ccfToPasc = ccf -> pasc "Uses"
        c4csToPcf = c4cs -> pcf "Uses"
        c4caXXToPcf = c4caXX -> pcf "Uses"
        c4ccXXXXXXToPcf = c4ccXXXXXX -> pcf "Uses"
        c4ccXXXXXXXToPcf = c4ccXXXXXXX -> pcf "Uses"
        ccfToPcf = ccf -> pcf "Uses"
        c4cfToPcf = c4cf -> pcf "Uses"
        c4ciXToPcc = c4ciX -> pcc "Uses"
        c4csToPcc = c4cs -> pcc "Uses"
        c4caXXToPcc = c4caXX -> pcc "Uses"
        c4ccXXXXXXXXXXXXXToPcc = c4ccXXXXXXXXXXXXX -> pcc "Uses"
        c4ccXXXXToPcc = c4ccXXXX -> pcc "Uses"
        c4ccXXXXXToPcc = c4ccXXXXX -> pcc "Uses"
        c4ccXXXXXXXXToPcc = c4ccXXXXXXXX -> pcc "Uses"
        c4ccXXXXXXXXXToPcc = c4ccXXXXXXXXX -> pcc "Uses"
        c4ccXXXXXXXXXXXXXXXToPcc = c4ccXXXXXXXXXXXXXXX -> pcc "Uses"
        c4ccXXXXXXXXXXToPcc = c4ccXXXXXXXXXX -> pcc "Uses"
        c4ccXXXXXXXXXXXToPcc = c4ccXXXXXXXXXXX -> pcc "Uses"
        c4ccXXXXXXXXXXXXToPcc = c4ccXXXXXXXXXXXX -> pcc "Uses"
        c4ccXXXXXXToPcc = c4ccXXXXXX -> pcc "Uses"
        c4ccXXXXXXXToPcc = c4ccXXXXXXX -> pcc "Uses"
        ccfToPcc = ccf -> pcc "Uses"
        c4csXXXXToPcc = c4csXXXX -> pcc "Uses"
        c4f4ToPcc = c4f4 -> pcc "Uses"
        c4m4XToPcc = c4m4X -> pcc "Uses"
        c4mmXToPcc = c4mmX -> pcc "Uses"
        epToPcc = ep -> pcc "Uses"
        c4ciXToPp = c4ciX -> pp "Uses"
        c4csToPp = c4cs -> pp "Uses"
        c4caXXToPp = c4caXX -> pp "Uses"
        c4ccXXXXXToPp = c4ccXXXXX -> pp "Uses"
        c4ccXXXXXXXXToPp = c4ccXXXXXXXX -> pp "Uses"
        c4ccXXXXXXXXXToPp = c4ccXXXXXXXXX -> pp "Uses"
        c4ccXXXXXXXXXXToPp = c4ccXXXXXXXXXX -> pp "Uses"
        c4ccXXXXXXXXXXXToPp = c4ccXXXXXXXXXXX -> pp "Uses"
        c4ccXXXXXXXXXXXXToPp = c4ccXXXXXXXXXXXX -> pp "Uses"
        c4ccXXXXXXToPp = c4ccXXXXXX -> pp "Uses"
        c4ccXXXXXXXToPp = c4ccXXXXXXX -> pp "Uses"
        c4ccXXXToPp = c4ccXXX -> pp "Uses"
        ccfToPp = ccf -> pp "Uses"
        c4f4ToPp = c4f4 -> pp "Uses"
        c4mcToPp = c4mc -> pp "Uses"
        c4caXXToPpX = c4caXX -> ppX "Uses"
        c4ccXXXXXToPpX = c4ccXXXXX -> ppX "Uses"
        c4ccXXXXXXXXToPpX = c4ccXXXXXXXX -> ppX "Uses"
        c4ccXXXToPpX = c4ccXXX -> ppX "Uses"
        ccfToPpX = ccf -> ppX "Uses"
        c4csXXXXXToAs = c4csXXXXX -> as "Uses"
        c4csToBarb = c4cs -> barb "Uses"
        c4csXXXXXXToBarb = c4csXXXXXX -> barb "Uses"
        c4ccToBor = c4cc -> bor "Uses"
        c4ciToBor = c4ci -> bor "Uses"
        c4csToBor = c4cs -> bor "Uses"
        c4ctXToBor = c4ctX -> bor "Uses"
        c4csXXXXXXXToCedw = c4csXXXXXXX -> cedw "Uses"
        c4csXXXXXXToCedw = c4csXXXXXX -> cedw "Uses"
        c4ctXXToCedw = c4ctXX -> cedw "Uses"
        c4csXXXXXXXToC4 = c4csXXXXXXX -> c4 "Uses"
        c4csToDcri = c4cs -> dcri "Uses"
        c4ciXXToDcrs = c4ciXX -> dcrs "Uses"
        c4mmToDcrs = c4mm -> dcrs "Uses"
        c4mmXXToDcrs = c4mmXX -> dcrs "Uses"
        c4csToDf = c4cs -> df "Uses"
        c4csXToDf = c4csX -> df "Uses"
        c4mpXToTabl = c4mpX -> tabl "Uses"
        c4mpXToWa = c4mpX -> wa "Uses"
        ccfToAtax = ccf -> atax "Uses"
        ccfToBbp = ccf -> bbp "Uses"
        c4XToBsw = c4X -> bsw "Uses"
        ccfToBsw = ccf -> bsw "Uses"
        ccfrssToBsw = ccfrss -> bsw "Uses"
        ccfToEbs = ccf -> ebs "Uses"
        ccfrssToEbs = ccfrss -> ebs "Uses"
        c4XToFaf = c4X -> faf "Uses"
        ccfToMsc = ccf -> msc "Uses"
        ccfToSov = ccf -> sov "Uses"
        ccfToSbi = ccf -> sbi "Uses"
        ccfrssToSbi = ccfrss -> sbi "Uses"
        ccfrssToTgn = ccfrss -> tgn "Uses"
        ccfToWda = ccf -> wda "Uses"
        c4ccXXXXXXXXXXXXXXXXToLsp = c4ccXXXXXXXXXXXXXXXX -> lsp "Uses"
        c4ccXXXToLsp = c4ccXXX -> lsp "Uses"
        c4ctToLsp = c4ct -> lsp "Uses"
        c4ctToSp = c4ct -> sp "Uses"
        c4mmXXToBraz = c4mmXX -> braz "Uses"
        c4mpXXToMparX = c4mpXX -> mparX "Uses"
        c4mpXXXToMparX = c4mpXXX -> mparX "Uses"
        c4ccXXXXXToAwar = c4ccXXXXX -> awar "Uses"
        c4csXXXToMsp = c4csXXX -> msp "Uses"
        c4ccXXXXXXXXXXXXXXXXXToMsp = c4ccXXXXXXXXXXXXXXXXX -> msp "Uses"
        c4ccXXXXXXXToMsp = c4ccXXXXXXX -> msp "Uses"
        c4ccXToMsp = c4ccX -> msp "Uses"
        c4ctToMsp = c4ct -> msp "Uses"
        c4m4XToMsp = c4m4X -> msp "Uses"
        epToMsp = ep -> msp "Uses"
        c4caXToPpsp = c4caX -> ppsp "Uses"
        c4ctToPpsp = c4ct -> ppsp "Uses"
        c4m4XToPpsp = c4m4X -> ppsp "Uses"
        c4XTo4peo = c4X -> 4peo "Uses"
        c4cpTo4peo = c4cp -> 4peo "Uses"
        c4XToActi = c4X -> acti "Uses"
        c4cpToActi = c4cp -> acti "Uses"
        c4cXToAcXX = c4cX -> acXX "Uses"
        c4XToBp = c4X -> bp "Uses"
        c4cpXToBp = c4cpX -> bp "Uses"
        c4ctXXXToEr = c4ctXXX -> er "Uses"
        c4XToFes = c4X -> fes "Uses"
        c4cpToFes = c4cp -> fes "Uses"
        c4XToLl = c4X -> ll "Uses"
        c4cpXXToLl = c4cpXX -> ll "Uses"
        c4cpToPopp = c4cp -> popp "Uses"
        c4XToTlh = c4X -> tlh "Uses"
        c4csToPrms = c4cs -> prms "Uses"
        c4caXXToPrms = c4caXX -> prms "Uses"
        c4ccXXXXXToPrms = c4ccXXXXX -> prms "Uses"
        c4ccXXXXXXXXXToPrms = c4ccXXXXXXXXX -> prms "Uses"
        c4ccXXXXXXXToPrms = c4ccXXXXXXX -> prms "Uses"
        c4ccXXXToPrms = c4ccXXX -> prms "Uses"
        ccfToPrms = ccf -> prms "Uses"
        c4m4ToPrms = c4m4 -> prms "Uses"
        c4mmXToPrms = c4mmX -> prms "Uses"
        c4caXXToRcX = c4caXX -> rcX "Uses"
        c4ciToCome = c4ci -> come "Uses"
        c4caXXToCome = c4caXX -> come "Uses"
        c4ccXXXToCome = c4ccXXX -> come "Uses"
        ccfrssToCome = ccfrss -> come "Uses"
        c4caXXToEps = c4caXX -> eps "Uses"
        c4caXXToNeo = c4caXX -> neo "Uses"
        c4csToPap = c4cs -> pap "Uses"
        c4caXXToPap = c4caXX -> pap "Uses"
        ccfToPap = ccf -> pap "Uses"
        c4csXXXXToPap = c4csXXXX -> pap "Uses"
        c4caXXToPris = c4caXX -> pris "Uses"
        c4ccXXXToPris = c4ccXXX -> pris "Uses"
        ccfToPris = ccf -> pris "Uses"
        c4m4ToPris = c4m4 -> pris "Uses"
        c4caXXToPrrs = c4caXX -> prrs "Uses"
        ccfToPrrs = ccf -> prrs "Uses"
        c4caXXToSd = c4caXX -> sd "Uses"
        c4m4ToTed = c4m4 -> ted "Uses"
        c4ccXXXXXToPepl = c4ccXXXXX -> pepl "Uses"
        c4ccXXXXXXToPepl = c4ccXXXXXX -> pepl "Uses"
        c4ccXXXXXXXToPepl = c4ccXXXXXXX -> pepl "Uses"
        c4ccXXXToPepl = c4ccXXX -> pepl "Uses"
        c4mcToPepl = c4mc -> pepl "Uses"
        c4caXToAnda = c4caX -> anda "Uses"
        c4ccXXXToAnda = c4ccXXX -> anda "Uses"
        c4cfXToCms = c4cfX -> cms "Uses"
        c4caXXXXXToFa = c4caXXXXX -> fa "Uses"
        c4ctXXToTime = c4ctXX -> time "Uses"
        evToC4sl = ev -> c4sl "Uses"
        c4mpXXXXToPipe = c4mpXXXX -> pipe "Uses"
        c4mpXXXXXToSm = c4mpXXXXX -> sm "Uses"
        c4ctXXToSl = c4ctXX -> sl "Uses"
        c4ccXXXToTr = c4ccXXX -> tr "Uses"
        c4mpXXToThin = c4mpXX -> thin "Uses"
        c4cfXXToCe = c4cfXX -> ce "Uses"
        c4XToEgen = c4X -> egen "Uses"
        ccfToEgen = ccf -> egen "Uses"

        /* ============================================================
           APPLICATION -> APPLICATION RELATIONSHIPS (from LeanIX Interfaces)
           ============================================================ */
        
        4ta = 4peo -> acti "4People to ActivePay" "Employees interface synchronisation with Active Pay" "Integration"
        4tac = 4peo -> acXX "4People to Alert cascade" "Current employee sync to Alert Cascade mass notification service" "Integration"
        4tb = 4peo -> acXX "4People to Benefits" "TBC" "Integration"
        4tce = 4peo -> ce "4People to Concept Evolution" "Employee records synchronisation between Sage People and Concept Evolution facilities management ..." "Integration"
        4tcm = 4peo -> cms "4People to Contract Management System(CMS)" "Current employee/additional worker with Active AD account daily sync" "Integration"
        4tc = 4peo -> tlh "4People to Cornerstone" "This data pipeline moves/updates current employee list of data between Sage People and Cornerston..." "Integration"
        4te = 4peo -> egen "4People to Egencia" "Weekly data pipeline from Sage People to Egencia travel management app of Joiners and Leavers emp..." "Integration"
        4toe = 4peo -> ebs "4People to Oracle EBS" "Full extract of employees from Sage People including additional workers" "Integration"
        4tp = 4peo -> wda "4People to Planning" "TBC" "Integration"
        4tpX = 4peo -> popp "4People to Poppulo" "TBC" "Integration"
        atsf = passX -> stel "A55 to Stellar for Advanced Schedule data flow" "Contains an overview of the coming 60-90 days of schedule (in A55 format) one per C4 owned channe..." "Integration"
        aptf = acti -> wda "Active Pay to Financial Planning" "Staff costs - Monthly" "Integration"
        atoe = acti -> ebs "ActivPay to Oracle EBS" "Monthly payrol data synchronisation between ActivePay and Oracle EBS" "Integration"
        aate = wa -> cedw "Adobe Analytics to EDW" "Interface collects Adobe clickstream data from Adobe and loads it to EDW" "Integration"
        apff = ap -> pbm "Agency Portal fetch from Pirate for Brand" "Fetch Brand information from Pirate, Change exception handling and error reporting." "Integration"
        apffX = ap -> stel "Agency Portal fetch from Stellar for Programme" "Fetch Contract information from Stellar, Change exception handling and error reporting." "Integration"
        apfs = ap -> stel "Agency Portal from Stellar for Pick Your Own transmission" "Call Stellar webservices from Agency Portal for Pick Your Own services" "Integration"
        ai = pcc -> prrs "Agreement Information" "CC/Purchases will send data to RRS such as the Contract Number, Contract Title, Supplier name i.e..." "Integration"
        apX = sd -> pap "Artist payments" "Payment files (one payee, one payment batch) are sent from APS to Sargent-Disc for each payment r..." "Integration"
        adaa = asp -> msp "ASP Delivery Acknowledgment API" "TBC" "Integration"
        alss = lsp -> asp "ASP live subtitle streams to LSP" "TBC" "Integration"
        alls = asp -> lsp "ASP low latency stream from LSP" "TBC" "Integration"
        apja = asp -> msp "ASP Production Job API" "TBC" "Integration"
        apjs = msp -> asp "ASP Production Job Status API" "TBC" "Integration"
        asfp = asp -> pira "ASP Schedule from Pirate" "TBC" "Integration"
        assm = asp -> msp "ASP Signer Source Media File Delivery" "TBC" "Integration"
        avcm = asp -> msp "ASP Viewing Copy Media File Delivery" "TBC" "Integration"
        asal = fsh -> as "Audience Segments and Lookalikes to Freewheel" "Pipeline showing processing of Channel 4 matched viewer data from Mediarithmics to Freewheel" "Integration"
        bwpf = ebs -> bbp "BACS & Wire Payments File Out" "TBC" "Integration"
        brdt = barb -> cedw "BARB ratings data to EDW" "Interface describes all data that is received from BARB which and is related to the audience perf..." "Integration"
        btsf = barb -> stel "BARB to Stellar for Audience Universe" "Contains population data concerning audiences and regions. Note only comes from BARB. Nielsen inc..." "Integration"
        btsfX = barb -> stel "BARB to Stellar for Impacts" "Television impacts by audience (sent daily). Actually consists of two files, daily ratings as wel..." "Integration"
        bpsr = bbp -> ebs "Barclay Payment Statement Receipt In" "TBC" "Integration"
        bsi = bbp -> ebs "Barclay Statement In" "TBC" "Integration"
        bbdc = ebs -> bsw "Basware Business Department Codes" "Interface from Oracle to Basware that provides users department codes." "Integration"
        bcer = ebs -> bsw "Basware Currency Exchange Rates" "Interface from Oracle to Basware that provides users exchange rate information." "Integration"
        bgcv = ebs -> bsw "Basware GL Cross Validation Rules" "Interface from Oracle to Basware that provides cross validation rules." "Integration"
        bgnc = ebs -> bsw "Basware GL Nominal Codes" "Interface from Oracle to Basware that provides GL nominal codes." "Integration"
        bic = ebs -> bsw "Basware Individual Codes" "Interface from Oracle to Basware that provides individual codes." "Integration"
        bis = bsw -> ebs "Basware Invoice Statuses" "Interface from Basware to Oracle that provides invoice status updates." "Integration"
        bppi = ebs -> bsw "Basware Payments/Void Payments/Cancelled Invoices" "Interface from Basware to Oracle that provides payments and cancellation updates." "Integration"
        bpcc = ebs -> bsw "Basware Pirate Code Combinations" "Interface from Oracle to Basware that provides Pirate code combinations" "Integration"
        bpc = ebs -> bsw "Basware Product Codes" "Interface from Oracle to Basware that provides product codes." "Integration"
        bpcX = ebs -> bsw "Basware Project Codes" "Interface from Oracle to Basware that provides project codes." "Integration"
        bs = ebs -> bsw "Basware Suppliers" "Interface from Oracle to Basware that provides a current list of suppliers" "Integration"
        btef = bsw -> ebs "Basware to EBS for Approved Invoices" "TBC" "Integration"
        btso = bsw -> ebs "Basware to SplashBI (Oracle eBS Schema)" "Integration that takes data from the Basware SaaS tool, via an API data call, transforms and load..." "Integration"
        btso2 = bsw -> sbi "Basware to SplashBI (Oracle eBS Schema)" "Integration that takes data from the Basware SaaS tool, via an API data call, transforms and load..." "Integration"
        bur = ebs -> bsw "Basware User Rights" "Interface from Oracle to Basware that provides users, advanced rights, user rights and approval p..." "Integration"
        buri = ebs -> bsw "Basware User Rights (Inactive users)" "For inactive users it provides users, advanced rights, user rights and approval paths." "Integration"
        bta = acti -> bp "Benefits to Actvipay" "*** THIS IS NOT CURRENTLY IMPLEMENTED IN MULE ***. This interface sends benefit selection data ba..." "Integration"
        bdte = stel -> cedw "Budget data to EDW" "Copies Budget and Universe data to Aurora. Name of specific ETL job: BDAP_JOB_sdw_to_aurora" "Integration"
        btmi = modX -> bynd "Bynder to MediaGenix Image Integration" "TBC" "Integration"
        btmiX = modX -> bynd "Bynder to MediaGenix Image Tagging Changes" "TBC" "Integration"
        chpt = er -> bor "C4 HR & Payroll to PowerBI Reporting" "Executive reporting report about employees and freelancers" "Integration"
        cio = ebs -> come "C4 intl overages" "This interface exports to Oracle eBusiness Suite the invoices generated in Comet from Contract in..." "Integration"
        cvr = sov -> ebs "C4 VAT Returns" "This is a data exchange between Sovos SaaS software used in Channel 4 and HMRC portal" "Integration"
        cbsd = sm -> cedw "C4S Braintree Subscriber data to EDW" "Braintree Channel 4 Streaming subscriber data to Redshift EDW" "Integration"
        cetf = free -> pepl "C4S EPG to Freely" "EPG to aid 'out of app' discovery" "Integration"
        cete = mparX -> cedw "C4S Events to EDW" "TBC" "Integration"
        cfve = ova -> free "C4S Freely Video Events to BitMovin Analytics" "Freely will make requests for DRM licences from the DRM Provider" "Integration"
        cfvs = cdna -> free "C4S Freely Video Stream from CDN" "C4 Streaming requests video streams (chucks of stream data) from the CDN (Akamai or Cloudfront). ..." "Integration"
        cmif = cdna -> modX "C4S MoD Images from CDN" "MoD copies the image from this location" "Integration"
        cqte = ova -> cedw "C4S QoS to EDW" "QoS export to EDW" "Integration"
        ctaa = wa -> c4sl "C4S to Adobe Analytics" "TBC" "Integration"
        ctb = barb -> c4sl "C4S to BARB" "TBC" "Integration"
        ctc7 = c4sl -> c7t "C4S to C4 7A Titles" "TBC" "Integration"
        ctlv = lsp -> c4sl "C4S to Licence Validation Service" "TBC" "Integration"
        ctsm = sm -> c4sl "C4S to Subscription Management (Aptitude)" "Subscription for Channel 4 Streaming (Legacy) to Aptitude (Legacy)" "Integration"
        ctt- = thin -> c4sl "C4S to ThinkAnalytics - User Events" "TBC" "Integration"
        ctet = wa -> mparX "C4S Tracking Events to Adobe Analytics" "TBC" "Integration"
        ctetX = mparX -> c4sl "C4S Tracking Events to mParticle" "All 4 clients sending user tracking events to mParticle" "Integration"
        cvmt = free -> modX "C4S VoD Metadata to Freely" "Metadata for VoD assets to aid 'out of app' discovery" "Integration"
        c4st = po -> po "C4STELLARPROMO" "TBC" "Integration"
        c4st2 = po -> stel "C4STELLARPROMO" "TBC" "Integration"
        caap = ap -> stel "CARIA and Agency Portal from Stellar for Deals" "Used to fetch 1. Pre-defined package data from Stellar by CARIA 2. Deals and Campaigns specific d..." "Integration"
        cfsf = cari -> stel "CARIA from Stellar for Copy Rotation Instruction" "A Caria API will need to be called once one of the following actions are performed in Stellar - 1..." "Integration"
        ctsf = cari -> stel "CARIA to Stellar for Copy Rotation Instructions" "Information about how to allocate the copy for a campaign’s spots. (e.g. how to rotate them in th..." "Integration"
        ctsfX = cari -> stel "CARIA to STELLAR for Deals and Campaign creation" "Data flow interface via an ~XML file using SOJA and FTP from CARIA to Stellar containing Campaign..." "Integration"
        crfo = ebs -> come "Cash Receipts from Oracle to Comet" "This interface brings invoice payment data into Comet. Finance applies the receipt from the Bank ..." "Integration"
        ctt = pcgs -> ptis "CGS to TIS2" "TBC" "Integration"
        c4it = msp -> pmmX "Channel 4 Interstitals to RedBee" "JSON wrapper for interstitial operations of BTO Metadata Exchange Service and MMWebService" "Integration"
        c4sr = braz -> c4sl "Channel 4 Streaming Recommendations to Braze" "Recommendations feed from Think Analytics via Channel 4 Streaming to Braze" "Integration"
        c4tp = msp -> asp "Channel 4 to PFT token" "C4-PFT-TOKEN is an application used to manage access tokens for PFT APIs, avoiding the need to bu..." "Integration"
        crbt = as -> dcri "Clean Room (Brandm4tch) to Audience Segmentation" "Pipeline showing processing of Channel 4 viewer data inside Infosum application and enrich it and..." "Integration"
        crbt2 = as -> dcrs "Clean Room (Brandm4tch) to Audience Segmentation" "Pipeline showing processing of Channel 4 viewer data inside Infosum application and enrich it and..." "Integration"
        ctsfXX = fsh -> stel "Clearcast to Stellar for Copy Clearance Information" "Import Copy Clearance information from Clearcast at regular intervals of 10 mins into Stellar app..." "Integration"
        ctf = fsh -> cmt "CMT to Freewheel" "TBC" "Integration"
        ctp = pira -> cmt "CMT to Pirate" "TBC" "Integration"
        ctpc = cmt -> pcX "CMT to Promo Create" "TBC" "Integration"
        ctpo = po -> cmt "CMT to Promo Optimiser" "CMT sends campaign details to optimiser and TVRS" "Integration"
        ccii = come -> ebs "Comet C4I Invoice Interface" "This interface exports to Oracle eBusiness Suite the invoices generated in Comet from Contract in..." "Integration"
        cfii = ebs -> come "Comet FFL Invoice Interface" "An automate job creates a file from the invoice data in the Comet Interface. This data is transfo..." "Integration"
        cai = pira -> pris "Contract & Agreement info" "Pirate data pulled/ingested showing contract details such as title, agreement, etc." "Integration"
        caiX = pcc -> pap "Contract/Prog & Agreement info" "Pirate data displaying contract details such as title, agreement, etc." "Integration"
        cpdt = pira -> anda "Contracts PAC data to Anda" "PDF format PAC forms received from Silvermouse are archived in ANDA." "Integration"
        cctf = cc -> fsh "Copy Central to Freewheel" "TBC" "Integration"
        ccts = cc -> stel "Copy Central to Stellar" "TBC" "Integration"
        ctll = tlh -> ll "Cornerstone to LinkedIn Learning" "Bidirectional API data flow and integration between Cornerstone and LinkedIn Learning enable empl..." "Integration"
        epct = fes -> ebs "EBS project codes to FES" "TBC" "Integration"
        et4f = 4peo -> ebs "EBS to 4People for Employees" "Employee data transfer between 4People and EBS" "Integration"
        etbf = ebs -> bsw "EBS to Basware for Reference & Transactional data" "Project Codes, suppliers, departments, nominals, projects, cross combinations, users, user privil..." "Integration"
        etcf = come -> ebs "EBS to Comet for Cash Receipts" "This interface brings invoice payment data into Comet C4I and Comet Film4. Source Application: Or..." "Integration"
        etmf = msc -> ebs "EBS to Mastercard for Employee credit card transactions" "TBC" "Integration"
        etpc = ebs -> come "EBS to Pirate (Comet Flim4)" "An automate job creates a file from the invoice data in the Comet Interface. This data is transfo..." "Integration"
        etsd = ebs -> stel "EBS to Stellar Daily exchange rate (in) Invoices (out)" "TBC" "Integration"
        etsf = ebs -> stel "EBS to Stellar for Currency Exchange" "The interface serves a crucial role in managing the exchange rate file that is used for convertin..." "Integration"
        etp = ebs -> wda "eBusiness to Planning" "TBC" "Integration"
        e4ti = dcri -> cedw "EDW 4 to Infosum" "This is an ETL job which loads Active Channel 4 streaming users, excluding opted out users, into ..." "Integration"
        emcs = df -> cedw "EDW Marketing Campaign Snapshots to Microsoft Data Fabric" "Campaign Snapshot data from Camgen for visualisation in Power BI showing the different option CAM..." "Integration"
        emct = df -> cedw "EDW Marketing Campaign to Microsoft Data Fabric" "Non Snapshot version of the Campaign Data Model queried using federation from AWS Redshift EDW in..." "Integration"
        esit = braz -> cedw "EDW Streaming Identity to Braze" "Identity feed originating from C4S to Braze" "Integration"
        etdf = df -> cedw "EDW to  Data Fabric - Spots data" "Reading Spot related data into Power BI for consumption by Commercial teams" "Integration"
        etap = cedw -> pap "EDW to Artist Payment Systems (Pirate)" "Interface providing VoD viewing data to Artist Payment Systems app in Pirate to calculate payment..." "Integration"
        etb = braz -> cedw "EDW to Braze" "Datawarehouse Viewer data send into Braze platform" "Integration"
        etm- = cedw -> as "EDW to Mediarithmics - Instream Promo Control Audience Upload" "Manual CSV file upload to Mediarithmics using SQL to extract and prepare files from EDWLIV (Redsh..." "Integration"
        etm-X = as -> cedw "EDW to Mediarithmics - Streaming User Data" "Streaming user data from EDW is sent to Mediarithmics. Added as part of Streaming Transformation,..." "Integration"
        ett- = thin -> cedw "EDW to ThinkAnalytics - Viewers" "TBC" "Integration"
        etdfX = cedw -> pira "EDW TX data feed to Pirate" "BARB programme and schedule viewing shares, TX historical revenue, VoD views data and Sales certi..." "Integration"
        fgl = pira -> ebs "Failed GL lines" "TBC" "Integration"
        fvte = fsh -> cedw "Feewheel v4logs to EDW" "*freewheel-load-v4logs-raw-files job loading Freewheel v4logs from the adserver to EDW Data Wareh..." "Integration"
        fate = ebs -> faf "Finance Approval to E-Business Suite" "TBC" "Integration"
        ffsf = fsh -> cedw "Freewheel from Stellar for Forecast data of VOD Campaign" "Send forecast for VOD campaigns from both Stellar and Enterprise Data Warehouse (EDW) to Freewheel" "Integration"
        ffsf2 = fsh -> stel "Freewheel from Stellar for Forecast data of VOD Campaign" "Send forecast for VOD campaigns from both Stellar and Enterprise Data Warehouse (EDW) to Freewheel" "Integration"
        fltm = fsh -> df "Freewheel logs to Microsoft Data Fabric" "A data pipeline to create a data model which is going to provide Freewheel related ad metric data..." "Integration"
        ftie = dcri -> fsh "Freewheel to Infosum (Exposed Campaign Users Attribution)" "The interface facilitates the transfer of campaign user attribution data from Freewheel to Infosu..." "Integration"
        ftsf = fsh -> stel "Freewheel to Stellar for Freewheel reference data changes API" "Java programme on Stellar periodically checking changes on the Freewheel API" "Integration"
        ftsv = fsh -> stel "Freewheel to Stellar VoD Views for Commercial, Sponsorship and Promotions" "This interface is used to propagate data from Freewheel to Stellar on Commercial, Sponsorship and..." "Integration"
        frtp = msp -> prta "From RedBee to Pirate ASRUN" "Business Critical, real time as run (RTAR): This app is listening messages from new LSP SSAPI str..." "Integration"
        fstp = stel -> pira "From Stellar to Pirate for Commercial Registrations" "Imports Commercial registration details generated by Stellar into Pirate. Pirate would then gener..." "Integration"
        idtc = bynd -> c4sl "Image DAM to C4S" "TBC" "Integration"
        imcf = sounXX -> pira "Interstial music cuesheets from Soundmouse to Pirate" "Programme and interstitial information ftp upload to Soundmouse" "Integration"
        infr = pris -> ebs "Invoice/credit note for Royalties" "Contains the statement pack invoice and credit notes details that are sent to Oracle eBusiness Suite" "Integration"
        lspp = pira -> c4sl "Logging Sheets & Programme Parts" "TBC" "Integration"
        lcfl = lsp -> ppsp "LSP Contribution Feed ( Line Record)" "TBC" "Integration"
        lmfd = lsp -> msp "LSP Media File Delivery" "TBC" "Integration"
        lm = lsp -> osp "LSP Multicast" "TBC" "Integration"
        lsto = osp -> lsp "LSP Simulcast to OSLP" "RedBee Provides the simulcast stream to PFT" "Integration"
        ltpa = pira -> lsp "LSP to Pirate Asruns" "TBC" "Integration"
        mtbb = bynd -> modX "MediaGenix to Bynder Brand" "Integration creating/updating brands (name, id) from MediaGenix On-Demand to Bynder." "Integration"
        mtfp = fsh -> modX "MediaGenix to FreeWheel Programme Info" "MediaGenix sends FreeWheel (FW) IVI messages (meta data about programmes)." "Integration"
        mtgc = grac -> modX "MediaGenix to Gracenote Channel 4 VoD Catalogue" "TBC" "Integration"
        mtmb = modX -> modX "MediaGenix to MediaGenix BARB VOD Schedule Integration" "Integration creating and updating BARB VOD schedules based on the content availability on owned &..." "Integration"
        mtpe = pira -> modX "MediaGenix to Pirate EPG Content Warnings" "Integration updating Pirate linear schedule with media asset content warnings from MediaGenix On-..." "Integration"
        mttc = thin -> modX "MediaGenix to ThinkAnalytics Channel 4 VoD Catalogue" "TBC" "Integration"
        mtbf = braz -> as "Mediarithmics to Braze for Marketing Segments" "TBC" "Integration"
        mtff = fsh -> as "Mediarithmics to Freewheel for ALA segments" "ALA segment upload to Freewheel generated and curated in Mediarithmics SaaS tool" "Integration"
        mtic = dcri -> as "Mediarithmics to Infosum (Control Group attribution)" "Segments containing control group users (GUIDs) from mediarithmics are exported and then uploaded..." "Integration"
        mvrt = msp -> modX "MoD  VoD Request to PFT" "VoD Request from MoD to PFT Clear" "Integration"
        msdt = sm -> cedw "MPP Subscriber data to EDW" "MPP Channel 4 Streaming subscriber data to Redshift EDW" "Integration"
        mcra = msp -> asp "MSP Content Request API" "TBC" "Integration"
        mcra2 = msp -> lsp "MSP Content Request API" "TBC" "Integration"
        mcra3 = msp -> osp "MSP Content Request API" "TBC" "Integration"
        mcra4 = msp -> ppsp "MSP Content Request API" "TBC" "Integration"
        mmvf = msp -> osp "MSP Master Video Files to OLSP" "TBC" "Integration"
        mmfd = msp -> dist "MSP Media File Delivery - Acquired BBC Studios" "TBC" "Integration"
        mmfdX = msp -> dist "MSP Media File Delivery - Acquired Fox/Disney" "TBC" "Integration"
        mmfdXX = msp -> dist "MSP Media File Delivery - Acquired Generic" "TBC" "Integration"
        mmfdXXX = msp -> dist "MSP Media File Delivery - Acquired Sony" "TBC" "Integration"
        mmfdXXXX = msp -> dist "MSP Media File Delivery - Acquired Turner" "TBC" "Integration"
        mmfdXXXXX = msp -> dist "MSP Media File Delivery - Acquired Warner" "TBC" "Integration"
        mmfdXXXXXX = msp -> cari "MSP Media File Delivery - Commercials" "TBC" "Integration"
        mmfd2 = msp -> cc "MSP Media File Delivery - Commercials" "TBC" "Integration"
        mmfdXXXXXXX = msp -> pcXX "MSP Media File Delivery - Commissioned Programmes" "TBC" "Integration"
        mmfdXXXXXXXX = msp -> pcXX "MSP Media File Delivery - Interstitials" "TBC" "Integration"
        mmfdXXXXXXXXX = msp -> lsp "MSP Media File Delivery - LSP Video Recordings" "TBC" "Integration"
        mmfdXXXXXXXXXX = msp -> lsp "MSP Media File Delivery - LSP Voiceover Recordings" "TBC" "Integration"
        mmfdXXXXXXXXXXX = msp -> stel "MSP Media File Delivery - MB Media to Stellar for Long Form teleshopping" "Shows which teleshopping long format adverts should go out when on which channel (one message per..." "Integration"
        mmfdXXXXXXXXXXXX = msp -> cari "MSP Media File Delivery - Music Videos" "TBC" "Integration"
        mmfdXXXXXXXXXXXXX = msp -> asp "MSP Media File Delivery - Subtitles & Audio Description" "TBC" "Integration"
        mmfdXXXXXXXXXXXXXX = msp -> asp "MSP Media File Delivery - Supertrusted" "TBC" "Integration"
        mmfd2X = msp -> ppsp "MSP Media File Delivery - Supertrusted" "TBC" "Integration"
        mpvb = msp -> pvbX "MSP Pirate Video Browse API" "TBC" "Integration"
        mpvbX = msp -> pvbX "MSP Pirate Video Browse File Hosting" "TBC" "Integration"
        msfr = msp -> pira "MSP Schedule File Receipt" "TBC" "Integration"
        mti = msp -> uv "MSP Tape Ingest" "TBC" "Integration"
        mtp = pmmX -> msp "MSP to Pirate" "JSON wrapper for programme operations of BTO Metadata Exchange Service and MMWebService" "Integration"
        mtrt = rta -> msp "MSP to Ready to Air" "TBC" "Integration"
        mts = sounXX -> msp "MSP to Soundmouse" "TBC" "Integration"
        mtc4 = msp -> pira "MSPs to Channel 4 DFS folders" "External parties deliver multiple file types (As-Runs, Vod Delivery Receipts, etc) to C4 S3 bucke..." "Integration"
        nos = pc -> prrs "Name of Supplier" "This data will subsequently be used in the Producer's Statements generation process. RRS applicat..." "Integration"
        ntn = pris -> pira "New transmitted notifications" "These are new transmitted notifications that are generated when a programme is transmitted, e.g.,..." "Integration"
        oets = ebs -> ebs "Oracle EBS to SplashBI (Oracle eBS Schema)" "TBC" "Integration"
        oets2 = ebs -> sbi "Oracle EBS to SplashBI (Oracle eBS Schema)" "TBC" "Integration"
        oscn = ebs -> prrs "Oracle suppliers contact names" "Provides contacts in RRS for financiers and writers. In the new system we also want to retrieve d..." "Integration"
        ota = ebs -> atax "Oracle to AlphaTax" "Provides alphatax reporting data from eBS" "Integration"
        otpx = ebs -> ebs "Oracle to PublicIS XML Invoice feed" "Integration between Oracle EBS and PublicIS, via Mulesoft. Integration to provide invoice data in..." "Integration"
        ottx = ebs -> tgn "Oracle to Tungsten XML Invoice feed" "Integration that takes an XML generated invoice feed from Oracle server and moves to Tungsten ser..." "Integration"
        pfpf = sounXX -> pira "PAC form PDFs from Soundmouse to Pirate" "Production details (PAC forms) PDFs from Soundmouse to Pirate over FTP" "Integration"
        pfxf = sounXX -> pira "PAC form XMLs from Soundmouse to Pirate" "Production details (PAC forms) XMLs from Soundmouse to Pirate over FTP" "Integration"
        pmfs = msp -> stel "Peach Media from Stellar for Attribution files" "Send Attribution files generated in STELLAR and transfer them from C4 Shared location to Peach Me..." "Integration"
        patv = pira -> passX "Pirate A55 to VMS (ex Optimum)" "This app picks up the notification generated in the back-end systems to send to Optimum clients. ..." "Integration"
        patv2 = pira -> pepl "Pirate A55 to VMS (ex Optimum)" "This app picks up the notification generated in the back-end systems to send to Optimum clients. ..." "Integration"
        patv3 = pira -> pvms "Pirate A55 to VMS (ex Optimum)" "This app picks up the notification generated in the back-end systems to send to Optimum clients. ..." "Integration"
        passXX = pira -> c4sl "Pirate Advance Scheduling System to C4S" "TBC" "Integration"
        pctc = pira -> c4sl "Pirate Certification to C4S" "TBC" "Integration"
        pctb = bynd -> pcgs "Pirate CGS to Bynder" "This application provides REST API interface for OpenText Media Management application to retriev..." "Integration"
        pctf = fsh -> pcgs "Pirate CGS to Freewheel" "This picks up relevant messages from the VPS MGS (Message Generation Service) service and sends t..." "Integration"
        pctm = msp -> pcgs "Pirate CGS to MSP for VPS origin" "This is called by VPS on completion of transcode. It calls the Origin service to generate the cor..." "Integration"
        pcts = pcgs -> stel "Pirate CGS to Stellar for Programme and Platform information" "Which programmes are available on which VOD platforms at between which times. Note that it is onl..." "Integration"
        pctfX = fsh -> pcgs "Pirate Creatives to Freewheel" "This app sends FW Creative messages (Commercials, Promos, Pres items) to the FW creative endpoint." "Integration"
        pffr = pira -> asp "Pirate fetch from RedBee for Subtitles" "This provides a service to Redbee to notify C4 of new subtitle files." "Integration"
        pgpt = ebs -> come "Pirate GL posted Transactions" "Interface of payables invoice postings from Oracle General Ledger to the Pirate system" "Integration"
        ppta = msp -> pppsXXX "Pirate PPS to AWS S3 Bucket" "The c4-content outbound-s3 Mule application is developed to upload schedule files for ASP,MSP and..." "Integration"
        ppit = fsh -> pcgs "Pirate Programme Info to FreeWheel" "This Mule app sends FreeWheel (FW) IVI messages (meta data about programmes) to the FW IVI endpoint." "Integration"
        prmsX = pira -> c4sl "Pirate Rights Management System to C4S" "TBC" "Integration"
        prdt = prms -> cedw "PIRATE RMS data to  Oracle EDW" "TBC" "Integration"
        pta = ac -> modX "Pirate To Amagi" "CSV export created from Mediagenix reporter to generate CSV for import too Amagi" "Integration"
        ptbf = modX -> pira "Pirate to BeBanjo for Catalogue Assets" "This Application Includes the C4 → Bebanjo's Movida Catalog Integration. This facilitates synchro..." "Integration"
        ptbf2 = modX -> pp "Pirate to BeBanjo for Catalogue Assets" "This Application Includes the C4 → Bebanjo's Movida Catalog Integration. This facilitates synchro..." "Integration"
        ptbfX = modX -> pira "Pirate to BeBanjo for Linear Scheduling" "This Application Includes the C4 → Bebanjo's Movida Linear Scheduling Integration. This Mule app ..." "Integration"
        ptbf2X = modX -> passX "Pirate to BeBanjo for Linear Scheduling" "This Application Includes the C4 → Bebanjo's Movida Linear Scheduling Integration. This Mule app ..." "Integration"
        ptbfXX = modX -> pira "Pirate to BeBanjo for Media Assets" "This Mule app facilitates synchronisation between C4 Pirate and BeBanjo Movida for Media Assets. ..." "Integration"
        ptbf2XX = modX -> pmmX "Pirate to BeBanjo for Media Assets" "This Mule app facilitates synchronisation between C4 Pirate and BeBanjo Movida for Media Assets. ..." "Integration"
        ptbfXXX = modX -> prms "Pirate to BeBanjo for Rights" "This Application Includes the C4 → Bebanjo's Movida Rights Integration. This facilitates Rights d..." "Integration"
        ptbfXXXX = modX -> pira "Pirate to BeBanjo for Segment" "This Application Includes the C4 → Bebanjo's Movida Segments Integration. This Mule app facilitat..." "Integration"
        ptbd = pmmX -> bynd "Pirate to Bynder data flow" "Brand and other programme specifc data flow of assets and images from pirate to bynder. Attribute..." "Integration"
        ptcp = msp -> pvbX "Pirate to Clear (Prime Focus Technology)" "The c4-content-videobrowse application is developed to send videobrowse commands to PFT Clear. Th..." "Integration"
        ptcs = pira -> msp "Pirate to Compliance Service" "This provides an end point for authorised 3rd parties to access the Compliance service. *** MULE ..." "Integration"
        ptdf = et -> pira "Pirate to DUK Freesat VOD publication" "Sends VOD schedule data in TVA format to DUK" "Integration"
        ptdfX = et -> pira "Pirate to DUK Freeview VOD publication" "Sends VOD schedule data in TVA format to DUK" "Integration"
        pte = pira -> ebs "Pirate to EBS" "E-business synchronisation of project codes from Pirate Project tables" "Integration"
        ptes = pira -> msp "Pirate to Editorial Service" "This provides an end point for authorised 3rd parties to access the Editorial service. *** MULE i..." "Integration"
        ptgc = pira -> grac "Pirate to Gracenote Channel 4 channel EPGs" "TBC" "Integration"
        ptgm = pira -> grac "Pirate to Gracenote music channel EPGs" "TBC" "Integration"
        ptk = pppsXXX -> barb "Pirate to Kantar" "This app sends Asset Level metadata to the Kantar Media sFTP (for the BARB ContentID Master file)" "Integration"
        ptkf = barb -> pmmX "Pirate to Kantar for Assets" "The c4pirate-kantar-asset Mule app is used by VOD (i.e. non-linear) to push asset update messages..." "Integration"
        ptl = lsp -> pira "Pirate To LSP" "TBC" "Integration"
        ptl2 = lsp -> stel "Pirate To LSP" "TBC" "Integration"
        ptmo = modX -> pira "Pirate to MediaGenix On-Demand Content Metadata" "This is the interface to copy content metadata from Pirate to Bebanjo" "Integration"
        ptmo2 = modX -> pepl "Pirate to MediaGenix On-Demand Content Metadata" "This is the interface to copy content metadata from Pirate to Bebanjo" "Integration"
        ptpo = pppsXXX -> po "Pirate To Promo Optimser" "TBC" "Integration"
        ptss = lsp -> pppsXXX "Pirate to Schedule Service" "This provides an end point for authorised 3rd parties to access the Schedule service. *** MULE in..." "Integration"
        pts = pira -> stel "Pirate to Stellar" "TBC" "Integration"
        ptsf = pittX -> stel "Pirate to Stellar for ASRUN commercial" "ASRUN transmission log of event aired for a day. Events consists of spots." "Integration"
        ptsfX = pppsXXX -> stel "Pirate to Stellar for ASRUN Non-commercial" "A log of all events that have played out on a channel (for a day) for non-commercial data" "Integration"
        ptsfXX = pppsXXX -> stel "Pirate to Stellar for Schedule & Event timings" "TBC" "Integration"
        ptsu = stel -> ap "Pirate to Stellar update for Brand" "Update Stellar Series with Brand information fetched from Pirate" "Integration"
        pvtr = msp -> ptis "Pirate VPS to (RedBee, M2A, PFT, NLDR)" "This acts as the conduit between VPS and Redbee / M2A / NLDR for all VOD transcode and delivery r..." "Integration"
        pvts = msp -> pmmX "Pirate VPS to S3" "This provides a service to VPS to upload images to the S3 bucket." "Integration"
        pwft = pira -> stel "Pirate Weekly Forecast to Stellar" "TBC" "Integration"
        pvtc = prrs -> prms "Portal view to capture Royalty Producer shares" "In RMS there is a portal view of the agreements in RRS which allows the user to complete the reve..." "Integration"
        pdfp = sounXX -> pira "Post-TX data from Pirate to Soundmouse" "Programme and interstitial as run information via ftp upload to Soundmouse" "Integration"
        pcfX = ppsp -> lsp "PPSP Contribution Feed" "TBC" "Integration"
        pmfd = ppsp -> msp "PPSP Media File Delivery" "Source content delivery" "Integration"
        pdfpX = sounXX -> pira "Pre-TX data from Pirate to Soundmouse" "Programme and interstitial information ftp upload to Soundmouse" "Integration"
        prte = come -> ebs "Producer Reporting to EBS" "This process updates Oracle Finance with the most up-to-date Comet (C4I and Film4) data on Contra..." "Integration"
        prto = ebs -> come "Producer Reporting to Oracle eBusiness Suite " "This process updates Oracle Finance with the most up-to-date Comet (C4I and Film4) data on Contra..." "Integration"
        pptp = ppp -> pcc "Producers Portal to Pirate for Ed Spec Diversity info" "Editorial Specification Diversity information" "Integration"
        pasm = sounXX -> pira "Programme and social media clip music cuesheets from Soundmouse to Pirate" "Programme and interstitial information ftp upload to Soundmouse" "Integration"
        ppi = ebs -> pira "programme Payments Interface" "TBC" "Integration"
        pctmX = modX -> pcX "Promo Create To Movida" "TBC" "Integration"
        pctp = pira -> pcX "Promo Create To Pirate" "TBC" "Integration"
        potp = pira -> po "Promo Optimiser to Pirate" "TBC" "Integration"
        rtat = lsp -> c4sl "Real Time As-Run to ALL 4" "Real time ASRUN dataflow from Red Bee to Mule" "Integration"
        rdfp = pira -> pris "Recoupment/Advances data from Programme Finance Committee form" "Recoupment/advances can be pulled into RIS for the contract, when they are present in the Program..." "Integration"
        rad = pcc -> pap "Repeat agreement data" "Populates the repeat agreement data in APS to create the repeat event, When the repeat agreement ..." "Integration"
        rtc7 = prms -> c7t "Rights to C4 7A Titles" "TBC" "Integration"
        rswe = pc -> prrs "Royalty Statement (welcome Email)" "The statement that RRS produces to show the total revenue due to the producer is emailed to that ..." "Integration"
        sctf = ebs -> sc "Sales CRM to Finance ERP - Customer Master Data" "TBC" "Integration"
        sctfX = ebs -> sc "Sales CRM to Finance ERP - Invoice Creation" "TBC" "Integration"
        se = come -> pap "Sales Entry" "Manual sales entry created in APS for the sales reference provided by Comet UK secondary sales Wh..." "Integration"
        str = lsp -> pira "SSAPI to RTAR" "Open pipe from LSP to PIRATE XML fragments continuous feed" "Integration"
        sdfp = prrs -> bsw "Statement data (for pre-approved PO's)" "A new interface will be required to share the unique ID/PO number on statement summaries with the..." "Integration"
        scdt = ap -> stel "Stellar commercial data to Agencies" "The agencyportal Mule application is used to provide services to various Agencies, Module agencyp..." "Integration"
        stap = ap -> stel "Stellar to Agency Portal &  K2 for programme data" "Call Stellar webservices from Agency Portal, K2 Dashboard for Taxonomy and Reconciliator services," "Integration"
        stapX = ap -> stel "Stellar to Agency Portal for CB and PIB" "Data pipeline for moving Agency Portal aggregate data into AWS redshift so that the Agency can ha..." "Integration"
        stef = ebs -> stel "Stellar to EBS for Sales Orders & New Customers" "TBC" "Integration"
        ste- = stel -> cedw "STELLAR to EDW - Campaign Position and Deal Position at Group Level" "ETL job loads data periodically from STELLAR to Coeus for Campaign and Deal positions. FACT_CM_PO..." "Integration"
        ste-X = stel -> cedw "STELLAR to EDW - Data to be used in PIB & CB reporting" "ETL job name: SDW_JOB_agreement_deal_basis" "Integration"
        ste-XX = stel -> cedw "STELLAR to EDW - Processes Base Price Group data" "ETL job loads Price/Revenue data from STELLAR to Coeus for further analytics and reporting FACT_B..." "Integration"
        ste-XXX = stel -> cedw "STELLAR to EDW - ROI Sponsorship Revenue values per transmission" "TBC" "Integration"
        ste-XXXX = stel -> cedw "STELLAR to EDW - Sponsorship campaign data" "ETL job loads sponsorship data from STELLAR operational database to the analytics data platform E..." "Integration"
        stff = fsh -> stel "Stellar to Freewheel for Agencies, Brand, Deals and Campaigns" "Stellar pull/push interface with Freewheel for Sales Campaigns data and all the required referent..." "Integration"
        stna = barb -> stel "Stellar to NIELSEN and BARB for post transmission Spot Log" "Informing BARB, NIELSEN on what we transmitted. Shows which commercials where broadcasted during ..." "Integration"
        stof = stel -> ebs "Stellar to Oracle Financials about Agency financial exposure" "Interface propagates information from Stellar to Oracle Financials about Agency financial risk ex..." "Integration"
        stofX = stel -> ebs "Stellar to Oracle Financials on Credit Policy" "Interface propagates data on Credit limits and future bookings for an agency between Consumer and..." "Integration"
        stofXX = stel -> ebs "Stellar to Oracle Financials on invoicing" "An invoice across business streams (sponsorship, online and commercial). Same interface is used f..." "Integration"
        stpm = msp -> stel "Stellar to Peach Media for Spot Plus files" "Send Echo files from C4 Shared location to PeachMedia. Mule" "Integration"
        stpf = pppsXXX -> stel "Stellar to Pirate for Commercial break pattern information" "Commercial break (not programme break), time length and certification. Sent to different location..." "Integration"
        stpfX = stel -> pppsXXX "Stellar to Pirate for Commercial Copy Registrations" "Clock number duration and title. Flat file. Extension is .rec. Contains all new commercial clocks..." "Integration"
        stpfXX = pittX -> stel "Stellar to Pirate for commercial playlist" "Complete playlist of the commercial airtime, which is sent to the Playout Partner for final delivery" "Integration"
        stpfXXX = stel -> pppsXXX "Stellar to Pirate for Product placement indicator" "Contains series and episodes of programmes, and indicates which programmes contain some form of p..." "Integration"
        stpfXXXX = stel -> pppsXXX "Stellar to Pirate for Promotional Campaigns" "TBC" "Integration"
        stpfXXXXX = stel -> pppsXXX "Stellar to Pirate for Promotions Copy Registrations" "Promotional copy information such as certification and duration and clock number .All owned chann..." "Integration"
        stpfXXXXXX = stel -> pppsXXX "Stellar to Pirate for Sponsorship Campaign" "Sponsorship campaigns contain details such as dates, channel(s)," "Integration"
        stpfXXXXXXX = stel -> pppsXXX "Stellar to Pirate for Sponsorship Clocknumbers or Copy" "Sponsorship copy IDs (clock numbers). Sent per partner (e.g. UKTV get one) for all our media part..." "Integration"
        stpfXXXXXXXX = stel -> pppsXXX "Stellar to Pirate for Sponsorship Events" "Sponsorship event schedules with clock numbers." "Integration"
        stpfXXXXXXXXX = stel -> pppsXXX "Stellar to Pirate for Sponsorship Events for Partners" "Sponsorship event schedules with clock numbers." "Integration"
        stpfXXXXXXXXXX = stel -> pppsXXX "Stellar to Pirate for Trail patterns" "Metadata around promotions: Which copy belongs to which promos, does it have any restrictions, wh..." "Integration"
        stuf = msp -> stel "Stellar to UKTV for Ad Certification" "Interface populates the Certificate number of each UKTV programme inside stellar" "Integration"
        stufX = msp -> stel "Stellar to UKTV for Commercial Copy Registrations" "UKTV Sponsorship Copy details by campaign" "Integration"
        scte = c4sl -> cedw "Streaming Consent to EDW" "The platform event bus surfaces events such as user registrations, payments, new content publishe..." "Integration"
        sbde = ebs -> pap "Supplier Bank Details Exist" "When the payment batch is released in APS to make the payment, checks to see the payee's bank det..." "Integration"
        sffp = prrs -> cedw "Supplier fields from PIRATE to COEUS and Oracle EDW" "RRS data from PIRATE synchronised both with Oracle EDW and Redshift EDW. Ultimate Supplier & Supp..." "Integration"
        si = ebs -> pris "Supplier Information" "Holds the production company name & address, used to populate the invoice and distributor details..." "Integration"
        sr = ebs -> pap "Supplier Records" "A unique reference generated in APS which is stored as supplier record in Oracle, New Agent/FSO/A..." "Integration"
        ttn = sounXX -> pira "Ted to Neo" "Social media clip video asset files to Soundmouse Neo for automatic audio recognition over FTP" "Integration"
        tts = sounXX -> pira "Ted to Silvermouse" "Social media clip information to Soundmouse Neo for automatic audio recognition over FTP. Files a..." "Integration"
        ttc- = thin -> c4sl "ThinkAnalytics to C4S - Recommendation" "TBC" "Integration"
        tsfp = barb -> passX "TX Schedule from PIRATE to BARB" "Daily TX Transmission logs deliverd to BARB for Viewer and Audience calculations in their panels" "Integration"
        vptc = osp -> c4sl "Video Pipeline to C4S" "This has been better modelled by [OLSP Video Assets to JOS](https://channel4.leanix.net/Channel4P..." "Integration"
        vtcs = msp -> ppc "VisionCloud to Compliance Service" "Sending VisionCloud generated EDL files to transformation in Mule and addition (via Mule) into Co..." "Integration"
        vvd = cedw -> prrs "VOD Views Data" "The VOD views are required for the VOD revenue stream reporting so that it can be calculated agai..." "Integration"
        waad = wa -> cedw "Web Analytics (AA) data to EDW" "TBC" "Integration"
        wats = wda -> ebs "Workday Adaptive to SplashBI (Oracle eBS Schema)" "Takes CoA hierarchies from Workday to SplashBI staging table, within Oracle eBS db." "Integration"
        wats2 = wda -> sbi "Workday Adaptive to SplashBI (Oracle eBS Schema)" "Takes CoA hierarchies from Workday to SplashBI staging table, within Oracle eBS db." "Integration"
        
    }
    
    views {
        
        terminology {
            person "Team"
            softwareSystem "Platform"
            container "Application"
        }
        
        themes https://raw.githubusercontent.com/synchrotron/c4c4/main/assets/c4-default-theme.json
        
        branding {
            logo https://raw.githubusercontent.com/synchrotron/c4c4/main/assets/4-logo-black.png
            font "4Text" https://raw.githubusercontent.com/synchrotron/c4c4/main/assets/4Text-Regular.ttf
        }
        

    }
}